//! Generated by tsz compiler — cursor-ide [state.zig]
//! Source: cursor-ide.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

