//! Generated by tsz compiler — d93_dashboard_full [logic.zig]
//! Source: d93_dashboard_full.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var activeNav = 0;
    \\function setActiveNav(v) { activeNav = v; if (__luaReady) __luaEval("setActiveNav(" + v + ")"); else __markDirty(); }
    \\var darkMode = 1;
    \\function setDarkMode(v) { darkMode = v; if (__luaReady) __luaEval("setDarkMode(" + v + ")"); else __markDirty(); }
    \\var userCount = 0;
    \\function setUserCount(v) { userCount = v; if (__luaReady) __luaEval("setUserCount(" + v + ")"); else __markDirty(); }
    \\var eventCount = 0;
    \\function setEventCount(v) { eventCount = v; if (__luaReady) __luaEval("setEventCount(" + v + ")"); else __markDirty(); }
    \\var selectedUser = "";
    \\function setSelectedUser(v) { selectedUser = v; if (__luaReady) __luaEval("setSelectedUser(\'" + v + "\')"); else __markDirty(); }
    \\var sortDir = 0;
    \\function setSortDir(v) { sortDir = v; if (__luaReady) __luaEval("setSortDir(" + v + ")"); else __markDirty(); }
    \\var filterActive = 0;
    \\function setFilterActive(v) { filterActive = v; if (__luaReady) __luaEval("setFilterActive(" + v + ")"); else __markDirty(); }
    \\var notifCount = 3;
    \\function setNotifCount(v) { notifCount = v; if (__luaReady) __luaEval("setNotifCount(" + v + ")"); else __markDirty(); }
    \\var sidebarOpen = 1;
    \\function setSidebarOpen(v) { sidebarOpen = v; if (__luaReady) __luaEval("setSidebarOpen(" + v + ")"); else __markDirty(); }
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var metrics = [ { label : "" , value : 0 , delta : 0 , color : 0x000000 } ];
    \\function setMetrics(v) { metrics = v; __markDirty(); }
    \\var users = [ { name : "" , role : "" , active : 0 } ];
    \\function setUsers(v) { users = v; __markDirty(); }
    \\var events = [ { msg : "" , time : "" , type : 0 } ];
    \\function setEvents(v) { events = v; __markDirty(); }
    \\var m = [];
    \\var u = [];
    \\var e = [];
    \\var m = [
    \\  { label: 'Users', value: 1420, delta: 12, color: 0x3b82f6 },
    \\  { label: 'Revenue', value: 89400, delta: 8, color: 0x22c55e },
    \\  { label: 'Orders', value: 342, delta: -3, color: 0xf59e0b },
    \\  { label: 'Tickets', value: 17, delta: -22, color: 0xef4444 },
    \\  { label: 'Uptime', value: 99, delta: 0, color: 0x8b5cf6 },
    \\  { label: 'Latency', value: 42, delta: 5, color: 0x14b8a6 }
    \\];
    \\setMetrics(m);
    \\
    \\var u = [
    \\  { name: 'Alice Chen', role: 'admin', active: 1 },
    \\  { name: 'Bob Kim', role: 'dev', active: 1 },
    \\  { name: 'Carol Wu', role: 'design', active: 0 },
    \\  { name: 'Dave Park', role: 'dev', active: 1 },
    \\  { name: 'Eve Liu', role: 'admin', active: 1 },
    \\  { name: 'Frank Lee', role: 'dev', active: 0 }
    \\];
    \\setUsers(u);
    \\setUserCount(u.length);
    \\
    \\var e = [
    \\  { msg: 'Deploy v2.4.1 completed', time: '2m ago', type: 0 },
    \\  { msg: 'Alert: CPU spike on worker-3', time: '5m ago', type: 1 },
    \\  { msg: 'User alice promoted to admin', time: '1h ago', type: 0 }
    \\];
    \\setEvents(e);
    \\setEventCount(e.length);
    \\
    \\function addEvent(msg, type) {
    \\  e.push({ msg: msg, time: 'just now', type: type });
    \\  setEvents(e);
    \\  setEventCount(e.length);
    \\  setOutput('event: ' + msg);
    \\}
    \\
    \\function sortUsers() {
    \\  var list = u.slice();
    \\  for (var i = 0; i < list.length; i++) {
    \\    for (var j = i + 1; j < list.length; j++) {
    \\      if (sortDir === 0 && list[j].name < list[i].name) {
    \\        var tmp = list[i]; list[i] = list[j]; list[j] = tmp;
    \\      }
    \\      if (sortDir === 1 && list[j].name > list[i].name) {
    \\        var tmp2 = list[i]; list[i] = list[j]; list[j] = tmp2;
    \\      }
    \\    }
    \\  }
    \\  setSortDir(sortDir === 0 ? 1 : 0);
    \\  setUsers(list);
    \\  addEvent('Sorted users ' + (sortDir === 0 ? 'A-Z' : 'Z-A'), 0);
    \\}
    \\
    \\function toggleFilter() {
    \\  setFilterActive(filterActive === 0 ? 1 : 0);
    \\  if (filterActive === 0) {
    \\    var active = [];
    \\    for (var i = 0; i < u.length; i++) {
    \\      if (u[i].active === 1) active.push(u[i]);
    \\    }
    \\    setUsers(active);
    \\    setUserCount(active.length);
    \\  } else {
    \\    setUsers(u);
    \\    setUserCount(u.length);
    \\  }
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["activeNav"] = 0
    \\activeNav = _state["activeNav"]
    \\function setActiveNav(v) _state["activeNav"] = v; activeNav = v; __syncToJS("activeNav", v); __markDirty() end
    \\_state["darkMode"] = 1
    \\darkMode = _state["darkMode"]
    \\function setDarkMode(v) _state["darkMode"] = v; darkMode = v; __syncToJS("darkMode", v); __markDirty() end
    \\_state["userCount"] = 0
    \\userCount = _state["userCount"]
    \\function setUserCount(v) _state["userCount"] = v; userCount = v; __syncToJS("userCount", v); __markDirty() end
    \\_state["eventCount"] = 0
    \\eventCount = _state["eventCount"]
    \\function setEventCount(v) _state["eventCount"] = v; eventCount = v; __syncToJS("eventCount", v); __markDirty() end
    \\_state["selectedUser"] = ""
    \\selectedUser = _state["selectedUser"]
    \\function setSelectedUser(v) _state["selectedUser"] = v; selectedUser = v; __syncToJS("selectedUser", v); __markDirty() end
    \\_state["sortDir"] = 0
    \\sortDir = _state["sortDir"]
    \\function setSortDir(v) _state["sortDir"] = v; sortDir = v; __syncToJS("sortDir", v); __markDirty() end
    \\_state["filterActive"] = 0
    \\filterActive = _state["filterActive"]
    \\function setFilterActive(v) _state["filterActive"] = v; filterActive = v; __syncToJS("filterActive", v); __markDirty() end
    \\_state["notifCount"] = 3
    \\notifCount = _state["notifCount"]
    \\function setNotifCount(v) _state["notifCount"] = v; notifCount = v; __syncToJS("notifCount", v); __markDirty() end
    \\_state["sidebarOpen"] = 1
    \\sidebarOpen = _state["sidebarOpen"]
    \\function setSidebarOpen(v) _state["sidebarOpen"] = v; sidebarOpen = v; __syncToJS("sidebarOpen", v); __markDirty() end
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\
    \\metrics = {}
    \\function setMetrics(v) metrics = v; __markDirty() end
    \\users = {}
    \\function setUsers(v) users = v; __markDirty() end
    \\events = {}
    \\function setEvents(v) events = v; __markDirty() end
    \\m = {}
    \\u = {}
    \\e = {}
    \\
    \\function App()
    \\  return { style = { background_color = (darkMode == 1) and 0x0f172a or 0xf1f5f9, width = -1, height = -1, flex_direction = "row", overflow = "hidden" }, children = {
    \\    (sidebarOpen == 1) and { style = { width = 150, background_color = (darkMode == 1) and 0x1e293b or 0xffffff, padding = 12, gap = 4, border_color = (darkMode == 1) and 0x334155 or 0xe2e8f0, border_width = 1 }, children = {
    \\      { text = "Dashboard", font_size = 13, text_color = (darkMode == 1) and 0xe2e8f0 or 0x1e293b },
    \\      { style = { height = 8 } },
    \\      { style = { padding = 8, border_radius = 6, background_color = (activeNav == 0) and 0x334155 or 0x000000 }, lua_on_press = "setActiveNav(0)", children = {
    \\        { text = "Overview", font_size = 11, text_color = (activeNav == 0) and 0x3b82f6 or 0x94a3b8 }
    \\      } },
    \\      { style = { padding = 8, border_radius = 6, background_color = (activeNav == 1) and 0x334155 or 0x000000 }, lua_on_press = "setActiveNav(1)", children = {
    \\        { text = "Users", font_size = 11, text_color = (activeNav == 1) and 0x3b82f6 or 0x94a3b8 }
    \\      } },
    \\      { style = { padding = 8, border_radius = 6, background_color = (activeNav == 2) and 0x334155 or 0x000000 }, lua_on_press = "setActiveNav(2)", children = {
    \\        { text = "Events", font_size = 11, text_color = (activeNav == 2) and 0x3b82f6 or 0x94a3b8 }
    \\      } },
    \\      { style = { flex_grow = 1 } },
    \\      { style = { padding = 6, border_radius = 4, background_color = 0x334155 }, lua_on_press = "setDarkMode(darkMode == 0 and 1 or 0)", children = {
    \\        { text = (darkMode == 1) and "Light" or "Dark", font_size = 9, text_color = 0x94a3b8 }
    \\      } },
    \\      (notifCount > 0) and { style = { background_color = 0xef4444, border_radius = 10, padding_left = 6, padding_right = 6, padding_top = 2, padding_bottom = 2, align_self = "start" }, children = {
    \\        { text = tostring(notifCount) .. " new", font_size = 8, text_color = 0xffffff }
    \\      } } or nil
    \\    } } or nil,
    \\    { style = { flex_grow = 1, padding = 16, gap = 12, overflow = "auto" }, children = {
    \\      { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\        { style = { padding = 6 }, lua_on_press = "setSidebarOpen(sidebarOpen == 0 and 1 or 0)", children = {
    \\          { text = (sidebarOpen == 1) and "◀" or "▶", font_size = 14, text_color = 0x94a3b8 }
    \\        } },
    \\        { text = tostring(output), font_size = 9, text_color = 0x64748b }
    \\      } },
    \\      (activeNav == 0) and { children = {
    \\        { style = { flex_direction = "row", gap = 8, flex_wrap = "wrap" }, children = {
    \\          __mapLoop(metrics, function(_item, _i)
    \\            return { style = { background_color = (darkMode == 1) and 0x1e293b or 0xffffff, border_radius = 8, padding = 12, gap = 4, flex_grow = 1, min_width = 100, border_left_width = 3, border_color = _item.color, overflow = "auto" }, children = {
    \\              { text = tostring(_item.label), font_size = 9, text_color = (darkMode == 1) and 0x64748b or 0x94a3b8 },
    \\              { text = tostring(_item.value), font_size = 18, text_color = (darkMode == 1) and 0xe2e8f0 or 0x1e293b },
    \\              (_item.delta > 0) and { text = "+" .. tostring(_item.delta) .. "%", font_size = 8, text_color = 0x22c55e } or nil,
    \\              (_item.delta < 0) and { text = tostring(_item.delta) .. "%", font_size = 8, text_color = 0xef4444 } or nil,
    \\              (_item.delta == 0) and { text = "0%", font_size = 8, text_color = 0x64748b } or nil
    \\            } }
    \\          end)
    \\        } },
    \\        { style = { flex_direction = "row", gap = 12 }, children = {
    \\          { style = { flex_grow = 1, background_color = (darkMode == 1) and 0x1e293b or 0xffffff, border_radius = 8, padding = 12, gap = 4, overflow = "auto" }, children = {
    \\            { text = "Recent Events", font_size = 11, text_color = 0x94a3b8 },
    \\            __mapLoop(events, function(_item, _i)
    \\              return { style = { flex_direction = "row", gap = 6, padding = 4 }, children = {
    \\                (_item . type == 0) and { text = "INFO", font_size = 8, text_color = 0x22c55e } or nil,
    \\                (_item . type == 1) and { text = "ALERT", font_size = 8, text_color = 0xef4444 } or nil,
    \\                { text = tostring(_item.msg), font_size = 8, text_color = (darkMode == 1) and 0x94a3b8 or 0x64748b },
    \\                { text = tostring(_item.time), font_size = 7, text_color = 0x475569 }
    \\              } }
    \\            end)
    \\          } }
    \\        } }
    \\      } } or nil,
    \\      (activeNav == 1) and { style = { background_color = (darkMode == 1) and 0x1e293b or 0xffffff, border_radius = 8, padding = 12, gap = 8 }, children = {
    \\        { style = { flex_direction = "row", gap = 6 }, children = {
    \\          { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "sortUsers ( )", children = {
    \\            { text = "Sort", font_size = 9, text_color = 0xe2e8f0 }
    \\          } },
    \\          { style = { padding = 6, background_color = (filterActive == 1) and 0x1e40af or 0x334155, border_radius = 4 }, js_on_press = "toggleFilter ( )", children = {
    \\            { text = (filterActive == 1) and "Show All" or "Active Only", font_size = 9, text_color = 0xe2e8f0 }
    \\          } },
    \\          { text = tostring(userCount) .. " users", font_size = 9, text_color = 0x64748b }
    \\        } },
    \\        __mapLoop(users, function(_item, _i)
    \\          return { style = { flex_direction = "row", justify_content = "space_between", padding = 8, border_radius = 4, background_color = ((selectedUser == "_item.name")) and 0x334155 or 0x000000 }, js_on_press = "setSelectedUser(" .. (_item . name) .. ") ; addEvent(" .. ("Selected " + _item . name) .. ", 0)", children = {
    \\            { text = tostring(_item.name), font_size = 10, text_color = (darkMode == 1) and 0xe2e8f0 or 0x1e293b },
    \\            { style = { flex_direction = "row", gap = 6 }, children = {
    \\              { text = tostring(_item.role), font_size = 8, text_color = 0x7c3aed },
    \\              (_item . active == 1) and { text = "ON", font_size = 8, text_color = 0x22c55e } or nil,
    \\              (_item . active == 0) and { text = "OFF", font_size = 8, text_color = 0xef4444 } or nil
    \\            } }
    \\          } }
    \\        end)
    \\      } } or nil,
    \\      (activeNav == 2) and { style = { background_color = (darkMode == 1) and 0x1e293b or 0xffffff, border_radius = 8, padding = 12, gap = 4 }, children = {
    \\        { style = { flex_direction = "row", justify_content = "space_between" }, children = {
    \\          { text = "Event Log", font_size = 11, text_color = 0x94a3b8 },
    \\          { style = { padding = 4, background_color = 0x334155, border_radius = 4 }, js_on_press = "addEvent ( \"Manual event #\" + eventCount , 0 )", children = {
    \\            { text = "+ Add", font_size = 8, text_color = 0xe2e8f0 }
    \\          } }
    \\        } },
    \\        { style = { overflow = "scroll", flex_grow = 1 }, children = {
    \\          __mapLoop(events, function(_item, _i)
    \\            return { style = { flex_direction = "row", gap = 8, padding = 6, border_color = 0x334155, border_width = 1, border_radius = 4 }, children = {
    \\              { text = tostring((_i - 1)), font_size = 8, text_color = 0x475569 },
    \\              (_item . type == 0) and { style = { width = 4, height = 4, border_radius = 2, background_color = 0x22c55e, margin_top = 4 } } or nil,
    \\              (_item . type == 1) and { style = { width = 4, height = 4, border_radius = 2, background_color = 0xef4444, margin_top = 4 } } or nil,
    \\              { style = { flex_grow = 1, overflow = "auto" }, children = {
    \\                { text = tostring(_item.msg), font_size = 9, text_color = (darkMode == 1) and 0xe2e8f0 or 0x1e293b },
    \\                { text = tostring(_item.time), font_size = 7, text_color = 0x475569 }
    \\              } }
    \\            } }
    \\          end)
    \\        }, scroll_y = ((_scrollY and _scrollY[1]) or 0), scroll_persist_slot = 1 }
    \\      } } or nil
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then metrics = __luaMapData0 end
    \\  if __luaMapData1 then users = __luaMapData1 end
    \\  if __luaMapData2 then events = __luaMapData2 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

