//! Generated by tsz compiler — d88_data_table [nodes.zig]
//! Source: d88_data_table.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d88_data_table:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

