//! Generated by tsz compiler — counter [nodes.zig]
//! Source: counter.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:counter:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

