//! Generated by tsz compiler — d27a_array_methods_script [logic.zig]
//! Source: d27a_array_methods_script.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var sortDir = 0;
    \\function setSortDir(v) { sortDir = v; if (__luaReady) __luaEval("setSortDir(" + v + ")"); else __markDirty(); }
    \\var totalValue = 0;
    \\function setTotalValue(v) { totalValue = v; if (__luaReady) __luaEval("setTotalValue(" + v + ")"); else __markDirty(); }
    \\var matchCount = 0;
    \\function setMatchCount(v) { matchCount = v; if (__luaReady) __luaEval("setMatchCount(" + v + ")"); else __markDirty(); }
    \\var activeFilter = "";
    \\function setActiveFilter(v) { activeFilter = v; if (__luaReady) __luaEval("setActiveFilter(\'" + v + "\')"); else __markDirty(); }
    \\var items = [ { name : "" , category : "" , price : 0 , qty : 0 } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var filtered = [ { name : "" , category : "" , price : 0 , qty : 0 } ];
    \\function setFiltered(v) { filtered = v; __markDirty(); }
    \\var data = [];
    \\var data = [
    \\  { name: 'Hammer', category: 'tool', price: 25, qty: 4 },
    \\  { name: 'Apples', category: 'food', price: 3, qty: 12 },
    \\  { name: 'Wrench', category: 'tool', price: 18, qty: 7 },
    \\  { name: 'Bread', category: 'food', price: 4, qty: 5 },
    \\  { name: 'Drill', category: 'tool', price: 89, qty: 2 },
    \\  { name: 'Cheese', category: 'food', price: 7, qty: 8 },
    \\  { name: 'Pliers', category: 'tool', price: 12, qty: 6 },
    \\  { name: 'Rice', category: 'food', price: 2, qty: 20 },
    \\  { name: 'Saw', category: 'tool', price: 35, qty: 3 },
    \\  { name: 'Milk', category: 'food', price: 5, qty: 10 }
    \\];
    \\setItems(data);
    \\setFiltered(data);
    \\recalc(data);
    \\
    \\function recalc(list) {
    \\  var total = 0;
    \\  for (var i = 0; i < list.length; i++) {
    \\    total += list[i].price * list[i].qty;
    \\  }
    \\  setTotalValue(total);
    \\  setMatchCount(list.length);
    \\}
    \\
    \\function filterBy(cat) {
    \\  setActiveFilter(cat);
    \\  var result;
    \\  if (cat === '') {
    \\    result = items.slice();
    \\  } else {
    \\    result = [];
    \\    for (var i = 0; i < items.length; i++) {
    \\      if (items[i].category === cat) result.push(items[i]);
    \\    }
    \\  }
    \\  setFiltered(result);
    \\  recalc(result);
    \\}
    \\
    \\function sortByPrice() {
    \\  var list = filtered.slice();
    \\  for (var i = 0; i < list.length; i++) {
    \\    for (var j = i + 1; j < list.length; j++) {
    \\      if (sortDir === 0 && list[j].price < list[i].price) {
    \\        var tmp = list[i]; list[i] = list[j]; list[j] = tmp;
    \\      }
    \\      if (sortDir === 1 && list[j].price > list[i].price) {
    \\        var tmp2 = list[i]; list[i] = list[j]; list[j] = tmp2;
    \\      }
    \\    }
    \\  }
    \\  setSortDir(sortDir === 0 ? 1 : 0);
    \\  setFiltered(list);
    \\}
    \\
    \\function sortByName() {
    \\  var list = filtered.slice();
    \\  for (var i = 0; i < list.length; i++) {
    \\    for (var j = i + 1; j < list.length; j++) {
    \\      if (sortDir === 0 && list[j].name < list[i].name) {
    \\        var tmp = list[i]; list[i] = list[j]; list[j] = tmp;
    \\      }
    \\      if (sortDir === 1 && list[j].name > list[i].name) {
    \\        var tmp2 = list[i]; list[i] = list[j]; list[j] = tmp2;
    \\      }
    \\    }
    \\  }
    \\  setSortDir(sortDir === 0 ? 1 : 0);
    \\  setFiltered(list);
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["sortDir"] = 0
    \\sortDir = _state["sortDir"]
    \\function setSortDir(v) _state["sortDir"] = v; sortDir = v; __syncToJS("sortDir", v); __markDirty() end
    \\_state["totalValue"] = 0
    \\totalValue = _state["totalValue"]
    \\function setTotalValue(v) _state["totalValue"] = v; totalValue = v; __syncToJS("totalValue", v); __markDirty() end
    \\_state["matchCount"] = 0
    \\matchCount = _state["matchCount"]
    \\function setMatchCount(v) _state["matchCount"] = v; matchCount = v; __syncToJS("matchCount", v); __markDirty() end
    \\_state["activeFilter"] = ""
    \\activeFilter = _state["activeFilter"]
    \\function setActiveFilter(v) _state["activeFilter"] = v; activeFilter = v; __syncToJS("activeFilter", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\filtered = {}
    \\function setFiltered(v) filtered = v; __markDirty() end
    \\data = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 10, overflow = "hidden" }, children = {
    \\    { text = "Inventory", font_size = 16, text_color = 0xe2e8f0 },
    \\    { style = { flex_direction = "row", gap = 8 }, children = {
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "filterBy ( \"food\" )", children = {
    \\        { text = "Food", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "filterBy ( \"tool\" )", children = {
    \\        { text = "Tools", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "filterBy ( \"\" )", children = {
    \\        { text = "All", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x1e40af, border_radius = 4 }, js_on_press = "sortByPrice ( )", children = {
    \\        { text = "Sort $", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x1e40af, border_radius = 4 }, js_on_press = "sortByName ( )", children = {
    \\        { text = "Sort A-Z", font_size = 10, text_color = 0xe2e8f0 }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(filtered, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", padding = 8, background_color = 0x1e293b, border_radius = 4 }, children = {
    \\          { text = tostring(_item.name), font_size = 11, text_color = 0xe2e8f0 },
    \\          { text = tostring(_item.category), font_size = 11, text_color = 0x94a3b8 },
    \\          { text = "$" .. tostring(_item.price), font_size = 11, text_color = 0x6ee7b7 },
    \\          { text = "x" .. tostring(_item.qty), font_size = 11, text_color = 0xfbbf24 }
    \\        } }
    \\      end)
    \\    } },
    \\    { style = { flex_direction = "row", justify_content = "space_between", padding = 8, border_top_width = 1, border_color = 0x334155 }, children = {
    \\      { text = tostring(matchCount) .. " items · filter: " .. tostring(activeFilter), font_size = 10, text_color = 0x64748b },
    \\      { text = "total: $" .. tostring(totalValue), font_size = 10, text_color = 0x6ee7b7 }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  if __luaMapData1 then filtered = __luaMapData1 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

