//! Generated by tsz compiler — d72_typeof_operator [logic.zig]
//! Source: d72_typeof_operator.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var checks = 0;
    \\function setChecks(v) { checks = v; if (__luaReady) __luaEval("setChecks(" + v + ")"); else __markDirty(); }
    \\var items = [ { name : "" , val : 0 , kind : "" } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var data = [];
    \\var data = [
    \\  { name: 'count', val: 42, kind: 'number' },
    \\  { name: 'label', val: 0, kind: 'string' },
    \\  { name: 'flag', val: 1, kind: 'boolean' },
    \\  { name: 'empty', val: 0, kind: 'undefined' },
    \\  { name: 'score', val: 99, kind: 'number' }
    \\];
    \\setItems(data);
    \\
    \\function checkType(idx) {
    \\  var item = data[idx];
    \\  var result = 'unknown';
    \\  if (typeof item.val === 'number') {
    \\    result = item.name + ' is number (' + item.val + ')';
    \\  } else if (typeof item.val === 'string') {
    \\    result = item.name + ' is string';
    \\  } else if (typeof item.val === 'boolean') {
    \\    result = item.name + ' is boolean';
    \\  } else if (typeof item.val === 'undefined') {
    \\    result = item.name + ' is undefined';
    \\  }
    \\  setOutput(result);
    \\  setChecks(checks + 1);
    \\}
    \\
    \\function checkAll() {
    \\  var nums = 0;
    \\  for (var i = 0; i < data.length; i++) {
    \\    if (typeof data[i].val === 'number') nums++;
    \\  }
    \\  setOutput(nums + ' number values out of ' + data.length);
    \\  setChecks(checks + 1);
    \\}
    \\
    \\function typeofTest() {
    \\  var x = 42;
    \\  var t = typeof x;
    \\  setOutput('typeof 42 = ' + t);
    \\  setChecks(checks + 1);
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\_state["checks"] = 0
    \\checks = _state["checks"]
    \\function setChecks(v) _state["checks"] = v; checks = v; __syncToJS("checks", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\data = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "typeof Operator", font_size = 16, text_color = 0xe2e8f0 },
    \\    { text = "checks: " .. tostring(checks), font_size = 10, text_color = 0x64748b },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 8, background_color = 0x1e40af, border_radius = 6 }, js_on_press = "checkAll ( )", children = {
    \\        { text = "Check All", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "typeofTest ( )", children = {
    \\        { text = "typeof 42", font_size = 11, text_color = 0xe2e8f0 }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(items, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", padding = 8, background_color = 0x1e293b, border_radius = 4 }, js_on_press = "checkType(" .. ((_i - 1)) .. ")", children = {
    \\          { text = tostring(_item.name), font_size = 11, text_color = 0xe2e8f0 },
    \\          { style = { flex_direction = "row", gap = 6 }, children = {
    \\            { text = tostring(_item.val), font_size = 10, text_color = 0x6ee7b7 },
    \\            { text = tostring(_item.kind), font_size = 9, text_color = 0x7c3aed }
    \\          } }
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x6ee7b7 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

