//! Generated by tsz compiler — d112_triple_nested_component_map [state.zig]
//! Source: d112_triple_nested_component_map.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

