//! Generated by tsz compiler — d98_callback_prop_chain [logic.zig]
//! Source: d98_callback_prop_chain.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var selectedTitle = "";
    \\function setSelectedTitle(v) { selectedTitle = v; if (__luaReady) __luaEval("setSelectedTitle(\'" + v + "\')"); else __markDirty(); }
    \\var pinCount = 0;
    \\function setPinCount(v) { pinCount = v; if (__luaReady) __luaEval("setPinCount(" + v + ")"); else __markDirty(); }
    \\var archiveCount = 0;
    \\function setArchiveCount(v) { archiveCount = v; if (__luaReady) __luaEval("setArchiveCount(" + v + ")"); else __markDirty(); }
    \\var activity = "";
    \\function setActivity(v) { activity = v; if (__luaReady) __luaEval("setActivity(\'" + v + "\')"); else __markDirty(); }
    \\var tickets = [ { title : "" , team : "" , unread : 0 , pinned : 0 , severity : 0 , archived : 0 } ];
    \\function setTickets(v) { tickets = v; __markDirty(); }
    \\var rows = [];
    \\var rows = [
    \\  { title: 'Login loop on Safari', team: 'auth', unread: 4, pinned: 1, severity: 2, archived: 0 },
    \\  { title: 'Billing webhook retries', team: 'payments', unread: 2, pinned: 0, severity: 1, archived: 0 },
    \\  { title: 'Dark mode spacing cleanup', team: 'design', unread: 0, pinned: 0, severity: 0, archived: 0 },
    \\  { title: 'Import jobs stuck in queue', team: 'ops', unread: 6, pinned: 1, severity: 2, archived: 0 }
    \\];
    \\setTickets(rows);
    \\setSelectedTitle(rows[0].title);
    \\recalcPins();
    \\
    \\function recalcPins() {
    \\  var total = 0;
    \\  for (var i = 0; i < rows.length; i++) {
    \\    if (rows[i].archived === 0 && rows[i].pinned === 1) total++;
    \\  }
    \\  setPinCount(total);
    \\}
    \\
    \\function openTicket(idx) {
    \\  setSelectedTitle(rows[idx].title);
    \\  setActivity('opened ' + rows[idx].title);
    \\}
    \\
    \\function togglePin(idx) {
    \\  rows[idx].pinned = rows[idx].pinned === 1 ? 0 : 1;
    \\  setTickets(rows);
    \\  recalcPins();
    \\  setActivity((rows[idx].pinned === 1 ? 'pinned ' : 'unpinned ') + rows[idx].title);
    \\}
    \\
    \\function archiveTicket(idx) {
    \\  rows[idx].archived = 1;
    \\  setTickets(rows);
    \\  setArchiveCount(archiveCount + 1);
    \\  recalcPins();
    \\  setActivity('archived ' + rows[idx].title);
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["selectedTitle"] = ""
    \\selectedTitle = _state["selectedTitle"]
    \\function setSelectedTitle(v) _state["selectedTitle"] = v; selectedTitle = v; __syncToJS("selectedTitle", v); __markDirty() end
    \\_state["pinCount"] = 0
    \\pinCount = _state["pinCount"]
    \\function setPinCount(v) _state["pinCount"] = v; pinCount = v; __syncToJS("pinCount", v); __markDirty() end
    \\_state["archiveCount"] = 0
    \\archiveCount = _state["archiveCount"]
    \\function setArchiveCount(v) _state["archiveCount"] = v; archiveCount = v; __syncToJS("archiveCount", v); __markDirty() end
    \\_state["activity"] = ""
    \\activity = _state["activity"]
    \\function setActivity(v) _state["activity"] = v; activity = v; __syncToJS("activity", v); __markDirty() end
    \\_state["__jsExpr_4"] = ""
    \\__jsExpr_4 = _state["__jsExpr_4"]
    \\function __setJsExpr_4(v) _state["__jsExpr_4"] = v; __jsExpr_4 = v; __syncToJS("__jsExpr_4", v); __markDirty() end
    \\
    \\tickets = {}
    \\function setTickets(v) tickets = v; __markDirty() end
    \\rows = {}
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x020617, padding = 20, gap = 12, overflow = "hidden" }, children = {
    \\    { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\      { text = "Callback Prop Chain", font_size = 16, text_color = 0xf8fafc },
    \\      { text = tostring(pinCount) .. " pinned · " .. tostring(archiveCount) .. " archived", font_size = 10, text_color = 0x64748b }
    \\    } },
    \\    { style = { gap = 8 }, children = {
    \\      __mapLoop(tickets, function(_item, _i)
    \\        return (_item . archived == 0) and { style = { padding = 12, gap = 8, border_radius = 10, border_width = 1, border_color = (((((std.mem.eql(u8 == selectedTitle, "_item.title"))) and 1 or 0), "1")) and 0x60a5fa or 0x1f2937, background_color = (((((std.mem.eql(u8 == selectedTitle, "_item.title"))) and 1 or 0), "1")) and 0x172554 or 0x111827 }, children = {
    \\            { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\              { style = { gap = 3 }, children = {
    \\                { text = tostring(_item.title), font_size = 12, text_color = 0xf9fafb },
    \\                { text = tostring(_item.team) .. " · " .. tostring(_item.unread) .. " unread", font_size = 9, text_color = 0x94a3b8 }
    \\              } },
    \\              { text = tostring(__jsExpr_4), font_size = 8, text_color = (_item.severity == 2) and 0xf87171 or (_item.severity == 1) and 0xf59e0b or 0x34d399 }
    \\            } },
    \\            { style = { flex_direction = "row", gap = 6 }, children = {
    \\              { style = { padding_left = 8, padding_right = 8, padding_top = 5, padding_bottom = 5, border_radius = 999, background_color = 0x2563eb }, js_on_press = "openTicket(" .. ((_i - 1)) .. ")", children = {
    \\                { text = "Open", font_size = 8, text_color = 0xffffff }
    \\              } },
    \\              { style = { padding_left = 8, padding_right = 8, padding_top = 5, padding_bottom = 5, border_radius = 999, background_color = 0x7c3aed }, js_on_press = "togglePin(" .. ((_i - 1)) .. ")", children = {
    \\                { text = tostring(((_item.pinned == 1)) and "Unpin" or "Pin"), font_size = 8, text_color = 0xffffff }
    \\              } },
    \\              { style = { padding_left = 8, padding_right = 8, padding_top = 5, padding_bottom = 5, border_radius = 999, background_color = 0xdc2626 }, js_on_press = "archiveTicket(" .. ((_i - 1)) .. ")", children = {
    \\                { text = "Archive", font_size = 8, text_color = 0xffffff }
    \\              } }
    \\            } }
    \\          } } or nil
    \\      end)
    \\    } },
    \\    { style = { padding = 12, border_radius = 10, background_color = 0x111827, gap = 4 }, children = {
    \\      { text = "Focused ticket", font_size = 11, text_color = 0x94a3b8 },
    \\      { text = tostring(selectedTitle), font_size = 14, text_color = 0xf8fafc },
    \\      { text = tostring(activity), font_size = 9, text_color = 0x64748b }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then tickets = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

