//! Generated by tsz compiler — d122_breakpoint_variant_nesting [nodes.zig]
//! Source: d122_breakpoint_variant_nesting.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d122_breakpoint_variant_nesting:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

