//! Generated by tsz compiler — d75_throw_try_catch [logic.zig]
//! Source: d75_throw_try_catch.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var errorCount = 0;
    \\function setErrorCount(v) { errorCount = v; if (__luaReady) __luaEval("setErrorCount(" + v + ")"); else __markDirty(); }
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var results = [ { input : "" , status : "" , message : "" } ];
    \\function setResults(v) { results = v; __markDirty(); }
    \\var log = [];
    \\
    \\function safeParse(input) {
    \\  var status = 'ok';
    \\  var message = '';
    \\  try {
    \\    if (input === '') {
    \\      throw 'empty input';
    \\    }
    \\    if (input === 'bad') {
    \\      throw 'invalid format';
    \\    }
    \\    // Simulate successful parse
    \\    message = 'parsed: ' + input;
    \\  } catch (e) {
    \\    status = 'error';
    \\    message = 'caught: ' + e;
    \\    setErrorCount(errorCount + 1);
    \\  }
    \\  log.push({ input: input, status: status, message: message });
    \\  setResults(log);
    \\  setOutput(message);
    \\}
    \\
    \\function safeDivide(a, b) {
    \\  try {
    \\    if (b === 0) {
    \\      throw 'division by zero';
    \\    }
    \\    var result = Math.floor(a / b);
    \\    setOutput(a + ' / ' + b + ' = ' + result);
    \\  } catch (e) {
    \\    setOutput('error: ' + e);
    \\    setErrorCount(errorCount + 1);
    \\  }
    \\}
    \\
    \\function runAll() {
    \\  log = [];
    \\  setErrorCount(0);
    \\  safeParse('hello');
    \\  safeParse('world');
    \\  safeParse('');
    \\  safeParse('bad');
    \\  safeParse('ok');
    \\}
    \\
    \\runAll();
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["errorCount"] = 0
    \\errorCount = _state["errorCount"]
    \\function setErrorCount(v) _state["errorCount"] = v; errorCount = v; __syncToJS("errorCount", v); __markDirty() end
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\
    \\results = {}
    \\function setResults(v) results = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Try / Catch / Throw", font_size = 16, text_color = 0xe2e8f0 },
    \\    { text = "errors: " .. tostring(errorCount), font_size = 10, text_color = 0x64748b },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "runAll ( )", children = {
    \\        { text = "Run All", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "safeParse ( \"test\" )", children = {
    \\        { text = "Parse \"test\"", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0xf59e0b, border_radius = 6 }, js_on_press = "safeParse ( \"\" )", children = {
    \\        { text = "Parse empty", font_size = 11, text_color = 0x000000 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "safeDivide ( 100 , 3 )", children = {
    \\        { text = "100/3", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0xdc2626, border_radius = 6 }, js_on_press = "safeDivide ( 42 , 0 )", children = {
    \\        { text = "42/0", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(results, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", padding = 8, background_color = 0x1e293b, border_radius = 4, align_items = "center" }, children = {
    \\          { text = "\"" .. tostring(_item.input) .. "\"", font_size = 10, text_color = 0x94a3b8 },
    \\          { style = { flex_direction = "row", gap = 6 }, children = {
    \\            (_item . status == "ok") and { text = "OK", font_size = 9, text_color = 0x22c55e } or nil,
    \\            (_item . status == "error") and { text = "ERR", font_size = 9, text_color = 0xef4444 } or nil,
    \\            { text = tostring(_item.message), font_size = 9, text_color = 0x64748b }
    \\          } }
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x6ee7b7 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then results = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

