//! Generated by tsz compiler — d102_graph_path_map_expr_attrs [logic.zig]
//! Source: d102_graph_path_map_expr_attrs.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var shapes = [ { d : "M 0,-48 L 42,0 L 0,48 L -42,0 Z" , fillEffect : "plasma" , stroke : "#ffffff55" , strokeWidth : 2 , zoom : 0.9 } , { d : "M 0,-54 C 18,-54 34,-30 34,0 C 34,30 18,54 0,54 C -18,54 -34,30 -34,0 C -34,-30 -18,-54 0,-54 Z" , fillEffect : "ocean" , stroke : "#ffffff66" , strokeWidth : 3 , zoom : 0.8 } ];
    \\function setShapes(v) { shapes = v; __markDirty(); }
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\shapes = {}
    \\function setShapes(v) shapes = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x0f172a, padding = 20, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "d102 graph path map expr attrs", font_size = 20, text_color = 0xe2e8f0 },
    \\    { text = "Mapped Graph.Path props should resolve member expressions for d, fillEffect, stroke, strokeWidth, and viewZoom.", font_size = 12, text_color = 0x94a3b8 },
    \\    { style = { flex_direction = "row", gap = 12, flex_wrap = "wrap" }, children = {
    \\      __mapLoop(shapes, function(_item, _i)
    \\        return { style = { width = 180, background_color = 0x111827, border_radius = 14, padding = 12 }, children = {
    \\          { style = { width = 150, height = 150 }, graph_container = true, canvas_view_x = 0, canvas_view_y = 0, canvas_view_zoom = _item.zoom, canvas_view_set = true, children = {
    \\            { text_color = _item.stroke, canvas_path = true, canvas_path_d = _item.d, canvas_fill_effect = _item.fillEffect, canvas_stroke_width = _item.strokeWidth }
    \\          } }
    \\        } }
    \\      end)
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then shapes = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

