//! Generated by tsz compiler — d80_logical_assignment [logic.zig]
//! Source: d80_logical_assignment.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var ops = 0;
    \\function setOps(v) { ops = v; if (__luaReady) __luaEval("setOps(" + v + ")"); else __markDirty(); }
    \\var values = [ { name : "" , value : 0 } ];
    \\function setValues(v) { values = v; __markDirty(); }
    \\var data = [];
    \\var data = [
    \\  { name: 'a', value: 0 },
    \\  { name: 'b', value: 5 },
    \\  { name: 'c', value: 0 },
    \\  { name: 'd', value: 10 },
    \\  { name: 'e', value: 0 }
    \\];
    \\setValues(data);
    \\
    \\function orAssignDefaults() {
    \\  for (var i = 0; i < data.length; i++) {
    \\    if (data[i].value === 0) {
    \\      data[i].value = 99;
    \\    }
    \\  }
    \\  setValues(data);
    \\  setOps(ops + 1);
    \\  setOutput('||= applied defaults to zero values');
    \\}
    \\
    \\function nullishAssign() {
    \\  // Simulate ??= by checking for 0 as "null-like"
    \\  for (var i = 0; i < data.length; i++) {
    \\    if (data[i].value === 0) {
    \\      data[i].value = 42;
    \\    }
    \\  }
    \\  setValues(data);
    \\  setOps(ops + 1);
    \\  setOutput('??= assigned 42 to null-like values');
    \\}
    \\
    \\function andAssignDouble() {
    \\  // Simulate &&= by only transforming truthy values
    \\  for (var i = 0; i < data.length; i++) {
    \\    if (data[i].value !== 0) {
    \\      data[i].value = data[i].value * 2;
    \\    }
    \\  }
    \\  setValues(data);
    \\  setOps(ops + 1);
    \\  setOutput('&&= doubled all truthy values');
    \\}
    \\
    \\function resetAll() {
    \\  data = [
    \\    { name: 'a', value: 0 },
    \\    { name: 'b', value: 5 },
    \\    { name: 'c', value: 0 },
    \\    { name: 'd', value: 10 },
    \\    { name: 'e', value: 0 }
    \\  ];
    \\  setValues(data);
    \\  setOps(0);
    \\  setOutput('reset');
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\_state["ops"] = 0
    \\ops = _state["ops"]
    \\function setOps(v) _state["ops"] = v; ops = v; __syncToJS("ops", v); __markDirty() end
    \\
    \\values = {}
    \\function setValues(v) values = v; __markDirty() end
    \\data = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Logical Assignment", font_size = 16, text_color = 0xe2e8f0 },
    \\    { text = "ops: " .. tostring(ops), font_size = 10, text_color = 0x64748b },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "orAssignDefaults ( )", children = {
    \\        { text = "||= defaults", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "nullishAssign ( )", children = {
    \\        { text = "??= assign", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "andAssignDouble ( )", children = {
    \\        { text = "&&= double", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0xdc2626, border_radius = 6 }, js_on_press = "resetAll ( )", children = {
    \\        { text = "Reset", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(values, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 8, background_color = 0x1e293b, border_radius = 4 }, children = {
    \\          { text = tostring(_item.name), font_size = 11, text_color = 0x94a3b8 },
    \\          { text = tostring(_item.value), font_size = 14, text_color = (_item.value == 0) and 0x475569 or 0x6ee7b7 }
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x6ee7b7 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then values = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

