//! Generated by tsz compiler — s01c_counter [handlers.zig]
//! Source: s01c_counter.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:s01c_counter:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:s01c_counter:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobal("decrement");
}

// [origin:s01c_counter:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobal("reset");
}

// [origin:s01c_counter:handler:_handler_press_2]
pub fn _handler_press_2() void {
    qjs_runtime.callGlobal("increment");
}


