//! Generated by tsz compiler — s01c_counter [lua_logic.zig]
//! Source: s01c_counter.tsz


// [origin:s01c_counter:lua_logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

