//! Generated by tsz compiler — d118_classifier_variants_bp [nodes.zig]
//! Source: d118_classifier_variants_bp.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d118_classifier_variants_bp:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

