//! Generated by tsz compiler — l02_lscript_map_handlers [app.zig]
//! Source: l02_lscript_map_handlers.tsz

const std = @import("std");
const build_options = @import("build_options");
const IS_LIB = if (@hasDecl(build_options, "is_lib")) build_options.is_lib else false;

const layout = @import("framework/layout.zig");
const Node = layout.Node;
const Style = layout.Style;
const Color = layout.Color;
const state = @import("framework/state.zig");
const engine = if (IS_LIB) struct {} else @import("framework/engine.zig");
comptime { if (!IS_LIB) _ = @import("framework/core.zig"); }
const qjs_runtime = if (IS_LIB) struct {
    pub fn callGlobal(_: []const u8) void {}
    pub fn callGlobalStr(_: []const u8, _: []const u8) void {}
    pub fn callGlobalInt(_: []const u8, _: i64) void {}
    pub fn registerHostFn(_: []const u8, _: ?*const anyopaque, _: u8) void {}
    pub fn evalExpr(_: []const u8) void {}
} else @import("framework/qjs_runtime.zig");
const nodes = @import("nodes.zig");
const st = @import("state.zig");
const maps = @import("maps.zig");
const handlers = @import("handlers.zig");
const logic = @import("logic.zig");

fn _updateDynamicTexts() void {
    st._dyn_text_0 = std.fmt.bufPrint(&st._dyn_buf_0, "{s}", .{ state.getSlotString(2) }) catch "";
    nodes._arr_3[1].text = st._dyn_text_0;
    st._dyn_text_1 = std.fmt.bufPrint(&st._dyn_buf_1, "{d}", .{ state.getSlot(1) }) catch "";
    nodes._arr_3[2].text = st._dyn_text_1;
}


fn _appInit() void {
    st._initState();
    qjs_runtime.registerHostFn("__setObjArr0", @ptrCast(&st._oa0_unpack), 1);
    _updateDynamicTexts();
    _ = maps._pool_arena.reset(.retain_capacity);
    maps._rebuildMap0();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts();
        _ = maps._pool_arena.reset(.retain_capacity);
        maps._rebuildMap0();
 state.clearDirty(); }
}

export fn app_get_root() *Node { return &nodes._root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return logic.JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return logic.JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return logic.LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return logic.LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "l02_lscript_map_handlers"; }

export fn app_state_count() usize { return 3; }
const _slot_types = [_]u8{ 3, 0, 3 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

pub fn main() !void {
    if (IS_LIB) return;
    try engine.run(.{
        .title = "l02_lscript_map_handlers",
        .root = &nodes._root,
        .js_logic = logic.JS_LOGIC,
        .lua_logic = logic.LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}
