//! Generated by tsz compiler — l02_lscript_map_handlers [handlers.zig]
//! Source: l02_lscript_map_handlers.tsz

const std = @import("std");
const build_options = @import("build_options");
const IS_LIB = if (@hasDecl(build_options, "is_lib")) build_options.is_lib else false;

const qjs_runtime = if (IS_LIB) struct {
    pub fn callGlobal(_: []const u8) void {}
    pub fn callGlobalStr(_: []const u8, _: []const u8) void {}
    pub fn callGlobalInt(_: []const u8, _: i64) void {}
    pub fn registerHostFn(_: []const u8, _: ?*const anyopaque, _: u8) void {}
    pub fn evalExpr(_: []const u8) void {}
} else @import("framework/qjs_runtime.zig");

// [origin:l02_lscript_map_handlers:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:l02_lscript_map_handlers:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobal("resetSelection");
}

