//! Generated by tsz compiler — d102_effect_color_indexing [nodes.zig]
//! Source: d102_effect_color_indexing.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d102_effect_color_indexing:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

