//! Generated by Smith (mod mode) — do not edit
//! Source: m12_string_ops.mod.tsz
//! Module: parser

const std = @import("std");

pub const Token = struct {
    start: usize = 0,
    end: usize = 0,
    kind: []const u8 = "",
};

var buf: [4096]u8 = undefined;
var buf_len: usize = 0;
var tokens: [64]Token = [_]Token{.{}} ** 64;
var token_count: u8 = 0;

pub fn find_char(haystack: []const u8, needle: u8) usize {
    return std.mem.indexOfScalar(u8, haystack, needle) orelse haystack.len;
}

pub fn find_str(haystack: []const u8, needle: []const u8) usize {
    return std.mem.indexOf(u8, haystack, needle) orelse haystack.len;
}

pub fn compare(a: []const u8, b: []const u8) bool {
    return std.mem.eql(u8, a, b);
}

pub fn slice_from(s: []const u8, start: usize) []const u8 {
    return s[start..];
}

pub fn slice_range(s: []const u8, start: usize, end: usize) []const u8 {
    return s[start..end];
}
