//! Generated by Smith (mod mode) — do not edit
//! Source: m16_string_concat.mod.tsz
//! Module: msg

const std = @import("std");

var buf: [512]u8 = undefined;

pub fn greet(name: []const u8) []const u8 {
    return std.fmt.bufPrint(&buf, "Hello, {s}!", .{name}) catch "";
}

pub fn status(code: i32, text: []const u8) []const u8 {
    return std.fmt.bufPrint(&buf, "HTTP {d} {s}", .{ code, text }) catch "";
}
