//! Generated by tsz compiler — d136_render_fn_calls [state.zig]
//! Source: d136_render_fn_calls.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

