//! Generated by tsz compiler — d65_component_8_props [nodes.zig]
//! Source: d65_component_8_props.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d65_component_8_props:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

