//! Generated by tsz compiler — d65_component_8_props [state.zig]
//! Source: d65_component_8_props.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

