//! Generated by tsz compiler — s11b_text_icons [nodes.zig]
//! Source: s11b_text_icons.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:s11b_text_icons:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

