//! Generated by tsz compiler — s11b_text_icons [state.zig]
//! Source: s11b_text_icons.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

