//! Generated by tsz compiler — d89_calculator [nodes.zig]
//! Source: d89_calculator.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d89_calculator:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

