//! Generated by tsz compiler — s09b_physics_sim [logic.zig]
//! Source: s09b_physics_sim.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var paused = 0;
    \\function setPaused(v) { paused = v; if (__luaReady) __luaEval("setPaused(" + v + ")"); else __markDirty(); }
    \\var frame = 0;
    \\function setFrame(v) { frame = v; if (__luaReady) __luaEval("setFrame(" + v + ")"); else __markDirty(); }
    \\var balls = [ { id : 0 , x : 0 , y : 0 , dx : 0 , dy : 0 } ];
    \\function setBalls(v) { balls = v; __markDirty(); }
    \\var ballList = [];
    \\var W = 400;
    \\var H = 280;
    \\
    \\var ballList = [
    \\  { id: 0, x: 100, y: 80, dx: 3, dy: 2, r: 16, color: '#3b82f6' },
    \\  { id: 1, x: 250, y: 150, dx: -2, dy: 3, r: 12, color: '#ef4444' },
    \\  { id: 2, x: 180, y: 200, dx: 4, dy: -1, r: 10, color: '#22c55e' }
    \\];
    \\setBalls(ballList);
    \\
    \\function tick() {
    \\  if (paused === 1) return;
    \\  for (var i = 0; i < ballList.length; i++) {
    \\    var b = ballList[i];
    \\    b.x = b.x + b.dx;
    \\    b.y = b.y + b.dy;
    \\    if (b.x - b.r < 0 || b.x + b.r > W) b.dx = -b.dx;
    \\    if (b.y - b.r < 0 || b.y + b.r > H) b.dy = -b.dy;
    \\  }
    \\  setBalls(ballList);
    \\  setFrame(frame + 1);
    \\}
    \\
    \\function togglePause() {
    \\  setPaused(paused === 1 ? 0 : 1);
    \\}
    \\
    \\function addBall() {
    \\  var colors = ['#3b82f6', '#ef4444', '#22c55e', '#f59e0b', '#8b5cf6'];
    \\  var id = ballList.length;
    \\  ballList.push({ id: id, x: W / 2, y: H / 2, dx: (id % 3) - 1 + 2, dy: (id % 2) + 1, r: 10 + (id * 4) % 14, color: colors[id % colors.length] });
    \\  setBalls(ballList);
    \\}
    \\
    \\function reset() {
    \\  ballList = [
    \\    { id: 0, x: 100, y: 80, dx: 3, dy: 2, r: 16, color: '#3b82f6' },
    \\    { id: 1, x: 250, y: 150, dx: -2, dy: 3, r: 12, color: '#ef4444' },
    \\    { id: 2, x: 180, y: 200, dx: 4, dy: -1, r: 10, color: '#22c55e' }
    \\  ];
    \\  setBalls(ballList);
    \\  setFrame(0);
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["paused"] = 0
    \\paused = _state["paused"]
    \\function setPaused(v) _state["paused"] = v; paused = v; __syncToJS("paused", v); __markDirty() end
    \\_state["frame"] = 0
    \\frame = _state["frame"]
    \\function setFrame(v) _state["frame"] = v; frame = v; __syncToJS("frame", v); __markDirty() end
    \\
    \\balls = {}
    \\function setBalls(v) balls = v; __markDirty() end
    \\ballList = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0c0f1a, width = -1, height = -1, padding = 16, gap = 12, overflow = "hidden" }, children = {
    \\    { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\      { text = "Physics Sim", font_size = 16, text_color = 0xe2e8f0 },
    \\      { text = "frame " .. tostring(frame) .. "  •  " .. tostring(#balls) .. " balls", font_size = 10, text_color = 0x475569 }
    \\    } },
    \\    { style = { background_color = 0x111827, border_radius = 10, height = 280, overflow = "hidden" }, children = {
    \\      __mapLoop(balls, function(_item, _i)
    \\        return { style = { position = "absolute", left = _item.x, top = _item.y, width = (_item.r * 2), height = (_item.r * 2), border_radius = _item.r, background_color = _item.color } }
    \\      end)
    \\    } },
    \\    { style = { flex_direction = "row", gap = 8 }, children = {
    \\      { style = { flex_grow = 1, padding = 10, background_color = 0x1e293b, border_radius = 8, align_items = "center" }, lua_on_press = "tick()", children = {
    \\        { text = "Step", font_size = 12, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { flex_grow = 1, padding = 10, background_color = (paused == 1) and 0x3b82f6 or 0x334155, border_radius = 8, align_items = "center" }, lua_on_press = "togglePause()", children = {
    \\        { text = (paused == 1) and "Play" or "Pause", font_size = 12, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 10, background_color = 0x1e293b, border_radius = 8 }, lua_on_press = "addBall()", children = {
    \\        { text = "+Ball", font_size = 12, text_color = 0x3b82f6 }
    \\      } },
    \\      { style = { padding = 10, background_color = 0x450a0a, border_radius = 8 }, lua_on_press = "reset()", children = {
    \\        { text = "Reset", font_size = 12, text_color = 0xef4444 }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then balls = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

