//! Generated by tsz compiler — 12_min_max_constraints [nodes.zig]
//! Source: 12_min_max_constraints.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:12_min_max_constraints:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

