//! Generated by tsz compiler — d155_sync_direction_working [nodes.zig]
//! Source: d155_sync_direction_working.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d155_sync_direction_working:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

