//! Generated by tsz compiler — d155_sync_direction_working [state.zig]
//! Source: d155_sync_direction_working.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

