//! Generated by tsz compiler — d99_border_color_test [logic.zig]
//! Source: d99_border_color_test.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x000000, padding = 40, gap = 20, overflow = "hidden" }, children = {
    \\    { text = "Border Color Test", font_size = 18, text_color = 0xffffff },
    \\    { style = { flex_direction = "row", gap = 20 }, children = {
    \\      { style = { width = 120, height = 120, border_width = 4, border_color = 0xff0000, border_radius = 8, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\        { text = "RED", text_color = 0xff0000 }
    \\      } },
    \\      { style = { width = 120, height = 120, border_width = 4, border_color = 0x00ff00, border_radius = 8, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\        { text = "GREEN", text_color = 0x00ff00 }
    \\      } },
    \\      { style = { width = 120, height = 120, border_width = 4, border_color = 0x0000ff, border_radius = 8, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\        { text = "BLUE", text_color = 0x0000ff }
    \\      } },
    \\      { style = { width = 120, height = 120, border_width = 4, border_color = 0xffff00, background_color = 0x333333, border_radius = 8, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\        { text = "YELLOW", text_color = 0xffff00 }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 20 }, children = {
    \\      { style = { width = 200, height = 80, border_width = 6, border_color = 0xff00ff, background_color = 0x1a1a1a, border_radius = 12, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\        { text = "MAGENTA 6px", text_color = 0xff00ff }
    \\      } },
    \\      { style = { width = 200, height = 80, border_width = 2, border_color = 0x00ffff, background_color = 0x1a1a1a, border_radius = 4, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\        { text = "CYAN 2px", text_color = 0x00ffff }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

