//! Generated by tsz compiler — candlestick_chart [logic.zig]
//! Source: candlestick_chart.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC = "";

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { gap = 12, padding = 24, background_color = 0x0d1117, height = -1, width = -1, flex_direction = "column", overflow = "hidden" }, children = {
    \\    { text = "Candlestick Chart", font_size = 20, text_color = 0xe6edf3 },
    \\    { text = "OHLC candles — flex column wicks + colored bodies, bottom-aligned", font_size = 12, text_color = 0x8b949e },
    \\    { style = { gap = 8, padding = 16, border_color = 0x30363d, border_width = 1, border_radius = 8, background_color = 0x161b22, flex_direction = "column", flex_grow = 1, overflow = "auto" }, children = {
    \\      { style = { flex_direction = "row", gap = 12, flex_grow = 1, overflow = "auto" }, children = {
    \\        { style = { flex_direction = "column", justify_content = "space_between", padding_top = 4, padding_bottom = 4 }, children = {
    \\          { text = "$125", font_size = 9, text_color = 0x8b949e },
    \\          { text = "$110", font_size = 9, text_color = 0x8b949e },
    \\          { text = "$95", font_size = 9, text_color = 0x8b949e }
    \\        } },
    \\        { style = { flex_direction = "row", gap = 8, flex_grow = 1, align_items = "stretch", overflow = "auto" }, children = {
    \\          { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\            { style = { height = 67 } },
    \\            { style = { width = 2, height = 33, background_color = 0x8b949e } },
    \\            { style = { width = 28, height = 67, background_color = 0x22c55e, border_radius = 2 } },
    \\            { style = { width = 2, height = 33, background_color = 0x8b949e } }
    \\          } },
    \\          { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\            { style = { height = 33 } },
    \\            { style = { width = 2, height = 67, background_color = 0x8b949e } },
    \\            { style = { width = 28, height = 13, background_color = 0xef4444, border_radius = 2 } },
    \\            { style = { width = 2, height = 20, background_color = 0x8b949e } },
    \\            { style = { height = 67 } }
    \\          } },
    \\          { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\            { style = { height = 47 } },
    \\            { style = { width = 2, height = 20, background_color = 0x8b949e } },
    \\            { style = { width = 28, height = 47, background_color = 0x22c55e, border_radius = 2 } },
    \\            { style = { width = 2, height = 53, background_color = 0x8b949e } },
    \\            { style = { height = 33 } }
    \\          } },
    \\          { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\            { style = { width = 2, height = 33, background_color = 0x8b949e } },
    \\            { style = { width = 28, height = 33, background_color = 0x22c55e, border_radius = 2 } },
    \\            { style = { width = 2, height = 33, background_color = 0x8b949e } },
    \\            { style = { height = 100 } }
    \\          } },
    \\          { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\            { style = { height = 20 } },
    \\            { style = { width = 2, height = 13, background_color = 0x8b949e } },
    \\            { style = { width = 28, height = 33, background_color = 0xef4444, border_radius = 2 } },
    \\            { style = { width = 2, height = 33, background_color = 0x8b949e } },
    \\            { style = { height = 100 } }
    \\          } }
    \\        } }
    \\      } },
    \\      { style = { height = 1, background_color = 0x30363d } },
    \\      { style = { flex_direction = "row", padding_left = 36 }, children = {
    \\        { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\          { text = "Mon", font_size = 9, text_color = 0x8b949e }
    \\        } },
    \\        { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\          { text = "Tue", font_size = 9, text_color = 0x8b949e }
    \\        } },
    \\        { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\          { text = "Wed", font_size = 9, text_color = 0x8b949e }
    \\        } },
    \\        { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\          { text = "Thu", font_size = 9, text_color = 0x8b949e }
    \\        } },
    \\        { style = { flex_grow = 1, align_items = "center", overflow = "auto" }, children = {
    \\          { text = "Fri", font_size = 9, text_color = 0x8b949e }
    \\        } }
    \\      } },
    \\      { style = { flex_wrap = "wrap", gap = 16, flex_direction = "row" }, children = {
    \\        { style = { gap = 6, align_items = "center", flex_direction = "row" }, children = {
    \\          { style = { border_radius = 4, height = 8, width = 8, background_color = 0x22c55e } },
    \\          { text = "Bull (close >= open)", font_size = 11, text_color = 0x8b949e }
    \\        } },
    \\        { style = { gap = 6, align_items = "center", flex_direction = "row" }, children = {
    \\          { style = { border_radius = 4, height = 8, width = 8, background_color = 0xef4444 } },
    \\          { text = "Bear (close &lt; open)", font_size = 11, text_color = 0x8b949e }
    \\        } }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

