//! Generated by tsz compiler — d82_string_methods_chain [logic.zig]
//! Source: d82_string_methods_chain.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var count = 0;
    \\function setCount(v) { count = v; if (__luaReady) __luaEval("setCount(" + v + ")"); else __markDirty(); }
    \\var items = [ { original : "" , processed : "" } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var log = [];
    \\
    \\function processString(input) {
    \\  var trimmed = input.trim !== undefined ? input.trim() : input;
    \\  var lower = trimmed.toLowerCase !== undefined ? trimmed.toLowerCase() : trimmed;
    \\  var upper = trimmed.toUpperCase !== undefined ? trimmed.toUpperCase() : trimmed;
    \\  var first3 = trimmed.slice(0, 3);
    \\  var hasAt = trimmed.indexOf('@') >= 0 ? 'yes' : 'no';
    \\
    \\  log.push({ original: input, processed: lower + ' | first3:' + first3 + ' | @:' + hasAt });
    \\  setItems(log);
    \\  setCount(log.length);
    \\  setOutput('processed: ' + input + ' → ' + lower);
    \\}
    \\
    \\function searchIn(haystack, needle) {
    \\  var idx = haystack.indexOf(needle);
    \\  if (idx >= 0) {
    \\    setOutput('found "' + needle + '" at index ' + idx);
    \\  } else {
    \\    setOutput('"' + needle + '" not found in "' + haystack + '"');
    \\  }
    \\  setCount(count + 1);
    \\}
    \\
    \\function runBatch() {
    \\  log = [];
    \\  processString('  Hello World  ');
    \\  processString('alice@example.com');
    \\  processString('  SHOUTING  ');
    \\  processString('no-spaces');
    \\  processString('  MiXeD CaSe  ');
    \\}
    \\
    \\runBatch();
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\_state["count"] = 0
    \\count = _state["count"]
    \\function setCount(v) _state["count"] = v; count = v; __syncToJS("count", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "String Methods", font_size = 16, text_color = 0xe2e8f0 },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "runBatch ( )", children = {
    \\        { text = "Run Batch", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "processString ( \"  TEST INPUT  \" )", children = {
    \\        { text = "Process Test", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x1e40af, border_radius = 6 }, js_on_press = "searchIn ( \"hello world\" , \"world\" )", children = {
    \\        { text = "Search", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(items, function(_item, _i)
    \\        return { style = { padding = 8, background_color = 0x1e293b, border_radius = 4, gap = 2 }, children = {
    \\          { text = "in: \"" .. tostring(_item.original) .. "\"", font_size = 10, text_color = 0x94a3b8 },
    \\          { text = tostring(_item.processed), font_size = 10, text_color = 0x6ee7b7 }
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(count) .. " ops · " .. tostring(output), font_size = 10, text_color = 0x64748b }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

