//! Generated by tsz compiler — 01_flex_direction_row [nodes.zig]
//! Source: 01_flex_direction_row.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:01_flex_direction_row:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

