//! Generated by tsz compiler — d96_graph_map_expr_attrs [state.zig]
//! Source: d96_graph_map_expr_attrs.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

