//! Generated by tsz compiler — test_html_tags [logic.zig]
//! Source: test_html_tags.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, flex_direction = "column", padding = 20, overflow = "hidden" }, children = {
    \\    { text = "HTML Tag Test", font_size = 24 },
    \\    { style = { flex_direction = "row", gap = 10 }, children = {
    \\      { style = { width = 100, height = 100, background_color = 0xff6b6b, overflow = "auto" }, children = {
    \\        { text = "Red Box" }
    \\      } },
    \\      { style = { width = 100, height = 100, background_color = 0x4ecdc4, overflow = "auto" }, children = {
    \\        { text = "Teal Box" }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 8, margin_top = 10 }, children = {
    \\      { style = { padding = 8, background_color = 0x333333 }, children = {
    \\        { text = "Click Me", text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { margin_top = 20 }, children = {
    \\      { text = "Footer text" }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

