//! Generated by tsz compiler — depth_chart [state.zig]
//! Source: depth_chart.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

