//! Generated by tsz compiler — d10_handler_triple_capture [logic.zig]
//! Source: d10_handler_triple_capture.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var multiplier = 1;
    \\function setMultiplier(v) { multiplier = v; if (__luaReady) __luaEval("setMultiplier(" + v + ")"); else __markDirty(); }
    \\var accumulator = 0;
    \\function setAccumulator(v) { accumulator = v; if (__luaReady) __luaEval("setAccumulator(" + v + ")"); else __markDirty(); }
    \\var lastIdx = 0;
    \\function setLastIdx(v) { lastIdx = v; if (__luaReady) __luaEval("setLastIdx(" + v + ")"); else __markDirty(); }
    \\var lastWeight = 0;
    \\function setLastWeight(v) { lastWeight = v; if (__luaReady) __luaEval("setLastWeight(" + v + ")"); else __markDirty(); }
    \\var clickLog = 0;
    \\function setClickLog(v) { clickLog = v; if (__luaReady) __luaEval("setClickLog(" + v + ")"); else __markDirty(); }
    \\var entries = [ { label : "" , weight : 0 , category : 0 } ];
    \\function setEntries(v) { entries = v; __markDirty(); }
    \\
    \\// Populate entries for triple capture test
    \\
    \\var entries = [];
    \\var labels = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter',
    \\              'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Ceres',
    \\              'Eris', 'Haumea', 'Makemake', 'Sedna', 'Quaoar'];
    \\
    \\for (var i = 0; i < 15; i++) {
    \\  entries.push({
    \\    label: labels[i],
    \\    weight: (i + 1) * 3,
    \\    category: i % 3
    \\  });
    \\}
    \\setEntries(entries);
    \\
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["multiplier"] = 1
    \\multiplier = _state["multiplier"]
    \\function setMultiplier(v) _state["multiplier"] = v; multiplier = v; __syncToJS("multiplier", v); __markDirty() end
    \\_state["accumulator"] = 0
    \\accumulator = _state["accumulator"]
    \\function setAccumulator(v) _state["accumulator"] = v; accumulator = v; __syncToJS("accumulator", v); __markDirty() end
    \\_state["lastIdx"] = 0
    \\lastIdx = _state["lastIdx"]
    \\function setLastIdx(v) _state["lastIdx"] = v; lastIdx = v; __syncToJS("lastIdx", v); __markDirty() end
    \\_state["lastWeight"] = 0
    \\lastWeight = _state["lastWeight"]
    \\function setLastWeight(v) _state["lastWeight"] = v; lastWeight = v; __syncToJS("lastWeight", v); __markDirty() end
    \\_state["clickLog"] = 0
    \\clickLog = _state["clickLog"]
    \\function setClickLog(v) _state["clickLog"] = v; clickLog = v; __syncToJS("clickLog", v); __markDirty() end
    \\
    \\entries = {}
    \\function setEntries(v) entries = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0c0a09, padding = 16, width = -1, height = -1, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "Triple Capture", font_size = 16, text_color = 0xfafaf9 },
    \\    { style = { flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\      { style = { background_color = 0x78350f, border_radius = 6, padding = 8 }, lua_on_press = "setMultiplier(multiplier + 1)", children = {
    \\        { text = "multiplier: " .. tostring(multiplier), font_size = 12, text_color = 0xfef3c7 }
    \\      } },
    \\      { text = "acc: " .. tostring(accumulator) .. " | lastIdx: " .. tostring(lastIdx) .. " | lastW: " .. tostring(lastWeight) .. " | clicks: " .. tostring(clickLog), font_size = 11, text_color = 0x78716c }
    \\    } },
    \\    { style = { overflow = "scroll", flex_grow = 1 }, children = {
    \\      __mapLoop(entries, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 10, margin_bottom = 4, border_radius = 6, background_color = 0x1c1917 }, lua_on_press = "setAccumulator(" .. (accumulator + _item.weight * multiplier + (_i - 1)) .. "); setLastIdx(" .. ((_i - 1)) .. "); setLastWeight('" .. (_item.weight) .. "'); setClickLog(clickLog + 1)", children = {
    \\          { style = { flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\            { text = tostring((_i - 1)) .. ".", font_size = 11, text_color = 0xa8a29e },
    \\            { text = tostring(_item.label), font_size = 13, text_color = 0xfafaf9 }
    \\          } },
    \\          { style = { flex_direction = "row", gap = 12, align_items = "center" }, children = {
    \\            (_item . category == 0) and { text = "A", font_size = 9, text_color = 0x22c55e } or nil,
    \\            (_item . category == 1) and { text = "B", font_size = 9, text_color = 0x3b82f6 } or nil,
    \\            (_item . category == 2) and { text = "C", font_size = 9, text_color = 0xef4444 } or nil,
    \\            { text = "w:" .. tostring(_item.weight), font_size = 11, text_color = 0x78716c },
    \\            { text = "= " .. tostring(_item.weight * multiplier + (_i - 1)), font_size = 10, text_color = 0x57534e }
    \\          } }
    \\        } }
    \\      end)
    \\    }, scroll_y = ((_scrollY and _scrollY[1]) or 0), scroll_persist_slot = 1 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then entries = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

