//! Generated by tsz compiler — d10_handler_triple_capture [state.zig]
//! Source: d10_handler_triple_capture.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

