//! Generated by tsz compiler — SpotifyClone [state.zig]
//! Source: SpotifyClone.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

