//! Generated by tsz compiler — d63_empty_states [nodes.zig]
//! Source: d63_empty_states.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d63_empty_states:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

