//! Generated by tsz compiler — d57_children_prop [logic.zig]
//! Source: d57_children_prop.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var theme = 0;
    \\function setTheme(v) { theme = v; if (__luaReady) __luaEval("setTheme(" + v + ")"); else __markDirty(); }
    \\var taps = 0;
    \\function setTaps(v) { taps = v; if (__luaReady) __luaEval("setTaps(" + v + ")"); else __markDirty(); }
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["theme"] = 0
    \\theme = _state["theme"]
    \\function setTheme(v) _state["theme"] = v; theme = v; __markDirty() end
    \\_state["taps"] = 0
    \\taps = _state["taps"]
    \\function setTaps(v) _state["taps"] = v; taps = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Children Prop", font_size = 16, text_color = 0xe2e8f0 },
    \\    { style = { background_color = 0x1e293b, border_radius = 8, padding = 12, border_width = 1, border_color = 0x334155, gap = 8 }, children = {
    \\      { text = "Simple card with text children", font_size = 12, text_color = 0xe2e8f0 },
    \\      { text = "Just two Text nodes inside a Card wrapper", font_size = 10, text_color = 0x64748b }
    \\    } },
    \\    { style = { background_color = 0x1e293b, border_radius = 8, padding = 12, border_width = 1, border_color = 0x334155, gap = 8 }, children = {
    \\      { style = { gap = 8 }, children = {
    \\        { text = "Status", font_size = 13, text_color = 0x94a3b8 },
    \\        { style = { gap = 4, padding_left = 8 }, children = {
    \\          { style = { flex_direction = "row", gap = 6 }, children = {
    \\            { style = { background_color = 0x22c55e, border_radius = 10, padding_left = 8, padding_right = 8, padding_top = 2, padding_bottom = 2 }, children = {
    \\              { text = "Online", font_size = 9, text_color = 0xffffff }
    \\            } },
    \\            { style = { background_color = 0x3b82f6, border_radius = 10, padding_left = 8, padding_right = 8, padding_top = 2, padding_bottom = 2 }, children = {
    \\              { text = "v2.4", font_size = 9, text_color = 0xffffff }
    \\            } },
    \\            { style = { background_color = 0x7c3aed, border_radius = 10, padding_left = 8, padding_right = 8, padding_top = 2, padding_bottom = 2 }, children = {
    \\              { text = "Prod", font_size = 9, text_color = 0xffffff }
    \\            } }
    \\          } }
    \\        } }
    \\      } },
    \\      { style = { gap = 8 }, children = {
    \\        { text = "Actions", font_size = 13, text_color = 0x94a3b8 },
    \\        { style = { gap = 4, padding_left = 8 }, children = {
    \\          { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, lua_on_press = "setTaps(taps + 1)", children = {
    \\            { text = "Tap me (" .. tostring(taps) .. ")", font_size = 11, text_color = 0xe2e8f0 }
    \\          } }
    \\        } }
    \\      } }
    \\    } },
    \\    { style = { background_color = 0x1e293b, border_radius = 8, padding = 12, border_width = 1, border_color = 0x334155, gap = 8 }, children = {
    \\      { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\        { text = "Nested wrappers", font_size = 12, text_color = 0xe2e8f0 },
    \\        { style = { background_color = 0xf59e0b, border_radius = 10, padding_left = 8, padding_right = 8, padding_top = 2, padding_bottom = 2 }, children = {
    \\          { text = tostring(taps), font_size = 9, text_color = 0xffffff }
    \\        } }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

