//! Generated by tsz compiler — 07_flex_wrap [nodes.zig]
//! Source: 07_flex_wrap.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:07_flex_wrap:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

