//! Generated by tsz compiler — d62_negative_numbers [state.zig]
//! Source: d62_negative_numbers.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

