//! Generated by tsz compiler — 16_content_sizing [logic.zig]
//! Source: 16_content_sizing.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, flex_direction = "column", padding = 10, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "WPT: content-based sizing", font_size = 18 },
    \\    { text = "VERIFY: Items without explicit width size to content, empty containers visible with padding", font_size = 10, text_color = 0x888888 },
    \\    { text = "No explicit width — items size to content", font_size = 11 },
    \\    { style = { flex_direction = "row", background_color = 0x333333, gap = 4, padding = 4 }, children = {
    \\      { style = { background_color = 0x4caf50, padding = 8 }, children = {
    \\        { text = "Short", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { background_color = 0x2196f3, padding = 8 }, children = {
    \\        { text = "Medium length", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { background_color = 0xff9800, padding = 8 }, children = {
    \\        { text = "Longer text content", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "No explicit height — row items shrink-wrap vertically", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 300, background_color = 0x333333, gap = 4, padding = 4 }, children = {
    \\      { style = { width = 60, background_color = 0x4caf50, padding = 4 }, children = {
    \\        { text = "A", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 60, background_color = 0x2196f3, padding = 4 }, children = {
    \\        { text = "B", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "Empty containers — should still be visible with padding", font_size = 11 },
    \\    { style = { flex_direction = "row", background_color = 0x333333, gap = 4, padding = 4 }, children = {
    \\      { style = { background_color = 0x4caf50, padding = 20 } },
    \\      { style = { background_color = 0x2196f3, padding = 10 } },
    \\      { style = { background_color = 0xff9800, padding = 30 } }
    \\    } },
    \\    { text = "Mixed content + fixed — grow fills remaining", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 400, background_color = 0x333333, gap = 4, padding = 4 }, children = {
    \\      { style = { background_color = 0x4caf50, padding = 8 }, children = {
    \\        { text = "Content", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_grow = 1, background_color = 0x2196f3, padding = 8, overflow = "auto" }, children = {
    \\        { text = "Grows", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 80, background_color = 0xff9800, padding = 8 }, children = {
    \\        { text = "80px", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

