//! Generated by tsz compiler — d69_chat_ui [nodes.zig]
//! Source: d69_chat_ui.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d69_chat_ui:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

