//! Generated by tsz compiler — d69_chat_ui [state.zig]
//! Source: d69_chat_ui.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

