//! Generated by tsz compiler — d90_spreadsheet [logic.zig]
//! Source: d90_spreadsheet.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var selectedRow = 0;
    \\function setSelectedRow(v) { selectedRow = v; if (__luaReady) __luaEval("setSelectedRow(" + v + ")"); else __markDirty(); }
    \\var selectedCol = 0;
    \\function setSelectedCol(v) { selectedCol = v; if (__luaReady) __luaEval("setSelectedCol(" + v + ")"); else __markDirty(); }
    \\var formula = "";
    \\function setFormula(v) { formula = v; if (__luaReady) __luaEval("setFormula(\'" + v + "\')"); else __markDirty(); }
    \\var grandTotal = 0;
    \\function setGrandTotal(v) { grandTotal = v; if (__luaReady) __luaEval("setGrandTotal(" + v + ")"); else __markDirty(); }
    \\var editCount = 0;
    \\function setEditCount(v) { editCount = v; if (__luaReady) __luaEval("setEditCount(" + v + ")"); else __markDirty(); }
    \\var grid = [ { cells : [ 0 , 0 , 0 , 0 ] , label : "" } ];
    \\function setGrid(v) { grid = v; __markDirty(); }
    \\var colTotals = [ 0 , 0 , 0 , 0 ];
    \\function setColTotals(v) { colTotals = v; __markDirty(); }
    \\var data = [];
    \\var data = [
    \\  { cells: [1200, 800, 350, 200], label: 'Q1' },
    \\  { cells: [1400, 750, 400, 180], label: 'Q2' },
    \\  { cells: [1100, 900, 280, 220], label: 'Q3' },
    \\  { cells: [1600, 850, 420, 190], label: 'Q4' },
    \\  { cells: [-200, -150, -80, -50], label: 'Adj' }
    \\];
    \\setGrid(data);
    \\recalcTotals();
    \\
    \\function recalcTotals() {
    \\  var totals = [0, 0, 0, 0];
    \\  var grand = 0;
    \\  for (var r = 0; r < data.length; r++) {
    \\    for (var c = 0; c < 4; c++) {
    \\      totals[c] += data[r].cells[c];
    \\      grand += data[r].cells[c];
    \\    }
    \\  }
    \\  setColTotals(totals);
    \\  setGrandTotal(grand);
    \\}
    \\
    \\function selectCell(row, col) {
    \\  setSelectedRow(row);
    \\  setSelectedCol(col);
    \\  var val = data[row].cells[col];
    \\  setFormula(data[row].label + ':' + colName(col) + ' = ' + val);
    \\}
    \\
    \\function adjustCell(amount) {
    \\  var r = selectedRow;
    \\  var c = selectedCol;
    \\  data[r].cells[c] = data[r].cells[c] + amount;
    \\  setGrid(data);
    \\  setEditCount(editCount + 1);
    \\  recalcTotals();
    \\  setFormula(data[r].label + ':' + colName(c) + ' = ' + data[r].cells[c]);
    \\}
    \\
    \\function colName(c) {
    \\  if (c === 0) return 'Revenue';
    \\  if (c === 1) return 'Costs';
    \\  if (c === 2) return 'Marketing';
    \\  return 'Other';
    \\}
    \\
    \\function rowTotal(r) {
    \\  var sum = 0;
    \\  for (var c = 0; c < 4; c++) {
    \\    sum += data[r].cells[c];
    \\  }
    \\  return sum;
    \\}
    \\
    \\function zeroRow(r) {
    \\  for (var c = 0; c < 4; c++) {
    \\    data[r].cells[c] = 0;
    \\  }
    \\  setGrid(data);
    \\  setEditCount(editCount + 1);
    \\  recalcTotals();
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["selectedRow"] = 0
    \\selectedRow = _state["selectedRow"]
    \\function setSelectedRow(v) _state["selectedRow"] = v; selectedRow = v; __syncToJS("selectedRow", v); __markDirty() end
    \\_state["selectedCol"] = 0
    \\selectedCol = _state["selectedCol"]
    \\function setSelectedCol(v) _state["selectedCol"] = v; selectedCol = v; __syncToJS("selectedCol", v); __markDirty() end
    \\_state["formula"] = ""
    \\formula = _state["formula"]
    \\function setFormula(v) _state["formula"] = v; formula = v; __syncToJS("formula", v); __markDirty() end
    \\_state["grandTotal"] = 0
    \\grandTotal = _state["grandTotal"]
    \\function setGrandTotal(v) _state["grandTotal"] = v; grandTotal = v; __syncToJS("grandTotal", v); __markDirty() end
    \\_state["editCount"] = 0
    \\editCount = _state["editCount"]
    \\function setEditCount(v) _state["editCount"] = v; editCount = v; __syncToJS("editCount", v); __markDirty() end
    \\
    \\grid = {}
    \\function setGrid(v) grid = v; __markDirty() end
    \\colTotals = {}
    \\function setColTotals(v) colTotals = v; __markDirty() end
    \\data = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 16, width = -1, height = -1, gap = 8, overflow = "hidden" }, children = {
    \\    { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\      { text = "Spreadsheet", font_size = 16, text_color = 0xe2e8f0 },
    \\      { text = "edits: " .. tostring(editCount) .. " · total: " .. tostring(grandTotal), font_size = 9, text_color = 0x64748b }
    \\    } },
    \\    { style = { background_color = 0x1e293b, border_radius = 4, padding = 8, flex_direction = "row", justify_content = "space_between" }, children = {
    \\      { text = tostring(formula), font_size = 10, text_color = 0x94a3b8 },
    \\      { style = { flex_direction = "row", gap = 4 }, children = {
    \\        { style = { padding = 4, background_color = 0x334155, border_radius = 4 }, js_on_press = "adjustCell ( 100 )", children = {
    \\          { text = "+100", font_size = 9, text_color = 0x22c55e }
    \\        } },
    \\        { style = { padding = 4, background_color = 0x334155, border_radius = 4 }, js_on_press = "adjustCell ( - 100 )", children = {
    \\          { text = "-100", font_size = 9, text_color = 0xef4444 }
    \\        } },
    \\        { style = { padding = 4, background_color = 0x334155, border_radius = 4 }, js_on_press = "adjustCell ( 10 )", children = {
    \\          { text = "+10", font_size = 9, text_color = 0x22c55e }
    \\        } },
    \\        { style = { padding = 4, background_color = 0x334155, border_radius = 4 }, js_on_press = "adjustCell ( - 10 )", children = {
    \\          { text = "-10", font_size = 9, text_color = 0xef4444 }
    \\        } }
    \\      } }
    \\    } },
    \\    { children = {
    \\      { style = { flex_direction = "row" }, children = {
    \\        { style = { width = 40, padding = 6 } },
    \\        { style = { width = 70, padding = 6, align_items = "center", background_color = 0x334155, border_width = 1, border_color = 0x475569 }, children = {
    \\          { text = "Revenue", font_size = 9, text_color = 0x94a3b8 }
    \\        } },
    \\        { style = { width = 70, padding = 6, align_items = "center", background_color = 0x334155, border_width = 1, border_color = 0x475569 }, children = {
    \\          { text = "Costs", font_size = 9, text_color = 0x94a3b8 }
    \\        } },
    \\        { style = { width = 70, padding = 6, align_items = "center", background_color = 0x334155, border_width = 1, border_color = 0x475569 }, children = {
    \\          { text = "Mktg", font_size = 9, text_color = 0x94a3b8 }
    \\        } },
    \\        { style = { width = 70, padding = 6, align_items = "center", background_color = 0x334155, border_width = 1, border_color = 0x475569 }, children = {
    \\          { text = "Other", font_size = 9, text_color = 0x94a3b8 }
    \\        } },
    \\        { style = { width = 60, padding = 6, align_items = "center", background_color = 0x334155, border_width = 1, border_color = 0x475569 }, children = {
    \\          { text = "Row Σ", font_size = 9, text_color = 0xf59e0b }
    \\        } }
    \\      } },
    \\      __mapLoop(grid, function(_item, _i)
    \\        return { style = { flex_direction = "row" }, children = {
    \\          { style = { width = 40, padding = 6, align_items = "center", background_color = 0x334155, border_width = 1, border_color = 0x475569 }, js_on_press = "zeroRow(" .. ((_i - 1)) .. ")", children = {
    \\            { text = tostring(_item.label), font_size = 9, text_color = 0x94a3b8 }
    \\          } },
    \\          { style = { width = 70, padding = 6, align_items = "end", background_color = ((((selectedRow == (_i - 1) and selectedCol==0)) and 1 or 0) == 1) and 0x1e40af or 0x1e293b, border_width = 1, border_color = 0x334155 }, js_on_press = "selectCell ( _i , 0 )", children = {
    \\            { text = tostring(_item.cells), font_size = 10, text_color = (_item.cells < 0) and 0xef4444 or 0xe2e8f0 }
    \\          } },
    \\          { style = { width = 70, padding = 6, align_items = "end", background_color = ((((selectedRow == (_i - 1) and selectedCol==1)) and 1 or 0) == 1) and 0x1e40af or 0x1e293b, border_width = 1, border_color = 0x334155 }, js_on_press = "selectCell ( _i , 1 )", children = {
    \\            { text = tostring(_item.cells), font_size = 10, text_color = (_item.cells < 0) and 0xef4444 or 0xe2e8f0 }
    \\          } },
    \\          { style = { width = 70, padding = 6, align_items = "end", background_color = ((((selectedRow == (_i - 1) and selectedCol==2)) and 1 or 0) == 1) and 0x1e40af or 0x1e293b, border_width = 1, border_color = 0x334155 }, js_on_press = "selectCell ( _i , 2 )", children = {
    \\            { text = tostring(_item.cells), font_size = 10, text_color = (_item.cells < 0) and 0xef4444 or 0xe2e8f0 }
    \\          } },
    \\          { style = { width = 70, padding = 6, align_items = "end", background_color = ((((selectedRow == (_i - 1) and selectedCol==3)) and 1 or 0) == 1) and 0x1e40af or 0x1e293b, border_width = 1, border_color = 0x334155 }, js_on_press = "selectCell ( _i , 3 )", children = {
    \\            { text = tostring(_item.cells), font_size = 10, text_color = (_item.cells < 0) and 0xef4444 or 0xe2e8f0 }
    \\          } },
    \\          { style = { width = 60, padding = 6, align_items = "end", background_color = 0x0f172a, border_width = 1, border_color = 0x334155 }, children = {
    \\            { text = tostring(_item.cells[0] + _item.cells[1] + _item.cells[2] + _item.cells[3]), font_size = 9, text_color = 0xf59e0b }
    \\          } }
    \\        } }
    \\      end),
    \\      { style = { flex_direction = "row" }, children = {
    \\        { style = { width = 40, padding = 6, align_items = "center", background_color = 0x334155 }, children = {
    \\          { text = "Σ", font_size = 9, text_color = 0xf59e0b }
    \\        } },
    \\        { style = { width = 70, padding = 6, align_items = "end", background_color = 0x0f172a, border_width = 1, border_color = 0x334155 }, children = {
    \\          { text = tostring(colTotals[0]), font_size = 9, text_color = 0xf59e0b }
    \\        } },
    \\        { style = { width = 70, padding = 6, align_items = "end", background_color = 0x0f172a, border_width = 1, border_color = 0x334155 }, children = {
    \\          { text = tostring(colTotals[1]), font_size = 9, text_color = 0xf59e0b }
    \\        } },
    \\        { style = { width = 70, padding = 6, align_items = "end", background_color = 0x0f172a, border_width = 1, border_color = 0x334155 }, children = {
    \\          { text = tostring(colTotals[2]), font_size = 9, text_color = 0xf59e0b }
    \\        } },
    \\        { style = { width = 70, padding = 6, align_items = "end", background_color = 0x0f172a, border_width = 1, border_color = 0x334155 }, children = {
    \\          { text = tostring(colTotals[3]), font_size = 9, text_color = 0xf59e0b }
    \\        } },
    \\        { style = { width = 60, padding = 6, align_items = "end", background_color = 0x334155, border_width = 1, border_color = 0x475569 }, children = {
    \\          { text = tostring(grandTotal), font_size = 9, text_color = 0xffffff }
    \\        } }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then grid = __luaMapData0 end
    \\  if __luaMapData1 then colTotals = __luaMapData1 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

