//! Generated by tsz compiler — s04b_dashboard [state.zig]
//! Source: s04b_dashboard.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

