//! Generated by tsz compiler — twitter-clone [logic.zig]
//! Source: twitter-clone.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var tweets = [];
    \\function setTweets(v) { tweets = v; }
    \\
    \\// Twitter/X clone — 20 hardcoded tweets with engagement counts.
    \\
    \\function loadData() {
    \\  var tweets = [
    \\    { user: 'Elon Musk', handle: 'elonmusk', avatar: 'EM', avatarBg: 0x1da1f2, time: '2h', text: 'Just mass-produced the 10 millionth Cybertruck. Still no turn signals though.', replies: 4200, retweets: 18700, likes: 95400, hasImage: 0, imageBg: 0 },
    \\    { user: 'Sarah Chen', handle: 'sarahcodes', avatar: 'SC', avatarBg: 0x7856ff, time: '3h', text: 'Hot take: most "10x engineers" are just people who say no to meetings', replies: 342, retweets: 2100, likes: 14800, hasImage: 0, imageBg: 0 },
    \\    { user: 'The Verge', handle: 'verge', avatar: 'TV', avatarBg: 0xfa4b2a, time: '4h', text: 'Apple just announced the Vision Pro 2. It is lighter, cheaper, and still nobody knows what to do with it.', replies: 1800, retweets: 5600, likes: 23100, hasImage: 1, imageBg: 0x2d2d2d },
    \\    { user: 'Dan Abramov', handle: 'dan_abramov', avatar: 'DA', avatarBg: 0x61dafb, time: '5h', text: 'People keep asking me about React 22. I keep telling them to read the docs. They keep not reading the docs.', replies: 890, retweets: 3400, likes: 28900, hasImage: 0, imageBg: 0 },
    \\    { user: 'NASA', handle: 'NASA', avatar: 'NA', avatarBg: 0x0b3d91, time: '6h', text: 'New images from James Webb show a galaxy cluster 13.2 billion light-years away. You are looking at the universe as a toddler.', replies: 2400, retweets: 41000, likes: 187000, hasImage: 1, imageBg: 0x0a0a2a },
    \\    { user: 'Lex Fridman', handle: 'lexfridman', avatar: 'LF', avatarBg: 0x333333, time: '7h', text: 'Love is the answer. But also distributed systems. And jiu-jitsu.', replies: 560, retweets: 1200, likes: 9800, hasImage: 0, imageBg: 0 },
    \\    { user: 'Taylor Swift', handle: 'taylorswift13', avatar: 'TS', avatarBg: 0xc71585, time: '8h', text: 'Surprise! New album drops at midnight. It is called "Segmentation Fault" and every song is about debugging.', replies: 45000, retweets: 120000, likes: 890000, hasImage: 1, imageBg: 0x1a0a1a },
    \\    { user: 'Kelsey Hightower', handle: 'kelseyhightower', avatar: 'KH', avatarBg: 0x326ce5, time: '9h', text: 'YAML is not a programming language. Stop writing 4000-line YAML files and calling it infrastructure as code.', replies: 1200, retweets: 8900, likes: 34500, hasImage: 0, imageBg: 0 },
    \\    { user: 'MIT Tech Review', handle: 'techreview', avatar: 'MT', avatarBg: 0xe60000, time: '10h', text: 'Breaking: researchers achieve quantum error correction below the threshold needed for useful computation. This is a big deal.', replies: 670, retweets: 12000, likes: 45000, hasImage: 1, imageBg: 0x1a1a2e },
    \\    { user: 'Pieter Levels', handle: 'levelsio', avatar: 'PL', avatarBg: 0xf59e0b, time: '11h', text: 'Built a new SaaS in 48 hours. Already at $2k MRR. Stack: one PHP file and vibes.', replies: 2300, retweets: 4500, likes: 31200, hasImage: 0, imageBg: 0 },
    \\    { user: 'Mozilla', handle: 'mozilla', avatar: 'MZ', avatarBg: 0xff6611, time: '12h', text: 'Firefox 140 is here. We added nothing new but removed three things you loved. You are welcome.', replies: 3400, retweets: 7800, likes: 19500, hasImage: 0, imageBg: 0 },
    \\    { user: 'Andrej Karpathy', handle: 'karpathy', avatar: 'AK', avatarBg: 0x10b981, time: '13h', text: 'The best way to understand transformers is to implement one from scratch. In a weekend. With no dependencies. On a potato.', replies: 890, retweets: 6700, likes: 42000, hasImage: 0, imageBg: 0 },
    \\    { user: 'Bloomberg', handle: 'business', avatar: 'BB', avatarBg: 0x2800d7, time: '14h', text: 'BREAKING: S&P 500 hits all-time high as traders react to Fed holding rates steady. Market up 2.3%.', replies: 1100, retweets: 3200, likes: 8900, hasImage: 1, imageBg: 0x0d1117 },
    \\    { user: 'Linus Torvalds', handle: 'laborvalds', avatar: 'LT', avatarBg: 0xf1c40f, time: '15h', text: 'Reviewed 47 pull requests today. Rejected 46. The one I merged was a typo fix.', replies: 2100, retweets: 15000, likes: 78000, hasImage: 0, imageBg: 0 },
    \\    { user: 'Fireship', handle: 'firaboreship', avatar: 'FS', avatarBg: 0xff4500, time: '16h', text: 'JavaScript frameworks per year: 2015: 12, 2020: 24, 2025: 48. By 2030 every npm install creates a new framework.', replies: 3600, retweets: 9200, likes: 56000, hasImage: 0, imageBg: 0 },
    \\    { user: 'Jane Street', handle: 'jaboranestreet', avatar: 'JS', avatarBg: 0x1e3a5f, time: '17h', text: 'We are hiring. Must know OCaml. Must enjoy puzzles. Must accept that your interview will be harder than your actual job.', replies: 980, retweets: 4300, likes: 22000, hasImage: 0, imageBg: 0 },
    \\    { user: 'OpenAI', handle: 'OpenAI', avatar: 'OA', avatarBg: 0x10a37f, time: '18h', text: 'Introducing GPT-6. It can now write code, debug code, and mass-produce code that needs debugging.', replies: 8900, retweets: 34000, likes: 156000, hasImage: 1, imageBg: 0x0d0d0d },
    \\    { user: 'DHH', handle: 'dhh', avatar: 'DH', avatarBg: 0xcc0000, time: '19h', text: 'We just mass-deployed our entire SaaS on a single $40/month server. Your microservices architecture is a skill issue.', replies: 4500, retweets: 11000, likes: 67000, hasImage: 0, imageBg: 0 },
    \\    { user: 'Nature', handle: 'Nature', avatar: 'NT', avatarBg: 0x2e86ab, time: '20h', text: 'Study finds that octopuses dream and their skin changes color during REM sleep. They are literally living their dreams.', replies: 1200, retweets: 18000, likes: 92000, hasImage: 1, imageBg: 0x0a1628 },
    \\    { user: 'ThePrimeagen', handle: 'ThePrimeagen', avatar: 'TP', avatarBg: 0x9333ea, time: '21h', text: 'Just switched from Neovim to Vim to ed to cat. Next week I am writing code by flipping bits with a magnet.', replies: 2800, retweets: 7600, likes: 48000, hasImage: 0, imageBg: 0 }
    \\  ];
    \\
    \\  var tl = [];
    \\  for (var i = 0; tweets.length > i; i = i + 1) {
    \\    var t = tweets[i];
    \\    var replyStr = '';
    \\    var rtStr = '';
    \\    var likeStr = '';
    \\    if (t.replies > 999) {
    \\      replyStr = Math.floor(t.replies / 100) / 10 + 'K';
    \\    } else {
    \\      replyStr = '' + t.replies;
    \\    }
    \\    if (t.retweets > 999) {
    \\      rtStr = Math.floor(t.retweets / 100) / 10 + 'K';
    \\    } else {
    \\      rtStr = '' + t.retweets;
    \\    }
    \\    if (t.likes > 999) {
    \\      likeStr = Math.floor(t.likes / 100) / 10 + 'K';
    \\    } else {
    \\      likeStr = '' + t.likes;
    \\    }
    \\    tl.push({
    \\      user: t.user,
    \\      handle: '@' + t.handle,
    \\      avatar: t.avatar,
    \\      avatarBg: t.avatarBg,
    \\      time: t.time,
    \\      text: t.text,
    \\      replyStr: replyStr,
    \\      rtStr: rtStr,
    \\      likeStr: likeStr,
    \\      hasImage: t.hasImage,
    \\      imageBg: t.imageBg
    \\    });
    \\  }
    \\  setTweets(tl);
    \\}
    \\
    \\loadData();
    \\
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\tweets = {}
    \\function setTweets(v) tweets = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { flex_direction = "column", width = -1, height = -1, background_color = 0x000000, overflow = "hidden" }, children = {
    \\    { style = { flex_direction = "row", align_items = "center", justify_content = "space_between", padding_left = 16, padding_right = 16, padding_top = 10, padding_bottom = 10, border_color = 0x2f3336, border_width = 1 }, children = {
    \\      { style = { flex_direction = "row", gap = 24 }, children = {
    \\        { text = "For you", font_size = 14, text_color = 0xe7e9ea },
    \\        { text = "Following", font_size = 14, text_color = 0x71767b }
    \\      } },
    \\      { style = { flex_direction = "row", gap = 16 }, children = {
    \\        { text = "Search", font_size = 12, text_color = 0x71767b },
    \\        { text = "Notifs", font_size = 12, text_color = 0x71767b }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 10, padding_left = 16, padding_right = 16, padding_top = 12, padding_bottom = 12, border_color = 0x2f3336, border_width = 1 }, children = {
    \\      { style = { width = 40, height = 40, border_radius = 20, background_color = 0x1d9bf0, align_items = "center", justify_content = "center", flex_shrink = 0, overflow = "auto" }, children = {
    \\        { text = "You", font_size = 13, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_direction = "column", flex_grow = 1, gap = 8, overflow = "auto" }, children = {
    \\        { text = "What is happening?!", font_size = 13, text_color = 0x71767b },
    \\        { style = { flex_direction = "row", justify_content = "end" }, children = {
    \\          { style = { background_color = 0x1d9bf0, border_radius = 16, padding_left = 16, padding_right = 16, padding_top = 6, padding_bottom = 6 }, children = {
    \\            { text = "Post", font_size = 12, text_color = 0xffffff }
    \\          } }
    \\        } }
    \\      } }
    \\    } },
    \\    { style = { overflow = "scroll", flex_grow = 1 }, children = {
    \\      __mapLoop(tweets, function(_item, _i)
    \\        return { style = { flex_direction = "row", gap = 10, padding_left = 16, padding_right = 16, padding_top = 12, padding_bottom = 12, border_color = 0x2f3336, border_width = 1 }, children = {
    \\          { style = { width = 40, height = 40, border_radius = 20, background_color = _item.avatarBg, align_items = "center", justify_content = "center", flex_shrink = 0, overflow = "auto" }, children = {
    \\            { text = tostring(_item.avatar), font_size = 11, text_color = 0xffffff }
    \\          } },
    \\          { style = { flex_direction = "column", gap = 4, flex_shrink = 1 }, children = {
    \\            { style = { flex_direction = "row", gap = 6, align_items = "center" }, children = {
    \\              { text = tostring(_item.user), font_size = 12, text_color = 0xe7e9ea },
    \\              { text = tostring(_item.handle), font_size = 11, text_color = 0x71767b },
    \\              { text = tostring(_item.time), font_size = 11, text_color = 0x71767b }
    \\            } },
    \\            { text = tostring(_item.text), font_size = 12, text_color = 0xe7e9ea },
    \\            (_item . hasImage == 1) and { style = { width = -1, height = 160, border_radius = 12, background_color = _item.imageBg, margin_top = 8 } } or nil,
    \\            { style = { flex_direction = "row", justify_content = space_between, padding_top = 8, padding_right = 32 }, children = {
    \\              { style = { flex_direction = "row", gap = 4, align_items = "center" }, children = {
    \\                { text = "Reply", font_size = 10, text_color = 0x71767b },
    \\                { text = tostring(_item.replyStr), font_size = 10, text_color = 0x71767b }
    \\              } },
    \\              { style = { flex_direction = "row", gap = 4, align_items = "center" }, children = {
    \\                { text = "RT", font_size = 10, text_color = 0x71767b },
    \\                { text = tostring(_item.rtStr), font_size = 10, text_color = 0x71767b }
    \\              } },
    \\              { style = { flex_direction = "row", gap = 4, align_items = "center" }, children = {
    \\                { text = "Like", font_size = 10, text_color = 0x71767b },
    \\                { text = tostring(_item.likeStr), font_size = 10, text_color = 0x71767b }
    \\              } },
    \\              { text = "Share", font_size = 10, text_color = 0x71767b }
    \\            } }
    \\          } }
    \\        } }
    \\      end)
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then tweets = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

