//! Generated by tsz compiler — twitter-clone [state.zig]
//! Source: twitter-clone.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

