//! Generated by tsz compiler — d97_jsx_prop_spread [nodes.zig]
//! Source: d97_jsx_prop_spread.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d97_jsx_prop_spread:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

