//! Generated by tsz compiler — d97_jsx_prop_spread [state.zig]
//! Source: d97_jsx_prop_spread.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

