//! Generated by tsz compiler — 04_align_items [logic.zig]
//! Source: 04_align_items.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, flex_direction = "column", padding = 10, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "WPT: align-items", font_size = 18 },
    \\    { text = "VERIFY: stretch fills height, start/center/end position items at top/middle/bottom", font_size = 10, text_color = 0x888888 },
    \\    { style = { background_color = 0x0d1117, border_radius = 4, padding = 6, padding_left = 10, padding_right = 10, flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\      { text = "WPT", font_size = 9, text_color = 0x8b949e },
    \\      { text = "align-items", font_size = 10, text_color = 0x58a6ff }
    \\    } },
    \\    { text = "stretch (default) — items stretch to fill cross axis", font_size = 11 },
    \\    { style = { flex_direction = "row", align_items = "stretch", width = 300, height = 80, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { width = 40, background_color = 0x4caf50 } },
    \\      { style = { width = 40, background_color = 0x2196f3 } },
    \\      { style = { width = 40, background_color = 0xff9800 } }
    \\    } },
    \\    { text = "start — items aligned to cross-start", font_size = 11 },
    \\    { style = { flex_direction = "row", align_items = "start", width = 300, height = 80, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { width = 40, height = 20, background_color = 0x4caf50 } },
    \\      { style = { width = 40, height = 40, background_color = 0x2196f3 } },
    \\      { style = { width = 40, height = 30, background_color = 0xff9800 } }
    \\    } },
    \\    { text = "center — items centered on cross axis", font_size = 11 },
    \\    { style = { flex_direction = "row", align_items = "center", width = 300, height = 80, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { width = 40, height = 20, background_color = 0x4caf50 } },
    \\      { style = { width = 40, height = 40, background_color = 0x2196f3 } },
    \\      { style = { width = 40, height = 30, background_color = 0xff9800 } }
    \\    } },
    \\    { text = "end — items aligned to cross-end", font_size = 11 },
    \\    { style = { flex_direction = "row", align_items = "end", width = 300, height = 80, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { width = 40, height = 20, background_color = 0x4caf50 } },
    \\      { style = { width = 40, height = 40, background_color = 0x2196f3 } },
    \\      { style = { width = 40, height = 30, background_color = 0xff9800 } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

