//! Generated by tsz compiler — d139_fallback_in_classifier [logic.zig]
//! Source: d139_fallback_in_classifier.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var itemName = "";
    \\function setItemName(v) { itemName = v; if (__luaReady) __luaEval("setItemName(\'" + v + "\')"); else __markDirty(); }
    \\var itemLane = "";
    \\function setItemLane(v) { itemLane = v; if (__luaReady) __luaEval("setItemLane(\'" + v + "\')"); else __markDirty(); }
    \\var itemStatus = "unknown";
    \\function setItemStatus(v) { itemStatus = v; if (__luaReady) __luaEval("setItemStatus(\'" + v + "\')"); else __markDirty(); }
    \\var itemDay = "";
    \\function setItemDay(v) { itemDay = v; if (__luaReady) __luaEval("setItemDay(\'" + v + "\')"); else __markDirty(); }
    \\var hasDetail = 0;
    \\function setHasDetail(v) { hasDetail = v; if (__luaReady) __luaEval("setHasDetail(" + v + ")"); else __markDirty(); }
    \\function statusColor(st) {
    \\  if (st === 'pass') return '#34d399';
    \\  if (st === 'fail') return '#f87171';
    \\  return '#94a3b8';
    \\}
    \\
    \\setItemName('test_alpha');
    \\setItemLane('mixed');
    \\setItemStatus('pass');
    \\setHasDetail(1);
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["itemName"] = ""
    \\itemName = _state["itemName"]
    \\function setItemName(v) _state["itemName"] = v; itemName = v; __syncToJS("itemName", v); __markDirty() end
    \\_state["itemLane"] = ""
    \\itemLane = _state["itemLane"]
    \\function setItemLane(v) _state["itemLane"] = v; itemLane = v; __syncToJS("itemLane", v); __markDirty() end
    \\_state["itemStatus"] = "unknown"
    \\itemStatus = _state["itemStatus"]
    \\function setItemStatus(v) _state["itemStatus"] = v; itemStatus = v; __syncToJS("itemStatus", v); __markDirty() end
    \\_state["itemDay"] = ""
    \\itemDay = _state["itemDay"]
    \\function setItemDay(v) _state["itemDay"] = v; itemDay = v; __syncToJS("itemDay", v); __markDirty() end
    \\_state["hasDetail"] = 0
    \\hasDetail = _state["hasDetail"]
    \\function setHasDetail(v) _state["hasDetail"] = v; hasDetail = v; __syncToJS("hasDetail", v); __markDirty() end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x0f1a25, padding = 16, gap = 10, overflow = "hidden" }, children = {
    \\    { text = "d139 — fallback in classifier", font_size = 14, text_color = 0xe8eef5 },
    \\    { style = { flex_direction = "row", gap = 12 }, children = {
    \\      { children = {
    \\        { text = "Name", font_size = 9, text_color = 0x7b93a6 },
    \\        { text = tostring(itemName  or  '--'), font_size = 12, text_color = 0xd5dfeb }
    \\      } },
    \\      { children = {
    \\        { text = "Lane", font_size = 9, text_color = 0x7b93a6 },
    \\        { text = tostring(itemLane  or  '--'), font_size = 12, text_color = 0xd5dfeb }
    \\      } },
    \\      { children = {
    \\        { text = "Status", font_size = 9, text_color = 0x7b93a6 },
    \\        { text = tostring(itemStatus  or  '--'), font_size = 12, text_color = 0x000000 }
    \\      } },
    \\      { children = {
    \\        { text = "Built", font_size = 9, text_color = 0x7b93a6 },
    \\        { text = tostring(itemDay  or  '--'), font_size = 12, text_color = 0xd5dfeb }
    \\      } }
    \\    } },
    \\    (hasDetail == 1) and { style = { background_color = 0x12202e, border_radius = 8, padding = 10, gap = 6 }, children = {
    \\      { children = {
    \\        { text = "Full name", font_size = 9, text_color = 0x7b93a6 },
    \\        { text = tostring(itemName  or  'none'), font_size = 12, text_color = 0xd5dfeb }
    \\      } },
    \\      { children = {
    \\        { text = "Status detail", font_size = 9, text_color = 0x7b93a6 },
    \\        { text = tostring((hasDetail == 1) and "verified" or ""), font_size = 12, text_color = 0x000000 }
    \\      } }
    \\    } } or nil,
    \\    { style = { background_color = 0x152634, padding = 6, border_radius = 6, flex_direction = "row", gap = 8 }, children = {
    \\      { text = "detail panel", font_size = 9, text_color = 0x38bdf8 },
    \\      { text = tostring(itemName || 'nothing') .. " | " .. tostring(itemLane || 'unknown'), font_size = 9, text_color = 0x475569 }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

