//! Generated by tsz compiler — d121_variant_switching [nodes.zig]
//! Source: d121_variant_switching.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d121_variant_switching:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

