//! Generated by tsz compiler — d85_math_heavy [nodes.zig]
//! Source: d85_math_heavy.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d85_math_heavy:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

