//! Generated by tsz compiler — d85_math_heavy [state.zig]
//! Source: d85_math_heavy.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

