//! Generated by tsz compiler — kanban-clone [app.zig]
//! Source: kanban-clone.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const engine = api.engine;
const qjs_runtime = api.qjs_runtime;
const luajit_runtime = api.luajit_runtime;
const nodes = @import("nodes.zig");
const st = @import("state.zig");
const logic = @import("logic.zig");

fn _appInit() void {
    luajit_runtime.setMapWrapper(0, @ptrCast(&nodes._root));
    // OA data synced on first tick (after logic.JS_LOGIC loads)
    state.markDirty();
}

var _first_render: bool = true;
fn _appTick(now: u32) void {
    _ = now;
    if (_first_render or state.isDirty()) {
        qjs_runtime.evalLuaMapData(0, "backlog");
        qjs_runtime.evalLuaMapData(1, "inProgress");
        qjs_runtime.evalLuaMapData(2, "review");
        qjs_runtime.evalLuaMapData(3, "done");
        luajit_runtime.callGlobal("__render");
        state.clearDirty();
        _first_render = false;
    }
}

export fn app_get_root() *Node { return &nodes._root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return logic.JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return logic.JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return logic.LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return logic.LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "kanban-clone"; }

export fn app_state_count() usize { return 4; }

pub fn main() !void {
    try engine.run(.{
        .title = "kanban-clone",
        .root = &nodes._root,
        .init = _appInit,
        .tick = _appTick,
        .js_logic = logic.JS_LOGIC,
        .lua_logic = logic.LUA_LOGIC,
    });
}

// ── Smith debug log ──
// DBG: [LUA_NODE_MISS] tag=ScrollView child=0 keys=nodeExpr,_luaMapWrapper nodeExpr=.{ .test_id = "__lmw0" }
// DBG: [LUA_NODE_MISS] tag=ScrollView child=0 keys=nodeExpr,_luaMapWrapper nodeExpr=.{ .test_id = "__lmw1" }
// DBG: [LUA_NODE_MISS] tag=ScrollView child=0 keys=nodeExpr,_luaMapWrapper nodeExpr=.{ .test_id = "__lmw2" }
// DBG: [LUA_NODE_MISS] tag=ScrollView child=0 keys=nodeExpr,_luaMapWrapper nodeExpr=.{ .test_id = "__lmw3" }
