//! Generated by tsz compiler — kanban-clone [nodes.zig]
//! Source: kanban-clone.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:kanban-clone:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

