//! Generated by tsz compiler — d79_shorthand_properties [logic.zig]
//! Source: d79_shorthand_properties.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var count = 0;
    \\function setCount(v) { count = v; if (__luaReady) __luaEval("setCount(" + v + ")"); else __markDirty(); }
    \\var items = [ { name : "" , score : 0 , active : 0 } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var log = [];
    \\
    \\function createItem(name, score, active) {
    \\  // Shorthand: { name, score, active } instead of { name: name, score: score, active: active }
    \\  var item = { name: name, score: score, active: active };
    \\  log.push(item);
    \\  setItems(log);
    \\  setCount(log.length);
    \\  setOutput('added ' + name + ' (' + score + ')');
    \\}
    \\
    \\function buildFromParts() {
    \\  var name = 'Generated';
    \\  var score = 77;
    \\  var active = 1;
    \\  // Mix of shorthand and explicit
    \\  var item = { name: name, score: score, active: active };
    \\  log.push(item);
    \\  setItems(log);
    \\  setCount(log.length);
    \\  setOutput('built from parts');
    \\}
    \\
    \\function clearAll() {
    \\  log = [];
    \\  setItems(log);
    \\  setCount(0);
    \\  setOutput('cleared');
    \\}
    \\
    \\createItem('Alice', 95, 1);
    \\createItem('Bob', 72, 1);
    \\createItem('Carol', 88, 0);
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\_state["count"] = 0
    \\count = _state["count"]
    \\function setCount(v) _state["count"] = v; count = v; __syncToJS("count", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Shorthand Properties", font_size = 16, text_color = 0xe2e8f0 },
    \\    { text = tostring(count) .. " items", font_size = 10, text_color = 0x64748b },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "createItem ( \"Dave\" , 61 , 1 )", children = {
    \\        { text = "Add Dave", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "createItem ( \"Eve\" , 43 , 0 )", children = {
    \\        { text = "Add Eve", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x1e40af, border_radius = 6 }, js_on_press = "buildFromParts ( )", children = {
    \\        { text = "Build", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { padding = 8, background_color = 0xdc2626, border_radius = 6 }, js_on_press = "clearAll ( )", children = {
    \\        { text = "Clear", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(items, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 8, background_color = 0x1e293b, border_radius = 4 }, children = {
    \\          { style = { flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\            (_item . active == 1) and { style = { width = 6, height = 6, border_radius = 3, background_color = 0x22c55e } } or nil,
    \\            (_item . active == 0) and { style = { width = 6, height = 6, border_radius = 3, background_color = 0x475569 } } or nil,
    \\            { text = tostring(_item.name), font_size = 11, text_color = 0xe2e8f0 }
    \\          } },
    \\          { text = tostring(_item.score), font_size = 10, text_color = 0x6ee7b7 }
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x6ee7b7 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

