//! Generated by tsz compiler — d79_shorthand_properties [state.zig]
//! Source: d79_shorthand_properties.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

