//! Generated by tsz compiler — d44_classifier_styles [logic.zig]
//! Source: d44_classifier_styles.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var selected = "";
    \\function setSelected(v) { selected = v; if (__luaReady) __luaEval("setSelected(\'" + v + "\')"); else __markDirty(); }
    \\var count = 0;
    \\function setCount(v) { count = v; if (__luaReady) __luaEval("setCount(" + v + ")"); else __markDirty(); }
    \\var items = [ { title : "" , status : 0 } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var data = [];
    \\var data = [
    \\  { title: 'Setup CI', status: 1 },
    \\  { title: 'Write tests', status: 0 },
    \\  { title: 'Deploy v3', status: 0 },
    \\  { title: 'Fix auth bug', status: 1 },
    \\  { title: 'Update deps', status: 2 }
    \\];
    \\setItems(data);
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["selected"] = ""
    \\selected = _state["selected"]
    \\function setSelected(v) _state["selected"] = v; selected = v; __syncToJS("selected", v); __markDirty() end
    \\_state["count"] = 0
    \\count = _state["count"]
    \\function setCount(v) _state["count"] = v; count = v; __syncToJS("count", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\data = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0d1117, padding = 20, width = -1, height = -1, gap = 10, overflow = "hidden" }, children = {
    \\    { text = "Classifier Styles", font_size = 16, text_color = 0xc9d1d9 },
    \\    { style = { gap = 6 }, children = {
    \\      __mapLoop(items, function(_item, _i)
    \\        return { style = { gap = 8, border_color = 0x30363d, border_width = 1, border_radius = 8, background_color = 0x161b22, padding = 12 }, children = {
    \\          { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\            { text = tostring(_item.title), font_size = 13, text_color = 0xc9d1d9 },
    \\            (_item . status == 0) and { style = { padding_bottom = 2, padding_top = 2, padding_right = 6, padding_left = 6, border_radius = 4, background_color = 0x6e7681 }, children = {
    \\              { text = "TODO", font_size = 9, text_color = 0xffffff }
    \\            } } or nil,
    \\            (_item . status == 1) and { style = { padding_bottom = 2, padding_top = 2, padding_right = 6, padding_left = 6, border_radius = 4, background_color = 0x238636 }, children = {
    \\              { text = "DONE", font_size = 9, text_color = 0xffffff }
    \\            } } or nil,
    \\            (_item . status == 2) and { style = { padding_bottom = 2, padding_top = 2, padding_right = 6, padding_left = 6, border_radius = 4, background_color = 0xda3633 }, children = {
    \\              { text = "BLOCKED", font_size = 9, text_color = 0xffffff }
    \\            } } or nil
    \\          } },
    \\          { text = "Task " .. tostring((_i - 1)), font_size = 10, text_color = 0x8b949e }
    \\        } }
    \\      end)
    \\    } },
    \\    { style = { align_items = "center", padding = 8, border_radius = 6, background_color = 0x238636 }, lua_on_press = "setCount(count + 1)", children = {
    \\      { text = "Actions: " .. tostring(count), font_size = 11, text_color = 0xffffff }
    \\    } },
    \\    { text = "selected: " .. tostring(selected), font_size = 10, text_color = 0x484f58 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

