//! Generated by tsz compiler — d44_classifier_styles [state.zig]
//! Source: d44_classifier_styles.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

