//! Generated by tsz compiler — d13_schema_form [nodes.zig]
//! Source: d13_schema_form.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d13_schema_form:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

