//! Generated by tsz compiler — d49_string_state [state.zig]
//! Source: d49_string_state.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

