//! Generated by tsz compiler — d47_nested_ternary [nodes.zig]
//! Source: d47_nested_ternary.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d47_nested_ternary:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

