//! Generated by tsz compiler — d76_new_expression [logic.zig]
//! Source: d76_new_expression.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var count = 0;
    \\function setCount(v) { count = v; if (__luaReady) __luaEval("setCount(" + v + ")"); else __markDirty(); }
    \\var items = [ { label : "" , value : "" } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var log = [];
    \\
    \\function testNewDate() {
    \\  var d = new Date();
    \\  var ts = d.getTime();
    \\  log.push({ label: 'Date.getTime()', value: '' + ts });
    \\  setItems(log);
    \\  setCount(log.length);
    \\  setOutput('created Date, ts=' + ts);
    \\}
    \\
    \\function testNewArray() {
    \\  var arr = new Array(5);
    \\  log.push({ label: 'new Array(5)', value: 'length=' + arr.length });
    \\  setItems(log);
    \\  setCount(log.length);
    \\  setOutput('created Array(5), len=' + arr.length);
    \\}
    \\
    \\function testNewError() {
    \\  try {
    \\    throw new Error('test error');
    \\  } catch (e) {
    \\    log.push({ label: 'new Error()', value: e.message });
    \\    setItems(log);
    \\    setCount(log.length);
    \\    setOutput('caught: ' + e.message);
    \\  }
    \\}
    \\
    \\function testNewObject() {
    \\  var obj = new Object();
    \\  obj.name = 'test';
    \\  obj.value = 42;
    \\  log.push({ label: 'new Object()', value: obj.name + '=' + obj.value });
    \\  setItems(log);
    \\  setCount(log.length);
    \\  setOutput('created object: ' + obj.name);
    \\}
    \\
    \\function clearLog() {
    \\  log = [];
    \\  setItems(log);
    \\  setCount(0);
    \\  setOutput('cleared');
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\_state["count"] = 0
    \\count = _state["count"]
    \\function setCount(v) _state["count"] = v; count = v; __syncToJS("count", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "new Expression", font_size = 16, text_color = 0xe2e8f0 },
    \\    { text = tostring(count) .. " tests run", font_size = 10, text_color = 0x64748b },
    \\    { style = { flex_direction = "row", gap = 6, flex_wrap = "wrap" }, children = {
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "testNewDate ( )", children = {
    \\        { text = "new Date()", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "testNewArray ( )", children = {
    \\        { text = "new Array(5)", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "testNewError ( )", children = {
    \\        { text = "new Error()", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "testNewObject ( )", children = {
    \\        { text = "new Object()", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0xdc2626, border_radius = 6 }, js_on_press = "clearLog ( )", children = {
    \\        { text = "Clear", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(items, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", padding = 8, background_color = 0x1e293b, border_radius = 4 }, children = {
    \\          { text = tostring(_item.label), font_size = 10, text_color = 0x94a3b8 },
    \\          { text = tostring(_item.value), font_size = 10, text_color = 0x6ee7b7 }
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x6ee7b7 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

