//! Generated by tsz compiler — d124_variant_switcher [state.zig]
//! Source: d124_variant_switcher.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

