//! Generated by tsz compiler — d46_multiline_comments [logic.zig]
//! Source: d46_multiline_comments.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var count = 0;
    \\function setCount(v) { count = v; if (__luaReady) __luaEval("setCount(" + v + ")"); else __markDirty(); }
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\/* initial setup comment */
    \\setOutput('ready');
    \\
    \\function increment() {
    \\  /* this increments the counter */
    \\  setCount(count + 1);
    \\  setOutput('incremented to ' + (count + 1));
    \\}
    \\
    \\function reset() {
    \\  /*
    \\   * Reset everything back to zero.
    \\   * Multi-line inside a function.
    \\   */
    \\  setCount(0);
    \\  setOutput('reset');
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["count"] = 0
    \\count = _state["count"]
    \\function setCount(v) _state["count"] = v; count = v; __syncToJS("count", v); __markDirty() end
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Block Comments", font_size = 16, text_color = 0xe2e8f0 },
    \\    { text = tostring(count), font_size = 24, text_color = 0x3b82f6 },
    \\    { style = { flex_direction = "row", gap = 8 }, children = {
    \\      { style = { padding = 10, background_color = 0x334155, border_radius = 6 }, js_on_press = "increment ( )", children = {
    \\        { text = "+1", font_size = 12, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 10, background_color = 0xdc2626, border_radius = 6 }, js_on_press = "reset ( )", children = {
    \\        { text = "Reset", font_size = 12, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x64748b }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

