//! Generated by tsz compiler — s07b_node_editor [logic.zig]
//! Source: s07b_node_editor.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var selected = -1;
    \\function setSelected(v) { selected = v; if (__luaReady) __luaEval("setSelected(" + v + ")"); else __markDirty(); }
    \\var nodeCount = 0;
    \\function setNodeCount(v) { nodeCount = v; if (__luaReady) __luaEval("setNodeCount(" + v + ")"); else __markDirty(); }
    \\var nodes = [ { id : 0 , title : "" , x : 0 , y : 0 , color : "" } ];
    \\function setNodes(v) { nodes = v; __markDirty(); }
    \\var edges = [ { from : 0 , to : 0 } ];
    \\function setEdges(v) { edges = v; __markDirty(); }
    \\var nodeList = [];
    \\var edgeList = [];
    \\var nodeList = [
    \\  { id: 0, title: 'Input', x: 60, y: 80, color: '#3b82f6' },
    \\  { id: 1, title: 'Process', x: 220, y: 160, color: '#8b5cf6' },
    \\  { id: 2, title: 'Output', x: 380, y: 80, color: '#22c55e' }
    \\];
    \\var edgeList = [
    \\  { from: 0, to: 1 },
    \\  { from: 1, to: 2 }
    \\];
    \\sync();
    \\
    \\function sync() {
    \\  setNodes(nodeList);
    \\  setEdges(edgeList);
    \\  setNodeCount(nodeList.length);
    \\}
    \\
    \\var nextId = 3;
    \\var colors = ['#3b82f6', '#8b5cf6', '#ef4444', '#f59e0b', '#22c55e', '#06b6d4'];
    \\
    \\function addNode() {
    \\  var id = nextId;
    \\  nodeList.push({ id: id, title: 'Node ' + id, x: 60 + (id * 80) % 360, y: 60 + (id * 60) % 200, color: colors[id % colors.length] });
    \\  nextId++;
    \\  sync();
    \\}
    \\
    \\function removeNode(idx) {
    \\  var removed = nodeList[idx].id;
    \\  var result = [];
    \\  for (var i = 0; i < nodeList.length; i++) {
    \\    if (i !== idx) result.push(nodeList[i]);
    \\  }
    \\  nodeList = result;
    \\  var newEdges = [];
    \\  for (var j = 0; j < edgeList.length; j++) {
    \\    if (edgeList[j].from !== removed && edgeList[j].to !== removed) newEdges.push(edgeList[j]);
    \\  }
    \\  edgeList = newEdges;
    \\  setSelected(-1);
    \\  sync();
    \\}
    \\
    \\function connectSelected(toIdx) {
    \\  if (selected < 0 || selected === toIdx) return;
    \\  edgeList.push({ from: nodeList[selected].id, to: nodeList[toIdx].id });
    \\  setSelected(-1);
    \\  sync();
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["selected"] = -1
    \\selected = _state["selected"]
    \\function setSelected(v) _state["selected"] = v; selected = v; __syncToJS("selected", v); __markDirty() end
    \\_state["nodeCount"] = 0
    \\nodeCount = _state["nodeCount"]
    \\function setNodeCount(v) _state["nodeCount"] = v; nodeCount = v; __syncToJS("nodeCount", v); __markDirty() end
    \\
    \\nodes = {}
    \\function setNodes(v) nodes = v; __markDirty() end
    \\edges = {}
    \\function setEdges(v) edges = v; __markDirty() end
    \\nodeList = {}
    \\edgeList = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0c0f1a, width = -1, height = -1, padding = 16, gap = 12, overflow = "hidden" }, children = {
    \\    { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\      { text = "Node Editor", font_size = 16, text_color = 0xe2e8f0 },
    \\      { style = { flex_direction = "row", gap = 8 }, children = {
    \\        { style = { padding = 8, background_color = 0x3b82f6, border_radius = 6 }, lua_on_press = "addNode()", children = {
    \\          { text = "+ Node", font_size = 11, text_color = 0xffffff }
    \\        } },
    \\        { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, lua_on_press = "setSelected( - 1)", children = {
    \\          { text = "Deselect", font_size = 11, text_color = 0x94a3b8 }
    \\        } }
    \\      } }
    \\    } },
    \\    { text = tostring((selected >= 0) and "" or ""), font_size = 10, text_color = 0x475569 },
    \\    { style = { flex_grow = 1, background_color = 0x111827, border_radius = 10, padding = 8, gap = 6, overflow = "auto" }, children = {
    \\      { text = tostring(nodeCount) .. " nodes  •  " .. tostring(#edges) .. " edges", font_size = 10, text_color = 0x334155 },
    \\      { style = { flex_wrap = "wrap", flex_direction = "row", gap = 8 }, children = {
    \\        __mapLoop(nodes, function(_item, _i)
    \\          return { style = { background_color = (selected == (_i - 1)) and 0x1e3a5f or 0x1e293b, border_radius = 8, padding = 12, gap = 4, min_width = 90, border_width = 2, border_color = _item.color }, js_on_press = "selected >= 0 ? connectSelected(" .. ((_i - 1)) .. ") : setSelected(" .. ((_i - 1)) .. ")", children = {
    \\            { style = { width = 10, height = 10, border_radius = 5, background_color = _item.color } },
    \\            { text = tostring(_item.title), font_size = 12, text_color = 0xe2e8f0 },
    \\            { text = "(" .. tostring(_item.x) .. ", " .. tostring(_item.y) .. ")", font_size = 9, text_color = 0x475569 },
    \\            { style = { margin_top = 4 }, js_on_press = "removeNode(" .. ((_i - 1)) .. ")", children = {
    \\              { text = "remove", font_size = 9, text_color = 0xef4444 }
    \\            } }
    \\          } }
    \\        end)
    \\      } },
    \\      { style = { gap = 2, margin_top = 8 }, children = {
    \\        { text = "Connections:", font_size = 10, text_color = 0x475569 },
    \\        __mapLoop(edges, function(_item, _i)
    \\          return { text = tostring(_item.from) .. " → " .. tostring(_item.to), font_size = 10, text_color = 0x64748b }
    \\        end)
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then nodes = __luaMapData0 end
    \\  if __luaMapData1 then edges = __luaMapData1 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

