//! Generated by tsz compiler — s07b_node_editor [state.zig]
//! Source: s07b_node_editor.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

