//! Generated by tsz compiler — 20_real_world_layouts [logic.zig]
//! Source: 20_real_world_layouts.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, flex_direction = "column", padding = 10, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "WPT: real-world layout patterns", font_size = 18 },
    \\    { text = "VERIFY: Holy grail layout (header/sidebar/main/aside/footer), card grid wraps, toolbar with spacer", font_size = 10, text_color = 0x888888 },
    \\    { text = "Holy grail layout — header, sidebar+main+aside, footer", font_size = 11 },
    \\    { style = { flex_direction = "column", width = 400, height = 250, background_color = 0x222222, overflow = "auto" }, children = {
    \\      { style = { height = 30, background_color = 0x1565c0, justify_content = "center", align_items = "center", overflow = "auto" }, children = {
    \\        { text = "Header", font_size = 12, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_direction = "row", flex_grow = 1, overflow = "auto" }, children = {
    \\        { style = { width = 80, background_color = 0x2e7d32, justify_content = "center", align_items = "center" }, children = {
    \\          { text = "Sidebar", font_size = 10, text_color = 0xffffff }
    \\        } },
    \\        { style = { flex_grow = 1, background_color = 0x37474f, justify_content = "center", align_items = "center", overflow = "auto" }, children = {
    \\          { text = "Main Content", font_size = 12, text_color = 0xffffff }
    \\        } },
    \\        { style = { width = 60, background_color = 0x4527a0, justify_content = "center", align_items = "center" }, children = {
    \\          { text = "Aside", font_size = 10, text_color = 0xffffff }
    \\        } }
    \\      } },
    \\      { style = { height = 25, background_color = 0x424242, justify_content = "center", align_items = "center", overflow = "auto" }, children = {
    \\        { text = "Footer", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "Card grid with wrap — responsive card layout", font_size = 11 },
    \\    { style = { flex_direction = "row", flex_wrap = "wrap", width = 350, background_color = 0x222222, gap = 8, padding = 8 }, children = {
    \\      { style = { width = 100, height = 80, background_color = 0xe91e63, padding = 8, overflow = "auto" }, children = {
    \\        { text = "Card 1", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 80, background_color = 0x9c27b0, padding = 8, overflow = "auto" }, children = {
    \\        { text = "Card 2", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 80, background_color = 0x3f51b5, padding = 8, overflow = "auto" }, children = {
    \\        { text = "Card 3", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 80, background_color = 0x009688, padding = 8, overflow = "auto" }, children = {
    \\        { text = "Card 4", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 80, background_color = 0xff5722, padding = 8, overflow = "auto" }, children = {
    \\        { text = "Card 5", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "Toolbar — icon buttons with spacer", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 350, height = 36, background_color = 0x333333, align_items = "center", padding = 4, gap = 4, overflow = "auto" }, children = {
    \\      { style = { width = 28, height = 28, background_color = 0x4caf50 } },
    \\      { style = { width = 28, height = 28, background_color = 0x2196f3 } },
    \\      { style = { width = 28, height = 28, background_color = 0xff9800 } },
    \\      { style = { flex_grow = 1 } },
    \\      { style = { width = 28, height = 28, background_color = 0xf44336 } },
    \\      { style = { width = 28, height = 28, background_color = 0x9c27b0 } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

