//! Generated by tsz compiler — d31a_state_machine_script [state.zig]
//! Source: d31a_state_machine_script.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

