//! Generated by tsz compiler — d33_extreme_nesting [state.zig]
//! Source: d33_extreme_nesting.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

