//! Generated by tsz compiler — d07_sibling_maps_shared_state [state.zig]
//! Source: d07_sibling_maps_shared_state.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

