//! Generated by tsz compiler — d77_do_while [state.zig]
//! Source: d77_do_while.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

