//! Generated by tsz compiler — todomvc [nodes.zig]
//! Source: todomvc.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:todomvc:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

