//! Generated by tsz compiler — d56_multiple_maps_nested [nodes.zig]
//! Source: d56_multiple_maps_nested.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d56_multiple_maps_nested:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

