//! Generated by tsz compiler — d56_multiple_maps_nested [state.zig]
//! Source: d56_multiple_maps_nested.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

