//! Generated by tsz compiler — d70_strict_equality [nodes.zig]
//! Source: d70_strict_equality.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d70_strict_equality:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

