//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: carts/conformance/d26b_timer_zscript.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime carts/conformance/d26b_timer_zscript.tsz
//! To modify: edit d26b_timer_zscript.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}
// ── Functions ──────────────────────────────────────

fn startTimer() void {
    if (running == 1) {
        return;
    }
    setRunning(1);
    startTime = Date.now();
    setMessage("Timer started");
    timerId = setInterval(function(), .{ setTicks(ticks + 1), ;, var, secs, =, @floor((Date.now() - startTime) / 1000), ;, setElapsed(secs), ; }, 500);
    setTimeout(function(), .{ setMessage("5s milestone reached"), ; }, 5000);
}

fn stopTimer() void {
    if (timerId != null) {
        clearInterval(timerId.?);
        timerId = null;
    }
    setRunning(0);
    setMessage("Timer stopped at " + ticks + " ticks");
}

fn resetTimer() void {
    stopTimer();
    setTicks(0);
    setElapsed(0);
    setMessage("Timer reset");
}

fn App() void {
    return (<);
    Box;
    style = .{ .{ .background_color = "#0d1117", .padding = 20, .width = "100%", .height = "100%", .gap = 12 } } > <;
    Text;
    fontSize = .{ 16 };
    color = "#c9d1d9" > Timer;
    Test;
    </;
    Text > <;
    Text;
    fontSize = .{ 32 };
    color = "#58a6ff" > .{ std.fmt.comptimePrint("{s}", .{ ticks }) };
    </;
    Text > <;
    Text;
    fontSize = .{ 11 };
    color = "#8b949e" > .{ std.fmt.comptimePrint("elapsed: {s}s", .{ elapsed }) };
    </;
    Text > <;
    Box;
    style = .{ .{ .flex_direction = "row", .gap = 8 } } > <;
    Pressable;
    onPress = .{ ()), =>, .{ startTimer() } };
    style = .{ .{ .padding = 10, .background_color = "#238636", .border_radius = 6 } } > <;
    Text;
    fontSize = .{ 12 };
    color = "#ffffff" > Start;
    </;
    Text > </;
    Pressable > <;
    Pressable;
    onPress = .{ ()), =>, .{ stopTimer() } };
    style = .{ .{ .padding = 10, .background_color = "#da3633", .border_radius = 6 } } > <;
    Text;
    fontSize = .{ 12 };
    color = "#ffffff" > Stop;
    </;
    Text > </;
    Pressable > <;
    Pressable;
    onPress = .{ ()), =>, .{ resetTimer() } };
    style = .{ .{ .padding = 10, .background_color = "#6e7681", .border_radius = 6 } } > <;
    Text;
    fontSize = .{ 12 };
    color = "#ffffff" > Reset;
    </;
    Text > </;
    Pressable > </;
    Box > .{ running, ==, 1 and <, Text, fontSize, =, .{ 10 }, color, =, "#3fb950" > RUNNING, </, Text, > };
    .{ running, ==, 0 and <, Text, fontSize, =, .{ 10 }, color, =, "#6e7681" > STOPPED, </, Text, > } < Text;
    fontSize = .{ 10 };
    color = "#484f58" > .{ .message = message };
    </;
    Text > </;
    Box > );
}
