//! Generated by tsz compiler (Zig) — do not edit
//!
//! Source: d16_state_stress.tsz

const std = @import("std");
const build_options = @import("build_options");
const IS_LIB = if (@hasDecl(build_options, "is_lib")) build_options.is_lib else false;

const layout = @import("framework/layout.zig");
const Node = layout.Node;
const Style = layout.Style;
const Color = layout.Color;
const state = @import("framework/state.zig");
const engine = if (IS_LIB) struct {} else @import("framework/engine.zig");

// ── State manifest ──────────────────────────────────────────────
// slot 0: a (int)
// slot 1: b (int)
// slot 2: c (int)
// slot 3: d (int)
// slot 4: e (int)
// slot 5: f (int)
// slot 6: g (int)
// slot 7: h (int)
// slot 8: total (int)
// slot 9: phase (int)
// slot 10: history (int)
// slot 11: barWidth (int)
comptime { if (12 != 12) @compileError("state slot count mismatch"); }

// ── Generated node tree ─────────────────────────────────────────
// tsz:d16_state_stress.tsz:35 — <Pressable>
var _arr_0 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(59, 130, 246) } };
// tsz:d16_state_stress.tsz:38 — <Pressable>
var _arr_1 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(34, 197, 94) } };
// tsz:d16_state_stress.tsz:41 — <Pressable>
var _arr_2 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(245, 158, 11) } };
// tsz:d16_state_stress.tsz:44 — <Pressable>
var _arr_3 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(239, 68, 68) } };
// tsz:d16_state_stress.tsz:47 — <Pressable>
var _arr_4 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(139, 92, 246) } };
// tsz:d16_state_stress.tsz:50 — <Pressable>
var _arr_5 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(236, 72, 153) } };
// tsz:d16_state_stress.tsz:53 — <Pressable>
var _arr_6 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(20, 184, 166) } };
// tsz:d16_state_stress.tsz:56 — <Pressable>
var _arr_7 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(249, 115, 22) } };
// tsz:d16_state_stress.tsz:34 — <Box>
var _arr_8 = [_]Node{ .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_0 }, .children = &_arr_0 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_1 }, .children = &_arr_1 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_2 }, .children = &_arr_2 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_3 }, .children = &_arr_3 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_4 }, .children = &_arr_4 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_5 }, .children = &_arr_5 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_6 }, .children = &_arr_6 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_7 }, .children = &_arr_7 } };
// tsz:d16_state_stress.tsz:20 — <Box>
var _arr_9 = [_]Node{ .{ .text = "a+b+c+d", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 18, .text_color = Color.rgb(0, 0, 0) } }; // StatBox
// tsz:d16_state_stress.tsz:20 — <Box>
var _arr_10 = [_]Node{ .{ .text = "e+f+g+h", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 18, .text_color = Color.rgb(0, 0, 0) } }; // StatBox
// tsz:d16_state_stress.tsz:20 — <Box>
var _arr_11 = [_]Node{ .{ .text = "total", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 18, .text_color = Color.rgb(0, 0, 0) } }; // StatBox
// tsz:d16_state_stress.tsz:20 — <Box>
var _arr_12 = [_]Node{ .{ .text = "sum", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 18, .text_color = Color.rgb(0, 0, 0) } }; // StatBox
// tsz:d16_state_stress.tsz:62 — <Box>
var _arr_13 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 8, .gap = 2, .flex_grow = 1, .align_items = .center }, .children = &_arr_9 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 8, .gap = 2, .flex_grow = 1, .align_items = .center }, .children = &_arr_10 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 8, .gap = 2, .flex_grow = 1, .align_items = .center }, .children = &_arr_11 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 8, .gap = 2, .flex_grow = 1, .align_items = .center }, .children = &_arr_12 } };
// tsz:d16_state_stress.tsz:71 — <Pressable>
var _arr_14 = [_]Node{ .{ .text = "-", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d16_state_stress.tsz:75 — <Pressable>
var _arr_15 = [_]Node{ .{ .text = "+", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d16_state_stress.tsz:70 — <Box>
var _arr_16 = [_]Node{ .{ .style = .{ .padding = 6, .background_color = Color.rgb(51, 65, 85), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_8 }, .children = &_arr_14 }, .{ .style = .{ .width = 0, .height = 24, .background_color = Color.rgb(59, 130, 246), .border_radius = 4 } }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(51, 65, 85), .border_radius = 4 }, .handlers = .{ .on_press = _handler_press_9 }, .children = &_arr_15 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } };
// tsz:d16_state_stress.tsz:82 — <Pressable>
var _arr_17 = [_]Node{ .{ .text = "", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d16_state_stress.tsz:87 — <Pressable>
var _arr_18 = [_]Node{ .{ .text = "Reset Everything", .font_size = 12, .text_color = Color.rgb(252, 165, 165) } };
// tsz:d16_state_stress.tsz:20 — <Box>
var _arr_19 = [_]Node{ .{ .text = "phase", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 18, .text_color = Color.rgb(0, 0, 0) } }; // StatBox
// tsz:d16_state_stress.tsz:20 — <Box>
var _arr_20 = [_]Node{ .{ .text = "history", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 18, .text_color = Color.rgb(0, 0, 0) } }; // StatBox
// tsz:d16_state_stress.tsz:20 — <Box>
var _arr_21 = [_]Node{ .{ .text = "bar", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 18, .text_color = Color.rgb(0, 0, 0) } }; // StatBox
// tsz:d16_state_stress.tsz:92 — <Box>
var _arr_22 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 8, .gap = 2, .flex_grow = 1, .align_items = .center }, .children = &_arr_19 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 8, .gap = 2, .flex_grow = 1, .align_items = .center }, .children = &_arr_20 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 8, .gap = 2, .flex_grow = 1, .align_items = .center }, .children = &_arr_21 } };
// tsz:d16_state_stress.tsz:29 — <Box>
var _arr_23 = [_]Node{ .{ .text = "State Stress", .font_size = 16, .text_color = Color.rgb(241, 245, 249) }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(71, 85, 105) }, .{ .text = "8 independent counters — state slot pressure", .font_size = 10, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .flex_direction = .row, .gap = 4, .flex_wrap = .wrap }, .children = &_arr_8 }, .{ .text = "Derived state — total should equal a+b+c+d+e+f+g+h", .font_size = 10, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .flex_direction = .row, .gap = 4 }, .children = &_arr_13 }, .{ .text = "State in style — bar width controlled by state", .font_size = 10, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .flex_direction = .row, .gap = 8, .align_items = .center }, .children = &_arr_16 }, .{ .text = "Multi-set in one handler — sets 3 vars atomically", .font_size = 10, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .padding = 10, .background_color = Color.rgb(51, 65, 85), .border_radius = 6 }, .handlers = .{ .on_press = _handler_press_10 }, .children = &_arr_17 }, .{ .text = "Reset all — every counter back to 0", .font_size = 10, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .padding = 10, .background_color = Color.rgb(127, 29, 29), .border_radius = 6, .align_items = .center }, .handlers = .{ .on_press = _handler_press_11 }, .children = &_arr_18 }, .{ .text = "State as component props", .font_size = 10, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .flex_direction = .row, .gap = 4 }, .children = &_arr_22 } };
var _root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(15, 23, 42), .padding = 16, .gap = 10 }, .children = &_arr_23 };

// ── Dynamic text buffers ─────────────────────────────────────────
var _dyn_buf_0: [82]u8 = undefined;
var _dyn_text_0: []const u8 = "";
var _dyn_buf_1: [64]u8 = undefined;
var _dyn_text_1: []const u8 = "";
var _dyn_buf_2: [64]u8 = undefined;
var _dyn_text_2: []const u8 = "";
var _dyn_buf_3: [64]u8 = undefined;
var _dyn_text_3: []const u8 = "";
var _dyn_buf_4: [64]u8 = undefined;
var _dyn_text_4: []const u8 = "";
var _dyn_buf_5: [64]u8 = undefined;
var _dyn_text_5: []const u8 = "";
var _dyn_buf_6: [64]u8 = undefined;
var _dyn_text_6: []const u8 = "";
var _dyn_buf_7: [64]u8 = undefined;
var _dyn_text_7: []const u8 = "";
var _dyn_buf_8: [64]u8 = undefined;
var _dyn_text_8: []const u8 = "";
var _dyn_buf_9: [64]u8 = undefined;
var _dyn_text_9: []const u8 = "";
var _dyn_buf_10: [64]u8 = undefined;
var _dyn_text_10: []const u8 = "";
var _dyn_buf_11: [64]u8 = undefined;
var _dyn_text_11: []const u8 = "";
var _dyn_buf_12: [64]u8 = undefined;
var _dyn_text_12: []const u8 = "";
var _dyn_buf_13: [64]u8 = undefined;
var _dyn_text_13: []const u8 = "";
var _dyn_buf_14: [74]u8 = undefined;
var _dyn_text_14: []const u8 = "";
var _dyn_buf_15: [64]u8 = undefined;
var _dyn_text_15: []const u8 = "";
var _dyn_buf_16: [64]u8 = undefined;
var _dyn_text_16: []const u8 = "";
var _dyn_buf_17: [64]u8 = undefined;
var _dyn_text_17: []const u8 = "";

// ── Event handlers ──────────────────────────────────────────────
fn _handler_press_0() void {
    state.setSlot(0, (state.getSlot(0) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_1() void {
    state.setSlot(1, (state.getSlot(1) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_2() void {
    state.setSlot(2, (state.getSlot(2) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_3() void {
    state.setSlot(3, (state.getSlot(3) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_4() void {
    state.setSlot(4, (state.getSlot(4) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_5() void {
    state.setSlot(5, (state.getSlot(5) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_6() void {
    state.setSlot(6, (state.getSlot(6) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_7() void {
    state.setSlot(7, (state.getSlot(7) + 1));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_8() void {
    state.setSlot(11, (if ((state.getSlot(11) > 10)) (state.getSlot(11) - 10) else @as(i32, 10)));
}

fn _handler_press_9() void {
    state.setSlot(11, (if ((state.getSlot(11) < 300)) (state.getSlot(11) + 10) else @as(i32, 300)));
}

fn _handler_press_10() void {
    state.setSlot(9, (state.getSlot(9) + 1));
    state.setSlot(10, (state.getSlot(10) + state.getSlot(9)));
    state.setSlot(8, (state.getSlot(8) + 1));
}

fn _handler_press_11() void {
    state.setSlot(0, 0);
    state.setSlot(1, 0);
    state.setSlot(2, 0);
    state.setSlot(3, 0);
    state.setSlot(4, 0);
    state.setSlot(5, 0);
    state.setSlot(6, 0);
    state.setSlot(7, 0);
    state.setSlot(8, 0);
    state.setSlot(9, 0);
    state.setSlot(10, 0);
    state.setSlot(11, 50);
}


// ── Embedded JS logic ────────────────────────────────────────
const JS_LOGIC =
    \\
;

// ── Embedded Lua logic ───────────────────────────────────────
const LUA_LOGIC =
    \\
;

fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(50);
}

fn _updateDynamicTexts() void {
    _dyn_text_0 = std.fmt.bufPrint(&_dyn_buf_0, "total:{d} phase:{d} history:{d}", .{ state.getSlot(8), state.getSlot(9), state.getSlot(10) }) catch "";
    _arr_23[1].text = _dyn_text_0;
    _dyn_text_1 = std.fmt.bufPrint(&_dyn_buf_1, "a:{d}", .{ state.getSlot(0) }) catch "";
    _arr_0[0].text = _dyn_text_1;
    _dyn_text_2 = std.fmt.bufPrint(&_dyn_buf_2, "b:{d}", .{ state.getSlot(1) }) catch "";
    _arr_1[0].text = _dyn_text_2;
    _dyn_text_3 = std.fmt.bufPrint(&_dyn_buf_3, "c:{d}", .{ state.getSlot(2) }) catch "";
    _arr_2[0].text = _dyn_text_3;
    _dyn_text_4 = std.fmt.bufPrint(&_dyn_buf_4, "d:{d}", .{ state.getSlot(3) }) catch "";
    _arr_3[0].text = _dyn_text_4;
    _dyn_text_5 = std.fmt.bufPrint(&_dyn_buf_5, "e:{d}", .{ state.getSlot(4) }) catch "";
    _arr_4[0].text = _dyn_text_5;
    _dyn_text_6 = std.fmt.bufPrint(&_dyn_buf_6, "f:{d}", .{ state.getSlot(5) }) catch "";
    _arr_5[0].text = _dyn_text_6;
    _dyn_text_7 = std.fmt.bufPrint(&_dyn_buf_7, "g:{d}", .{ state.getSlot(6) }) catch "";
    _arr_6[0].text = _dyn_text_7;
    _dyn_text_8 = std.fmt.bufPrint(&_dyn_buf_8, "h:{d}", .{ state.getSlot(7) }) catch "";
    _arr_7[0].text = _dyn_text_8;
    _dyn_text_9 = std.fmt.bufPrint(&_dyn_buf_9, "{d}", .{ (((state.getSlot(0) + state.getSlot(1)) + state.getSlot(2)) + state.getSlot(3)) }) catch "";
    _arr_9[1].text = _dyn_text_9;
    _dyn_text_10 = std.fmt.bufPrint(&_dyn_buf_10, "{d}", .{ (((state.getSlot(4) + state.getSlot(5)) + state.getSlot(6)) + state.getSlot(7)) }) catch "";
    _arr_10[1].text = _dyn_text_10;
    _dyn_text_11 = std.fmt.bufPrint(&_dyn_buf_11, "{d}", .{ state.getSlot(8) }) catch "";
    _arr_11[1].text = _dyn_text_11;
    _dyn_text_12 = std.fmt.bufPrint(&_dyn_buf_12, "{d}", .{ (((((((state.getSlot(0) + state.getSlot(1)) + state.getSlot(2)) + state.getSlot(3)) + state.getSlot(4)) + state.getSlot(5)) + state.getSlot(6)) + state.getSlot(7)) }) catch "";
    _arr_12[1].text = _dyn_text_12;
    _dyn_text_13 = std.fmt.bufPrint(&_dyn_buf_13, "{d}px", .{ state.getSlot(11) }) catch "";
    _arr_16[3].text = _dyn_text_13;
    _dyn_text_14 = std.fmt.bufPrint(&_dyn_buf_14, "Phase {d} → phase + 1 (history will be history + phase)", .{ state.getSlot(9) }) catch "";
    _arr_17[0].text = _dyn_text_14;
    _dyn_text_15 = std.fmt.bufPrint(&_dyn_buf_15, "{d}", .{ state.getSlot(9) }) catch "";
    _arr_19[1].text = _dyn_text_15;
    _dyn_text_16 = std.fmt.bufPrint(&_dyn_buf_16, "{d}", .{ state.getSlot(10) }) catch "";
    _arr_20[1].text = _dyn_text_16;
    _dyn_text_17 = std.fmt.bufPrint(&_dyn_buf_17, "{d}", .{ state.getSlot(11) }) catch "";
    _arr_21[1].text = _dyn_text_17;
    _arr_9[1].text_color = Color.rgb(59, 130, 246);
    _arr_10[1].text_color = Color.rgb(139, 92, 246);
    _arr_11[1].text_color = Color.rgb(34, 197, 94);
    _arr_12[1].text_color = Color.rgb(245, 158, 11);
    _arr_16[1].style.width = @as(f32, @floatFromInt(state.getSlot(11)));
    _arr_19[1].text_color = Color.rgb(236, 72, 153);
    _arr_20[1].text_color = Color.rgb(20, 184, 166);
    _arr_21[1].text_color = Color.rgb(249, 115, 22);
}


fn _appInit() void {
    _initState();
    _updateDynamicTexts();
}

fn _appTick(now: u32) void {
    _ = now;
    _updateDynamicTexts();
    if (state.isDirty()) state.clearDirty();
}

export fn app_get_root() *Node { return &_root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d16_state_stress"; }

export fn app_state_count() usize { return 12; }
const _slot_types = [_]u8{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

// Standalone mode — when compiled as an executable directly (skipped in .so builds)
pub fn main() !void {
    if (IS_LIB) return;
    try engine.run(.{
        .title = "d16_state_stress",
        .root = &_root,
        .js_logic = JS_LOGIC,
        .lua_logic = LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}
