//! Generated by tsz compiler (Zig) — do not edit
//!
//! Source: d10_handler_triple_capture.tsz

const std = @import("std");
const build_options = @import("build_options");
const IS_LIB = if (@hasDecl(build_options, "is_lib")) build_options.is_lib else false;

const layout = @import("framework/layout.zig");
const Node = layout.Node;
const Style = layout.Style;
const Color = layout.Color;
const state = @import("framework/state.zig");
const engine = if (IS_LIB) struct {} else @import("framework/engine.zig");
const qjs_runtime = if (IS_LIB) struct {
    pub fn callGlobal(_: []const u8) void {}
    pub fn callGlobalStr(_: []const u8, _: []const u8) void {}
    pub fn callGlobalInt(_: []const u8, _: i64) void {}
    pub fn registerHostFn(_: []const u8, _: ?*const anyopaque, _: u8) void {}
    pub fn evalExpr(_: []const u8) void {}
} else @import("framework/qjs_runtime.zig");

// ── State manifest ──────────────────────────────────────────────
// slot 0: multiplier (int)
// slot 1: accumulator (int)
// slot 2: lastIdx (int)
// slot 3: lastWeight (int)
// slot 4: clickLog (int)
comptime { if (5 != 5) @compileError("state slot count mismatch"); }

// ── Generated node tree ─────────────────────────────────────────
// tsz:d10_handler_triple_capture.tsz:21 — <Pressable>
var _arr_0 = [_]Node{ .{ .text = "", .font_size = 12, .text_color = Color.rgb(254, 243, 199) } };
// tsz:d10_handler_triple_capture.tsz:20 — <Box>
var _arr_1 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(120, 53, 15), .border_radius = 6, .padding = 8 }, .handlers = .{ .lua_on_press = "setMultiplier(multiplier + 1)" }, .children = &_arr_0 }, .{ .text = "", .font_size = 11, .text_color = Color.rgb(120, 113, 108) } };
// tsz:d10_handler_triple_capture.tsz:26 — <ScrollView>
var _arr_2 = [_]Node{ .{} };
// tsz:d10_handler_triple_capture.tsz:18 — <Box>
var _arr_3 = [_]Node{ .{ .text = "Triple Capture", .font_size = 16, .text_color = Color.rgb(250, 250, 249) }, .{ .style = .{ .flex_direction = .row, .gap = 8, .align_items = .center }, .children = &_arr_1 }, .{ .style = .{ .flex_grow = 1 }, .children = &_arr_2 } };
var _root = Node{ .style = .{ .background_color = Color.rgb(12, 10, 9), .padding = 16, .width = -1, .height = -1, .gap = 8 }, .children = &_arr_3 };

// ── Dynamic text buffers ─────────────────────────────────────────
var _dyn_buf_0: [64]u8 = undefined;
var _dyn_text_0: []const u8 = "";
var _dyn_buf_1: [118]u8 = undefined;
var _dyn_text_1: []const u8 = "";
const qjs = if (IS_LIB) struct {
    pub const JSValue = extern struct { tag: i64 = 3, u: extern union { int32: i32, float64: f64, ptr: ?*anyopaque } = .{ .int32 = 0 } };
    pub const JSContext = opaque {};
    pub fn JS_GetPropertyStr(_: ?*const @This().JSContext, _: @This().JSValue, _: [*:0]const u8) @This().JSValue { return .{}; }
    pub fn JS_GetPropertyUint32(_: ?*const @This().JSContext, _: @This().JSValue, _: u32) @This().JSValue { return .{}; }
    pub fn JS_ToInt32(_: ?*const @This().JSContext, _: *i32, _: @This().JSValue) i32 { return 0; }
    pub fn JS_ToInt64(_: ?*const @This().JSContext, _: *i64, _: @This().JSValue) i32 { return 0; }
    pub fn JS_ToFloat64(_: ?*const @This().JSContext, _: *f64, _: @This().JSValue) i32 { return 0; }
    pub fn JS_FreeValue(_: ?*const @This().JSContext, _: @This().JSValue) void {}
    pub fn JS_ToCString(_: ?*const @This().JSContext, _: @This().JSValue) ?[*:0]const u8 { return null; }
    pub fn JS_FreeCString(_: ?*const @This().JSContext, _: ?[*:0]const u8) void {}
    pub fn JS_NewFloat64(_: ?*const @This().JSContext, _: f64) @This().JSValue { return .{}; }
} else @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// ── Object arrays ───────────────────────────────────────────────
const _oa_alloc = std.heap.page_allocator;

fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

var _oa0_label: [][]const u8 = &[_][]const u8{};
var _oa0_label_lens: []usize = &[_]usize{};
var _oa0_label_cap: usize = 0;
var _oa0_weight: []i64 = &[_]i64{};
var _oa0_weight_cap: usize = 0;
var _oa0_category: []i64 = &[_]i64{};
var _oa0_category_cap: usize = 0;
var _oa0_len: usize = 0;
var _oa0_dirty: bool = false;

fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_label_cap) return;
    const new_cap = @max(needed, if (_oa0_label_cap == 0) @as(usize, 64) else _oa0_label_cap * 2);
    if (_oa0_label_cap == 0) {
        _oa0_label = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_label_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_label[_j] = &[_]u8{};
        @memset(_oa0_label_lens, 0);
    } else {
        const _old_cap = _oa0_label_cap;
        _oa0_label = _oa_alloc.realloc(_oa0_label.ptr[0.._old_cap], new_cap) catch return;
        _oa0_label_lens = _oa_alloc.realloc(_oa0_label_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_label[_j] = &[_]u8{};
        @memset(_oa0_label_lens[_old_cap..new_cap], 0);
    }
    _oa0_label_cap = new_cap;
    if (_oa0_weight_cap == 0) {
        _oa0_weight = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_weight, 0);
    } else {
        _oa0_weight = _oa_alloc.realloc(_oa0_weight.ptr[0.._oa0_weight_cap], new_cap) catch return;
        @memset(_oa0_weight[_oa0_weight_cap..new_cap], 0);
    }
    _oa0_weight_cap = new_cap;
    if (_oa0_category_cap == 0) {
        _oa0_category = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_category, 0);
    } else {
        _oa0_category = _oa_alloc.realloc(_oa0_category.ptr[0.._oa0_category_cap], new_cap) catch return;
        @memset(_oa0_category[_oa0_category_cap..new_cap], 0);
    }
    _oa0_category_cap = new_cap;
}

fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "label");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_label[_i], &_oa0_label_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_label[_i] = _oaDupString(sl); _oa0_label_lens[_i] = _oa0_label[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "weight");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_weight[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "category");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_category[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    for (count.._oa0_len) |_trim_i| _oaFreeString(&_oa0_label[_trim_i], &_oa0_label_lens[_trim_i]);
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}


// ── Map pools ───────────────────────────────────────────────────
const MAX_MAP_0: usize = 4096;
var _map_pool_0: [MAX_MAP_0]Node = undefined;
var _map_count_0: usize = 0;
var _map_inner_0: [MAX_MAP_0][2]Node = undefined;
var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_0: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_1: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_3: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_3: [MAX_MAP_0][]const u8 = undefined;
var _map_lua_bufs_0: [MAX_MAP_0][32]u8 = undefined;
var _map_lua_ptrs_0: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
fn _initMapLuaPtrs0() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0[_i][0..31], "__mapPress_0({d})", .{_i}) catch continue;
        _map_lua_bufs_0[_i][n.len] = 0;
        _map_lua_ptrs_0[_i] = @ptrCast(_map_lua_bufs_0[_i][0..n.len :0]);
    }
}
fn _rebuildMap0() void {
    _map_count_0 = @min(_oa0_len, MAX_MAP_0);
    for (0.._map_count_0) |_i| {
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{d}.", .{ @as(i64, @intCast(_i)) }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_0_3[_i] = std.fmt.bufPrint(&_map_text_bufs_0_3[_i], "w:{d}", .{ _oa0_weight[_i] }) catch "";
        _map_inner_0[_i] = [2]Node{ .{ .style = .{ .flex_direction = .row, .gap = 8, .align_items = .center }, .children = &_arr_2 }, .{ .style = .{ .flex_direction = .row, .gap = 12, .align_items = .center }, .children = &_arr_3 } };
        _map_pool_0[_i] = .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center, .padding = 10, .margin_bottom = 4, .border_radius = 6, .background_color = Color.rgb(28, 25, 23) }, .children = &_map_inner_0[_i], .handlers = .{ .lua_on_press = _map_lua_ptrs_0[_i] } };
    }
    _arr_2[0].children = _map_pool_0[0.._map_count_0];
}


// ── Embedded JS logic ────────────────────────────────────────
const JS_LOGIC =
    \\var entries = [];
    \\function setEntries(v) { entries = v; __setObjArr0(v); }
    \\// Populate entries for triple capture test
    \\
    \\var entries = [];
    \\var labels = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter',
    \\              'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Ceres',
    \\              'Eris', 'Haumea', 'Makemake', 'Sedna', 'Quaoar'];
    \\
    \\for (var i = 0; i < 15; i++) {
    \\  entries.push({
    \\    label: labels[i],
    \\    weight: (i + 1) * 3,
    \\    category: i % 3
    \\  });
    \\}
    \\setEntries(entries);
    \\
    \\
    \\
;

// ── Embedded Lua logic ───────────────────────────────────────
const LUA_LOGIC =
    \\-- State variables (mirroring Zig state slots)
    \\local multiplier = 1
    \\local accumulator = 0
    \\local lastIdx = 0
    \\local lastWeight = 0
    \\local clickLog = 0
    \\
    \\function setMultiplier(v) multiplier = v; __setState(0, v) end
    \\function setAccumulator(v) accumulator = v; __setState(1, v) end
    \\function setLastIdx(v) lastIdx = v; __setState(2, v) end
    \\function setLastWeight(v) lastWeight = v; __setState(3, v) end
    \\function setClickLog(v) clickLog = v; __setState(4, v) end
    \\
    \\local entries = {}
    \\function setEntries(v) entries = v; __setObjArr0(v) end
    \\// Populate entries for triple capture test
    \\
    \\local entries = [];
    \\local labels = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter',
    \\              'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Ceres',
    \\              'Eris', 'Haumea', 'Makemake', 'Sedna', 'Quaoar'];
    \\
    \\for (local i = 0; i < 15; i++) {
    \\  entries.push({
    \\    label = labels[i],
    \\    weight = (i + 1) * 3,
    \\    category = i % 3
    \\  });
    \\}
    \\setEntries(entries);
    \\
    \\
    \\function __mapPress_0(idx)
    \\  local entry = entries[idx + 1]
    \\  local idx = idx
    \\  setAccumulator(accumulator + entry.weight * multiplier + idx); setLastIdx(idx); setLastWeight(entry.weight); setClickLog(clickLog + 1)
    \\end
    \\
    \\
;

fn _initState() void {
    _ = state.createSlot(1);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

fn _updateDynamicTexts() void {
    _dyn_text_0 = std.fmt.bufPrint(&_dyn_buf_0, "multiplier: {d}", .{ state.getSlot(0) }) catch "";
    _arr_0[0].text = _dyn_text_0;
    _dyn_text_1 = std.fmt.bufPrint(&_dyn_buf_1, "acc: {d} | lastIdx: {d} | lastW: {d} | clicks: {d}", .{ state.getSlot(1), state.getSlot(2), state.getSlot(3), state.getSlot(4) }) catch "";
    _arr_1[1].text = _dyn_text_1;
}


fn _appInit() void {
    _initState();
    qjs_runtime.registerHostFn("__setObjArr0", @ptrCast(&_oa0_unpack), 1);
    _updateDynamicTexts();
    _initMapLuaPtrs0();
    _rebuildMap0();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts();
        _rebuildMap0();
 state.clearDirty(); }
}

export fn app_get_root() *Node { return &_root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d10_handler_triple_capture"; }

export fn app_state_count() usize { return 5; }
const _slot_types = [_]u8{ 0, 0, 0, 0, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

// Standalone mode — when compiled as an executable directly (skipped in .so builds)
pub fn main() !void {
    if (IS_LIB) return;
    try engine.run(.{
        .title = "d10_handler_triple_capture",
        .root = &_root,
        .js_logic = JS_LOGIC,
        .lua_logic = LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}
