//! Generated by tsz compiler (Zig) — do not edit
//!
//! Source: d11_map_component_map.tsz

const std = @import("std");
const build_options = @import("build_options");
const IS_LIB = if (@hasDecl(build_options, "is_lib")) build_options.is_lib else false;

const layout = @import("framework/layout.zig");
const Node = layout.Node;
const Style = layout.Style;
const Color = layout.Color;
const state = @import("framework/state.zig");
const engine = if (IS_LIB) struct {} else @import("framework/engine.zig");
const qjs_runtime = if (IS_LIB) struct {
    pub fn callGlobal(_: []const u8) void {}
    pub fn callGlobalStr(_: []const u8, _: []const u8) void {}
    pub fn callGlobalInt(_: []const u8, _: i64) void {}
    pub fn registerHostFn(_: []const u8, _: ?*const anyopaque, _: u8) void {}
    pub fn evalExpr(_: []const u8) void {}
} else @import("framework/qjs_runtime.zig");

// ── State manifest ──────────────────────────────────────────────
// slot 0: selectedDept (int)
// slot 1: selectedEmp (int)
// slot 2: totalClicks (int)
comptime { if (3 != 3) @compileError("state slot count mismatch"); }

// ── Generated node tree ─────────────────────────────────────────
// tsz:d11_map_component_map.tsz:18 — <Box>
var _arr_3 = [_]Node{ .{ .style = .{ .gap = 2 } } }; // EmployeeList
// tsz:d11_map_component_map.tsz:40 — <ScrollView>
var _arr_0 = [_]Node{ .{} };
// tsz:d11_map_component_map.tsz:37 — <Box>
var _arr_1 = [_]Node{ .{ .text = "Org Chart", .font_size = 16, .text_color = Color.rgb(248, 250, 252) }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(71, 85, 105) }, .{ .style = .{ .flex_grow = 1 }, .children = &_arr_0 } };
var _root = Node{ .style = .{ .background_color = Color.rgb(2, 6, 23), .padding = 16, .width = -1, .height = -1, .gap = 8 }, .children = &_arr_1 };

// ── Dynamic text buffers ─────────────────────────────────────────
var _dyn_buf_0: [85]u8 = undefined;
var _dyn_text_0: []const u8 = "";
const qjs = if (IS_LIB) struct {
    pub const JSValue = extern struct { tag: i64 = 3, u: extern union { int32: i32, float64: f64, ptr: ?*anyopaque } = .{ .int32 = 0 } };
    pub const JSContext = opaque {};
    pub fn JS_GetPropertyStr(_: ?*const @This().JSContext, _: @This().JSValue, _: [*:0]const u8) @This().JSValue { return .{}; }
    pub fn JS_GetPropertyUint32(_: ?*const @This().JSContext, _: @This().JSValue, _: u32) @This().JSValue { return .{}; }
    pub fn JS_ToInt32(_: ?*const @This().JSContext, _: *i32, _: @This().JSValue) i32 { return 0; }
    pub fn JS_ToInt64(_: ?*const @This().JSContext, _: *i64, _: @This().JSValue) i32 { return 0; }
    pub fn JS_ToFloat64(_: ?*const @This().JSContext, _: *f64, _: @This().JSValue) i32 { return 0; }
    pub fn JS_FreeValue(_: ?*const @This().JSContext, _: @This().JSValue) void {}
    pub fn JS_ToCString(_: ?*const @This().JSContext, _: @This().JSValue) ?[*:0]const u8 { return null; }
    pub fn JS_FreeCString(_: ?*const @This().JSContext, _: ?[*:0]const u8) void {}
    pub fn JS_NewFloat64(_: ?*const @This().JSContext, _: f64) @This().JSValue { return .{}; }
} else @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// ── Object arrays ───────────────────────────────────────────────
const _oa_alloc = std.heap.page_allocator;

fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

var _oa0_name: [][]const u8 = &[_][]const u8{};
var _oa0_name_lens: []usize = &[_]usize{};
var _oa0_name_cap: usize = 0;
var _oa0_headcount: []i64 = &[_]i64{};
var _oa0_headcount_cap: usize = 0;
var _oa0_budget: []i64 = &[_]i64{};
var _oa0_budget_cap: usize = 0;
var _oa0_len: usize = 0;
var _oa0_dirty: bool = false;

fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_name_cap) return;
    const new_cap = @max(needed, if (_oa0_name_cap == 0) @as(usize, 64) else _oa0_name_cap * 2);
    if (_oa0_name_cap == 0) {
        _oa0_name = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_name_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens, 0);
    } else {
        const _old_cap = _oa0_name_cap;
        _oa0_name = _oa_alloc.realloc(_oa0_name.ptr[0.._old_cap], new_cap) catch return;
        _oa0_name_lens = _oa_alloc.realloc(_oa0_name_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens[_old_cap..new_cap], 0);
    }
    _oa0_name_cap = new_cap;
    if (_oa0_headcount_cap == 0) {
        _oa0_headcount = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_headcount, 0);
    } else {
        _oa0_headcount = _oa_alloc.realloc(_oa0_headcount.ptr[0.._oa0_headcount_cap], new_cap) catch return;
        @memset(_oa0_headcount[_oa0_headcount_cap..new_cap], 0);
    }
    _oa0_headcount_cap = new_cap;
    if (_oa0_budget_cap == 0) {
        _oa0_budget = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_budget, 0);
    } else {
        _oa0_budget = _oa_alloc.realloc(_oa0_budget.ptr[0.._oa0_budget_cap], new_cap) catch return;
        @memset(_oa0_budget[_oa0_budget_cap..new_cap], 0);
    }
    _oa0_budget_cap = new_cap;
}

fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "name");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_name[_i], &_oa0_name_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_name[_i] = _oaDupString(sl); _oa0_name_lens[_i] = _oa0_name[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "headcount");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_headcount[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "budget");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_budget[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    for (count.._oa0_len) |_trim_i| _oaFreeString(&_oa0_name[_trim_i], &_oa0_name_lens[_trim_i]);
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

var _oa1_empName: [][]const u8 = &[_][]const u8{};
var _oa1_empName_lens: []usize = &[_]usize{};
var _oa1_empName_cap: usize = 0;
var _oa1_deptIdx: []i64 = &[_]i64{};
var _oa1_deptIdx_cap: usize = 0;
var _oa1_salary: []i64 = &[_]i64{};
var _oa1_salary_cap: usize = 0;
var _oa1_active: []i64 = &[_]i64{};
var _oa1_active_cap: usize = 0;
var _oa1_len: usize = 0;
var _oa1_dirty: bool = false;

fn _oa1_ensureCapacity(needed: usize) void {
    if (needed <= _oa1_empName_cap) return;
    const new_cap = @max(needed, if (_oa1_empName_cap == 0) @as(usize, 64) else _oa1_empName_cap * 2);
    if (_oa1_empName_cap == 0) {
        _oa1_empName = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_empName_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_empName[_j] = &[_]u8{};
        @memset(_oa1_empName_lens, 0);
    } else {
        const _old_cap = _oa1_empName_cap;
        _oa1_empName = _oa_alloc.realloc(_oa1_empName.ptr[0.._old_cap], new_cap) catch return;
        _oa1_empName_lens = _oa_alloc.realloc(_oa1_empName_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_empName[_j] = &[_]u8{};
        @memset(_oa1_empName_lens[_old_cap..new_cap], 0);
    }
    _oa1_empName_cap = new_cap;
    if (_oa1_deptIdx_cap == 0) {
        _oa1_deptIdx = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_deptIdx, 0);
    } else {
        _oa1_deptIdx = _oa_alloc.realloc(_oa1_deptIdx.ptr[0.._oa1_deptIdx_cap], new_cap) catch return;
        @memset(_oa1_deptIdx[_oa1_deptIdx_cap..new_cap], 0);
    }
    _oa1_deptIdx_cap = new_cap;
    if (_oa1_salary_cap == 0) {
        _oa1_salary = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_salary, 0);
    } else {
        _oa1_salary = _oa_alloc.realloc(_oa1_salary.ptr[0.._oa1_salary_cap], new_cap) catch return;
        @memset(_oa1_salary[_oa1_salary_cap..new_cap], 0);
    }
    _oa1_salary_cap = new_cap;
    if (_oa1_active_cap == 0) {
        _oa1_active = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_active, 0);
    } else {
        _oa1_active = _oa_alloc.realloc(_oa1_active.ptr[0.._oa1_active_cap], new_cap) catch return;
        @memset(_oa1_active[_oa1_active_cap..new_cap], 0);
    }
    _oa1_active_cap = new_cap;
}

fn _oa1_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa1_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "empName");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_empName[_i], &_oa1_empName_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_empName[_i] = _oaDupString(sl); _oa1_empName_lens[_i] = _oa1_empName[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "deptIdx");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_deptIdx[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "salary");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_salary[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "active");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_active[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    for (count.._oa1_len) |_trim_i| _oaFreeString(&_oa1_empName[_trim_i], &_oa1_empName_lens[_trim_i]);
    _oa1_len = count;
    _oa1_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}


// ── Map pools ───────────────────────────────────────────────────
const MAX_MAP_0: usize = 4096;
var _map_pool_0: [MAX_MAP_0]Node = undefined;
var _map_count_0: usize = 0;
var _map_inner_0: [MAX_MAP_0][1]Node = undefined;
var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_0: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_1: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_2: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_2: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_1: [MAX_MAP_0][]const u8 = undefined;
var _map_lua_bufs_0: [MAX_MAP_0][32]u8 = undefined;
var _map_lua_ptrs_0: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
fn _initMapLuaPtrs0() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0[_i][0..31], "__mapPress_0({d})", .{_i}) catch continue;
        _map_lua_bufs_0[_i][n.len] = 0;
        _map_lua_ptrs_0[_i] = @ptrCast(_map_lua_bufs_0[_i][0..n.len :0]);
    }
}
fn _rebuildMap0() void {
    _map_count_0 = @min(_oa1_len, MAX_MAP_0);
    for (0.._map_count_0) |_i| {
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ _oa0_name[_i][0.._oa0_name_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{d} people | ${d}k budget", .{ _oa0_headcount[_i], _oa0_budget[_i] }) catch "";
        _map_texts_0_2[_i] = std.fmt.bufPrint(&_map_text_bufs_0_2[_i], "{s}", .{ _oa1_empName[_i][0.._oa1_empName_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "${d}", .{ _oa1_salary[_i] }) catch "";
        _map_inner_0[_i] = [1]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .padding = 6, .border_radius = 4, .background_color = Color.rgb(30, 41, 59) }, .handlers = .{ .lua_on_press = "setSelectedEmp(ei); setTotalClicks(totalClicks + 1)" }, .children = &_arr_4 } };
        _map_pool_0[_i] = .{ .children = &_map_inner_0[_i] };
    }
    _arr_0[0].children = _map_pool_0[0.._map_count_0];
}

const MAX_MAP_1: usize = 4096;
var _map_pool_1: [MAX_MAP_1]Node = undefined;
var _map_count_1: usize = 0;
var _map_inner_1: [MAX_MAP_1][2]Node = undefined;
var _map_text_bufs_1_0: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_0: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_1: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_1: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_2: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_2: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_1: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_1: [MAX_MAP_1][]const u8 = undefined;
fn _rebuildMap1() void {
    _map_count_1 = @min(_oa0_len, MAX_MAP_1);
    for (0.._map_count_1) |_i| {
        _map_texts_1_0[_i] = std.fmt.bufPrint(&_map_text_bufs_1_0[_i], "{s}", .{ _oa0_name[_i][0.._oa0_name_lens[_i]] }) catch "";
        _map_texts_1_1[_i] = std.fmt.bufPrint(&_map_text_bufs_1_1[_i], "{d} people | ${d}k budget", .{ _oa0_headcount[_i], _oa0_budget[_i] }) catch "";
        _map_texts_1_2[_i] = std.fmt.bufPrint(&_map_text_bufs_1_2[_i], "{s}", .{ _oa1_empName[_i][0.._oa1_empName_lens[_i]] }) catch "";
        _map_texts_1_1[_i] = std.fmt.bufPrint(&_map_text_bufs_1_1[_i], "${d}", .{ _oa1_salary[_i] }) catch "";
        _map_inner_1[_i] = [2]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center, .padding = 10, .background_color = Color.rgb(15, 23, 42), .border_radius = 8 }, .handlers = .{ .lua_on_press = "setSelectedDept(di); setTotalClicks(totalClicks + 1)" }, .children = &_arr_2 }, .{ .style = .{ .gap = 2, .padding_left = 12 }, .children = &_arr_3 } };
        _map_pool_1[_i] = .{ .style = .{ .margin_bottom = 12 }, .children = &_map_inner_1[_i] };
    }
}


// ── Embedded JS logic ────────────────────────────────────────
const JS_LOGIC =
    \\var departments = [];
    \\function setDepartments(v) { departments = v; __setObjArr0(v); }
    \\var employees = [];
    \\function setEmployees(v) { employees = v; __setObjArr1(v); }
    \\// Populate departments and employees for map→component→map test
    \\
    \\var depts = [
    \\  { name: 'Engineering', headcount: 8, budget: 450 },
    \\  { name: 'Design', headcount: 4, budget: 200 },
    \\  { name: 'Marketing', headcount: 5, budget: 300 },
    \\  { name: 'Sales', headcount: 6, budget: 350 },
    \\  { name: 'Operations', headcount: 3, budget: 150 }
    \\];
    \\setDepartments(depts);
    \\
    \\var emps = [
    \\  { empName: 'Alice', deptIdx: 0, salary: 120, active: 1 },
    \\  { empName: 'Bob', deptIdx: 0, salary: 115, active: 1 },
    \\  { empName: 'Carol', deptIdx: 0, salary: 130, active: 1 },
    \\  { empName: 'Dave', deptIdx: 0, salary: 95, active: 0 },
    \\  { empName: 'Eve', deptIdx: 1, salary: 105, active: 1 },
    \\  { empName: 'Frank', deptIdx: 1, salary: 110, active: 1 },
    \\  { empName: 'Grace', deptIdx: 2, salary: 90, active: 1 },
    \\  { empName: 'Heidi', deptIdx: 2, salary: 85, active: 0 },
    \\  { empName: 'Ivan', deptIdx: 2, salary: 95, active: 1 },
    \\  { empName: 'Judy', deptIdx: 3, salary: 100, active: 1 },
    \\  { empName: 'Karl', deptIdx: 3, salary: 110, active: 1 },
    \\  { empName: 'Luna', deptIdx: 3, salary: 88, active: 0 },
    \\  { empName: 'Mike', deptIdx: 4, salary: 92, active: 1 },
    \\  { empName: 'Nina', deptIdx: 4, salary: 98, active: 1 }
    \\];
    \\setEmployees(emps);
    \\
    \\
    \\
;

// ── Embedded Lua logic ───────────────────────────────────────
const LUA_LOGIC =
    \\-- State variables (mirroring Zig state slots)
    \\local selectedDept = 0
    \\local selectedEmp = 0
    \\local totalClicks = 0
    \\
    \\function setSelectedDept(v) selectedDept = v; __setState(0, v) end
    \\function setSelectedEmp(v) selectedEmp = v; __setState(1, v) end
    \\function setTotalClicks(v) totalClicks = v; __setState(2, v) end
    \\
    \\local departments = {}
    \\function setDepartments(v) departments = v; __setObjArr0(v) end
    \\local employees = {}
    \\function setEmployees(v) employees = v; __setObjArr1(v) end
    \\// Populate departments and employees for map→component→map test
    \\
    \\local depts = {
    \\  { name = 'Engineering', headcount = 8, budget = 450 },
    \\  { name = 'Design', headcount = 4, budget = 200 },
    \\  { name = 'Marketing', headcount = 5, budget = 300 },
    \\  { name = 'Sales', headcount = 6, budget = 350 },
    \\  { name = 'Operations', headcount = 3, budget = 150 }
    \\}
    \\setDepartments(depts);
    \\
    \\local emps = {
    \\  { empName = 'Alice', deptIdx = 0, salary = 120, active = 1 },
    \\  { empName = 'Bob', deptIdx = 0, salary = 115, active = 1 },
    \\  { empName = 'Carol', deptIdx = 0, salary = 130, active = 1 },
    \\  { empName = 'Dave', deptIdx = 0, salary = 95, active = 0 },
    \\  { empName = 'Eve', deptIdx = 1, salary = 105, active = 1 },
    \\  { empName = 'Frank', deptIdx = 1, salary = 110, active = 1 },
    \\  { empName = 'Grace', deptIdx = 2, salary = 90, active = 1 },
    \\  { empName = 'Heidi', deptIdx = 2, salary = 85, active = 0 },
    \\  { empName = 'Ivan', deptIdx = 2, salary = 95, active = 1 },
    \\  { empName = 'Judy', deptIdx = 3, salary = 100, active = 1 },
    \\  { empName = 'Karl', deptIdx = 3, salary = 110, active = 1 },
    \\  { empName = 'Luna', deptIdx = 3, salary = 88, active = 0 },
    \\  { empName = 'Mike', deptIdx = 4, salary = 92, active = 1 },
    \\  { empName = 'Nina', deptIdx = 4, salary = 98, active = 1 }
    \\}
    \\setEmployees(emps);
    \\
    \\
    \\function __mapPress_0(idx)
    \\  local emp = employees[idx + 1]
    \\  local ei = idx
    \\  setSelectedDept(di); setTotalClicks(totalClicks + 1)
    \\end
    \\
    \\function __mapPress_0(idx)
    \\  local emp = employees[idx + 1]
    \\  local ei = idx
    \\  setSelectedEmp(ei); setTotalClicks(totalClicks + 1)
    \\end
    \\
    \\
;

fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

fn _updateDynamicTexts() void {
    _dyn_text_0 = std.fmt.bufPrint(&_dyn_buf_0, "dept: {d} | emp: {d} | clicks: {d}", .{ state.getSlot(0), state.getSlot(1), state.getSlot(2) }) catch "";
    _arr_1[1].text = _dyn_text_0;
}

fn _updateConditionals() void {
    _arr_1[0].style.display = if ((state.getSlot(0) == di)) .flex else .none;
    _arr_1[1].style.display = if ((state.getSlot(0) != di)) .flex else .none;
    _arr_5[0].style.display = if ((emp.deptIdx == deptIdx)) .flex else .none;
}


fn _appInit() void {
    _initState();
    qjs_runtime.registerHostFn("__setObjArr0", @ptrCast(&_oa0_unpack), 1);
    qjs_runtime.registerHostFn("__setObjArr1", @ptrCast(&_oa1_unpack), 1);
    _updateDynamicTexts();
    _updateConditionals();
    _initMapLuaPtrs0();
    _rebuildMap0();
    _rebuildMap1();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts(); _updateConditionals();
        _rebuildMap0();
        _rebuildMap1();
 state.clearDirty(); }
}

export fn app_get_root() *Node { return &_root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d11_map_component_map"; }

export fn app_state_count() usize { return 3; }
const _slot_types = [_]u8{ 0, 0, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

// Standalone mode — when compiled as an executable directly (skipped in .so builds)
pub fn main() !void {
    if (IS_LIB) return;
    try engine.run(.{
        .title = "d11_map_component_map",
        .root = &_root,
        .js_logic = JS_LOGIC,
        .lua_logic = LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}
