//! Generated by tsz compiler (Zig) — do not edit
//!
//! Source: d13_schema_form.tsz

const std = @import("std");
const build_options = @import("build_options");
const IS_LIB = if (@hasDecl(build_options, "is_lib")) build_options.is_lib else false;

const layout = @import("framework/layout.zig");
const Node = layout.Node;
const Style = layout.Style;
const Color = layout.Color;
const state = @import("framework/state.zig");
const engine = if (IS_LIB) struct {} else @import("framework/engine.zig");
const qjs_runtime = if (IS_LIB) struct {
    pub fn callGlobal(_: []const u8) void {}
    pub fn callGlobalStr(_: []const u8, _: []const u8) void {}
    pub fn callGlobalInt(_: []const u8, _: i64) void {}
    pub fn registerHostFn(_: []const u8, _: ?*const anyopaque, _: u8) void {}
    pub fn evalExpr(_: []const u8) void {}
} else @import("framework/qjs_runtime.zig");

// ── State manifest ──────────────────────────────────────────────
// slot 0: activeSection (int)
// slot 1: editCount (int)
// slot 2: lastEdited (int)
// slot 3: formDirty (int)
// slot 4: validationErrors (int)
comptime { if (5 != 5) @compileError("state slot count mismatch"); }

// ── Generated node tree ─────────────────────────────────────────
// tsz:d13_schema_form.tsz:91 — <Box>
var _arr_0 = [_]Node{ .{ .text = "Settings", .font_size = 14, .text_color = Color.rgb(249, 250, 251) }, .{ .style = .{ .height = 8 } }, .{ .style = .{ .gap = 4 } }, .{ .style = .{ .flex_grow = 1 } }, .{ .text = "Unsaved changes", .font_size = 9, .text_color = Color.rgb(245, 158, 11) }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(239, 68, 68) }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(107, 114, 128) } };
// tsz:d13_schema_form.tsz:113 — <Pressable>
var _arr_1 = [_]Node{ .{ .text = "Save", .font_size = 11, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d13_schema_form.tsz:116 — <Box>
var _arr_2 = [_]Node{ .{ .text = "", .font_size = 11, .text_color = Color.rgb(252, 165, 165) } };
// tsz:d13_schema_form.tsz:112 — <Box>
var _arr_3 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(59, 130, 246), .border_radius = 6, .padding = 8, .padding_left = 16, .padding_right = 16 }, .handlers = .{ .lua_on_press = "setFormDirty(0); setEditCount(editCount + 1); setValidationErrors(0)" }, .children = &_arr_1 }, .{ .style = .{ .background_color = Color.rgb(127, 29, 29), .border_radius = 6, .padding = 8 }, .children = &_arr_2 } };
// tsz:d13_schema_form.tsz:110 — <Box>
var _arr_4 = [_]Node{ .{ .text = "Form Builder", .font_size = 18, .text_color = Color.rgb(249, 250, 251) }, .{ .style = .{ .flex_direction = .row, .gap = 8 }, .children = &_arr_3 } };
// tsz:d13_schema_form.tsz:122 — <ScrollView>
var _arr_5 = [_]Node{ .{} };
// tsz:d13_schema_form.tsz:109 — <Box>
var _arr_6 = [_]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center }, .children = &_arr_4 }, .{ .style = .{ .flex_grow = 1 }, .children = &_arr_5 } };
// tsz:d13_schema_form.tsz:90 — <Box>
var _arr_7 = [_]Node{ .{ .style = .{ .width = 180, .background_color = Color.rgb(31, 41, 55), .padding = 12, .gap = 4, .border_color = Color.rgb(55, 65, 81), .border_width = 1 }, .children = &_arr_0 }, .{ .style = .{ .flex_grow = 1, .padding = 20, .gap = 16 }, .children = &_arr_6 } };
var _root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(17, 24, 39), .flex_direction = .row }, .children = &_arr_7 };

// ── Dynamic text buffers ─────────────────────────────────────────
var _dyn_buf_0: [64]u8 = undefined;
var _dyn_text_0: []const u8 = "";
var _dyn_buf_1: [64]u8 = undefined;
var _dyn_text_1: []const u8 = "";
var _dyn_buf_2: [64]u8 = undefined;
var _dyn_text_2: []const u8 = "";
var _dyn_buf_3: [70]u8 = undefined;
var _dyn_text_3: []const u8 = "";
var _dyn_buf_4: [64]u8 = undefined;
var _dyn_text_4: []const u8 = "";
const qjs = if (IS_LIB) struct {
    pub const JSValue = extern struct { tag: i64 = 3, u: extern union { int32: i32, float64: f64, ptr: ?*anyopaque } = .{ .int32 = 0 } };
    pub const JSContext = opaque {};
    pub fn JS_GetPropertyStr(_: ?*const @This().JSContext, _: @This().JSValue, _: [*:0]const u8) @This().JSValue { return .{}; }
    pub fn JS_GetPropertyUint32(_: ?*const @This().JSContext, _: @This().JSValue, _: u32) @This().JSValue { return .{}; }
    pub fn JS_ToInt32(_: ?*const @This().JSContext, _: *i32, _: @This().JSValue) i32 { return 0; }
    pub fn JS_ToInt64(_: ?*const @This().JSContext, _: *i64, _: @This().JSValue) i32 { return 0; }
    pub fn JS_ToFloat64(_: ?*const @This().JSContext, _: *f64, _: @This().JSValue) i32 { return 0; }
    pub fn JS_FreeValue(_: ?*const @This().JSContext, _: @This().JSValue) void {}
    pub fn JS_ToCString(_: ?*const @This().JSContext, _: @This().JSValue) ?[*:0]const u8 { return null; }
    pub fn JS_FreeCString(_: ?*const @This().JSContext, _: ?[*:0]const u8) void {}
    pub fn JS_NewFloat64(_: ?*const @This().JSContext, _: f64) @This().JSValue { return .{}; }
} else @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// ── Object arrays ───────────────────────────────────────────────
const _oa_alloc = std.heap.page_allocator;

fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

var _oa0_label: [][]const u8 = &[_][]const u8{};
var _oa0_label_lens: []usize = &[_]usize{};
var _oa0_label_cap: usize = 0;
var _oa0_icon: [][]const u8 = &[_][]const u8{};
var _oa0_icon_lens: []usize = &[_]usize{};
var _oa0_icon_cap: usize = 0;
var _oa0_len: usize = 0;
var _oa0_dirty: bool = false;

fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_label_cap) return;
    const new_cap = @max(needed, if (_oa0_label_cap == 0) @as(usize, 64) else _oa0_label_cap * 2);
    if (_oa0_label_cap == 0) {
        _oa0_label = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_label_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_label[_j] = &[_]u8{};
        @memset(_oa0_label_lens, 0);
    } else {
        const _old_cap = _oa0_label_cap;
        _oa0_label = _oa_alloc.realloc(_oa0_label.ptr[0.._old_cap], new_cap) catch return;
        _oa0_label_lens = _oa_alloc.realloc(_oa0_label_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_label[_j] = &[_]u8{};
        @memset(_oa0_label_lens[_old_cap..new_cap], 0);
    }
    _oa0_label_cap = new_cap;
    if (_oa0_icon_cap == 0) {
        _oa0_icon = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_icon_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_icon[_j] = &[_]u8{};
        @memset(_oa0_icon_lens, 0);
    } else {
        const _old_cap = _oa0_icon_cap;
        _oa0_icon = _oa_alloc.realloc(_oa0_icon.ptr[0.._old_cap], new_cap) catch return;
        _oa0_icon_lens = _oa_alloc.realloc(_oa0_icon_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_icon[_j] = &[_]u8{};
        @memset(_oa0_icon_lens[_old_cap..new_cap], 0);
    }
    _oa0_icon_cap = new_cap;
}

fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "label");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_label[_i], &_oa0_label_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_label[_i] = _oaDupString(sl); _oa0_label_lens[_i] = _oa0_label[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "icon");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_icon[_i], &_oa0_icon_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_icon[_i] = _oaDupString(sl); _oa0_icon_lens[_i] = _oa0_icon[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        qjs.JS_FreeValue(c2, elem);
    }
    for (count.._oa0_len) |_trim_i| _oaFreeString(&_oa0_label[_trim_i], &_oa0_label_lens[_trim_i]); _oaFreeString(&_oa0_icon[_trim_i], &_oa0_icon_lens[_trim_i]);
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

var _oa1_label: [][]const u8 = &[_][]const u8{};
var _oa1_label_lens: []usize = &[_]usize{};
var _oa1_label_cap: usize = 0;
var _oa1_type: []i64 = &[_]i64{};
var _oa1_type_cap: usize = 0;
var _oa1_sectionIdx: []i64 = &[_]i64{};
var _oa1_sectionIdx_cap: usize = 0;
var _oa1_value: []i64 = &[_]i64{};
var _oa1_value_cap: usize = 0;
var _oa1_placeholder: [][]const u8 = &[_][]const u8{};
var _oa1_placeholder_lens: []usize = &[_]usize{};
var _oa1_placeholder_cap: usize = 0;
var _oa1_len: usize = 0;
var _oa1_dirty: bool = false;

fn _oa1_ensureCapacity(needed: usize) void {
    if (needed <= _oa1_label_cap) return;
    const new_cap = @max(needed, if (_oa1_label_cap == 0) @as(usize, 64) else _oa1_label_cap * 2);
    if (_oa1_label_cap == 0) {
        _oa1_label = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_label_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_label[_j] = &[_]u8{};
        @memset(_oa1_label_lens, 0);
    } else {
        const _old_cap = _oa1_label_cap;
        _oa1_label = _oa_alloc.realloc(_oa1_label.ptr[0.._old_cap], new_cap) catch return;
        _oa1_label_lens = _oa_alloc.realloc(_oa1_label_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_label[_j] = &[_]u8{};
        @memset(_oa1_label_lens[_old_cap..new_cap], 0);
    }
    _oa1_label_cap = new_cap;
    if (_oa1_type_cap == 0) {
        _oa1_type = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_type, 0);
    } else {
        _oa1_type = _oa_alloc.realloc(_oa1_type.ptr[0.._oa1_type_cap], new_cap) catch return;
        @memset(_oa1_type[_oa1_type_cap..new_cap], 0);
    }
    _oa1_type_cap = new_cap;
    if (_oa1_sectionIdx_cap == 0) {
        _oa1_sectionIdx = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_sectionIdx, 0);
    } else {
        _oa1_sectionIdx = _oa_alloc.realloc(_oa1_sectionIdx.ptr[0.._oa1_sectionIdx_cap], new_cap) catch return;
        @memset(_oa1_sectionIdx[_oa1_sectionIdx_cap..new_cap], 0);
    }
    _oa1_sectionIdx_cap = new_cap;
    if (_oa1_value_cap == 0) {
        _oa1_value = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_value, 0);
    } else {
        _oa1_value = _oa_alloc.realloc(_oa1_value.ptr[0.._oa1_value_cap], new_cap) catch return;
        @memset(_oa1_value[_oa1_value_cap..new_cap], 0);
    }
    _oa1_value_cap = new_cap;
    if (_oa1_placeholder_cap == 0) {
        _oa1_placeholder = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_placeholder_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_placeholder[_j] = &[_]u8{};
        @memset(_oa1_placeholder_lens, 0);
    } else {
        const _old_cap = _oa1_placeholder_cap;
        _oa1_placeholder = _oa_alloc.realloc(_oa1_placeholder.ptr[0.._old_cap], new_cap) catch return;
        _oa1_placeholder_lens = _oa_alloc.realloc(_oa1_placeholder_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_placeholder[_j] = &[_]u8{};
        @memset(_oa1_placeholder_lens[_old_cap..new_cap], 0);
    }
    _oa1_placeholder_cap = new_cap;
}

fn _oa1_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa1_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "label");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_label[_i], &_oa1_label_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_label[_i] = _oaDupString(sl); _oa1_label_lens[_i] = _oa1_label[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "type");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_type[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "sectionIdx");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_sectionIdx[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "value");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_value[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "placeholder");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_placeholder[_i], &_oa1_placeholder_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_placeholder[_i] = _oaDupString(sl); _oa1_placeholder_lens[_i] = _oa1_placeholder[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        qjs.JS_FreeValue(c2, elem);
    }
    for (count.._oa1_len) |_trim_i| _oaFreeString(&_oa1_label[_trim_i], &_oa1_label_lens[_trim_i]); _oaFreeString(&_oa1_placeholder[_trim_i], &_oa1_placeholder_lens[_trim_i]);
    _oa1_len = count;
    _oa1_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}


// ── Map pools ───────────────────────────────────────────────────
const MAX_MAP_0: usize = 4096;
var _map_pool_0: [MAX_MAP_0]Node = undefined;
var _map_count_0: usize = 0;
var _map_inner_0: [MAX_MAP_0][5]Node = undefined;
var _map_text_bufs_0_2: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_2: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_0: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_0: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_0: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_1: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_3: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_3: [MAX_MAP_0][]const u8 = undefined;
var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0_1: [MAX_MAP_0][]const u8 = undefined;
var _map_lua_bufs_0: [MAX_MAP_0][32]u8 = undefined;
var _map_lua_ptrs_0: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
fn _initMapLuaPtrs0() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0[_i][0..31], "__mapPress_0({d})", .{_i}) catch continue;
        _map_lua_bufs_0[_i][n.len] = 0;
        _map_lua_ptrs_0[_i] = @ptrCast(_map_lua_bufs_0[_i][0..n.len :0]);
    }
}
fn _rebuildMap0() void {
    _map_count_0 = @min(_oa0_len, MAX_MAP_0);
    for (0.._map_count_0) |_i| {
        _map_texts_0_2[_i] = std.fmt.bufPrint(&_map_text_bufs_0_2[_i], "{s}", .{ _oa0_icon[_i][0.._oa0_icon_lens[_i]] }) catch "";
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ _oa0_icon[_i][0.._oa0_icon_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_0_3[_i] = std.fmt.bufPrint(&_map_text_bufs_0_3[_i], "{s}:{d} / edits:{d} / dirty:{d}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]], @as(i64, @intCast(_i)), state.getSlot(1), state.getSlot(3) }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{s}", .{ "_oa1_value[_i]" }) catch "";
        _map_inner_0[_i] = [5]Node{ .{ .style = .{ .width = 3, .height = 16, .border_radius = 2, .background_color = Color.rgb(59, 130, 246) } }, .{ .style = .{ .width = 3, .height = 16 } }, .{ .text = _map_texts_0_2[_i], .font_size = 11, .text_color = Color.rgb(229, 231, 235) }, .{ .text = _map_texts_0_0[_i], .font_size = 12, .text_color = Color.rgb(249, 250, 251) }, .{ .text = _map_texts_0_0[_i], .font_size = 12, .text_color = Color.rgb(156, 163, 175) } };
        _map_pool_0[_i] = .{ .style = .{ .flex_direction = .row, .gap = 8, .padding = 8, .border_radius = 6, .align_items = .center }, .children = &_map_inner_0[_i], .handlers = .{ .lua_on_press = _map_lua_ptrs_0[_i] } };
    }
    _arr_0[2].children = _map_pool_0[0.._map_count_0];
}

const MAX_MAP_1: usize = 4096;
var _map_pool_1: [MAX_MAP_1]Node = undefined;
var _map_count_1: usize = 0;
var _map_inner_1: [MAX_MAP_1][1]Node = undefined;
var _map_text_bufs_1_2: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_2: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_0: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_0: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_0: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_0: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_0: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_0: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_1: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_1: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_3: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_3: [MAX_MAP_1][]const u8 = undefined;
var _map_text_bufs_1_1: [MAX_MAP_1][256]u8 = undefined;
var _map_texts_1_1: [MAX_MAP_1][]const u8 = undefined;
var _map_lua_bufs_1: [MAX_MAP_1][32]u8 = undefined;
var _map_lua_ptrs_1: [MAX_MAP_1]?[*:0]const u8 = .{null} ** MAX_MAP_1;
fn _initMapLuaPtrs1() void {
    for (0..MAX_MAP_1) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_1[_i][0..31], "__mapPress_1({d})", .{_i}) catch continue;
        _map_lua_bufs_1[_i][n.len] = 0;
        _map_lua_ptrs_1[_i] = @ptrCast(_map_lua_bufs_1[_i][0..n.len :0]);
    }
}
fn _rebuildMap1() void {
    _map_count_1 = @min(_oa1_len, MAX_MAP_1);
    for (0.._map_count_1) |_i| {
        _map_texts_1_2[_i] = std.fmt.bufPrint(&_map_text_bufs_1_2[_i], "{s}", .{ _oa0_icon[_i][0.._oa0_icon_lens[_i]] }) catch "";
        _map_texts_1_0[_i] = std.fmt.bufPrint(&_map_text_bufs_1_0[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_1_0[_i] = std.fmt.bufPrint(&_map_text_bufs_1_0[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_1_0[_i] = std.fmt.bufPrint(&_map_text_bufs_1_0[_i], "{s}", .{ _oa0_icon[_i][0.._oa0_icon_lens[_i]] }) catch "";
        _map_texts_1_1[_i] = std.fmt.bufPrint(&_map_text_bufs_1_1[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_1_3[_i] = std.fmt.bufPrint(&_map_text_bufs_1_3[_i], "{s}:{d} / edits:{d} / dirty:{d}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]], @as(i64, @intCast(_i)), state.getSlot(1), state.getSlot(3) }) catch "";
        _map_texts_1_1[_i] = std.fmt.bufPrint(&_map_text_bufs_1_1[_i], "{s}", .{ "_oa1_value[_i]" }) catch "";
        _map_inner_1[_i] = [1]Node{ .{ .style = .{ .gap = 4 }, .children = &_arr_22 } };
        _map_pool_1[_i] = .{ .children = &_map_inner_1[_i] };
    }
    _arr_5[0].children = _map_pool_1[0.._map_count_1];
}

const MAX_MAP_2: usize = 4096;
var _map_pool_2: [MAX_MAP_2]Node = undefined;
var _map_count_2: usize = 0;
var _map_inner_2: [MAX_MAP_2][1]Node = undefined;
var _map_text_bufs_2_2: [MAX_MAP_2][256]u8 = undefined;
var _map_texts_2_2: [MAX_MAP_2][]const u8 = undefined;
var _map_text_bufs_2_0: [MAX_MAP_2][256]u8 = undefined;
var _map_texts_2_0: [MAX_MAP_2][]const u8 = undefined;
var _map_text_bufs_2_0: [MAX_MAP_2][256]u8 = undefined;
var _map_texts_2_0: [MAX_MAP_2][]const u8 = undefined;
var _map_text_bufs_2_0: [MAX_MAP_2][256]u8 = undefined;
var _map_texts_2_0: [MAX_MAP_2][]const u8 = undefined;
var _map_text_bufs_2_1: [MAX_MAP_2][256]u8 = undefined;
var _map_texts_2_1: [MAX_MAP_2][]const u8 = undefined;
var _map_text_bufs_2_3: [MAX_MAP_2][256]u8 = undefined;
var _map_texts_2_3: [MAX_MAP_2][]const u8 = undefined;
var _map_text_bufs_2_1: [MAX_MAP_2][256]u8 = undefined;
var _map_texts_2_1: [MAX_MAP_2][]const u8 = undefined;
fn _rebuildMap2() void {
    _map_count_2 = @min(_oa0_len, MAX_MAP_2);
    for (0.._map_count_2) |_i| {
        _map_texts_2_2[_i] = std.fmt.bufPrint(&_map_text_bufs_2_2[_i], "{s}", .{ _oa0_icon[_i][0.._oa0_icon_lens[_i]] }) catch "";
        _map_texts_2_0[_i] = std.fmt.bufPrint(&_map_text_bufs_2_0[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_2_0[_i] = std.fmt.bufPrint(&_map_text_bufs_2_0[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_2_0[_i] = std.fmt.bufPrint(&_map_text_bufs_2_0[_i], "{s}", .{ _oa0_icon[_i][0.._oa0_icon_lens[_i]] }) catch "";
        _map_texts_2_1[_i] = std.fmt.bufPrint(&_map_text_bufs_2_1[_i], "{s}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]] }) catch "";
        _map_texts_2_3[_i] = std.fmt.bufPrint(&_map_text_bufs_2_3[_i], "{s}:{d} / edits:{d} / dirty:{d}", .{ _oa0_label[_i][0.._oa0_label_lens[_i]], @as(i64, @intCast(_i)), state.getSlot(1), state.getSlot(3) }) catch "";
        _map_texts_2_1[_i] = std.fmt.bufPrint(&_map_text_bufs_2_1[_i], "{s}", .{ "_oa1_value[_i]" }) catch "";
        _map_inner_2[_i] = [1]Node{ .{ .text = "_oa1_placeholder[_i][0.._oa1_placeholder_lens[_i]]", .font_size = 12, .text_color = Color.rgb(156, 163, 175) } };
        _map_pool_2[_i] = .{ .children = &_map_inner_2[_i] };
    }
}


// ── Embedded JS logic ────────────────────────────────────────
const JS_LOGIC =
    \\var sections = [];
    \\function setSections(v) { sections = v; __setObjArr0(v); }
    \\var fields = [];
    \\function setFields(v) { fields = v; __setObjArr1(v); }
    \\// Schema-driven form data
    \\
    \\var sections = [
    \\  { label: 'Personal', icon: 'U' },
    \\  { label: 'Work', icon: 'W' },
    \\  { label: 'Preferences', icon: 'P' },
    \\  { label: 'Notifications', icon: 'N' }
    \\];
    \\setSections(sections);
    \\
    \\var fields = [
    \\  { label: 'Full Name', type: 0, sectionIdx: 0, value: 0, placeholder: 'Enter your name' },
    \\  { label: 'Email', type: 0, sectionIdx: 0, value: 0, placeholder: 'you@example.com' },
    \\  { label: 'Phone', type: 0, sectionIdx: 0, value: 0, placeholder: '+1 (555) 000-0000' },
    \\  { label: 'Public Profile', type: 1, sectionIdx: 0, value: 1, placeholder: '' },
    \\  { label: 'Company', type: 0, sectionIdx: 1, value: 0, placeholder: 'Company name' },
    \\  { label: 'Role', type: 2, sectionIdx: 1, value: 0, placeholder: '' },
    \\  { label: 'Experience (years)', type: 3, sectionIdx: 1, value: 5, placeholder: '' },
    \\  { label: 'Remote Work', type: 1, sectionIdx: 1, value: 1, placeholder: '' },
    \\  { label: 'Theme', type: 2, sectionIdx: 2, value: 0, placeholder: '' },
    \\  { label: 'Font Size', type: 3, sectionIdx: 2, value: 14, placeholder: '' },
    \\  { label: 'Compact Mode', type: 1, sectionIdx: 2, value: 0, placeholder: '' },
    \\  { label: 'Auto-save', type: 1, sectionIdx: 2, value: 1, placeholder: '' },
    \\  { label: 'Email Notifications', type: 1, sectionIdx: 3, value: 1, placeholder: '' },
    \\  { label: 'Push Notifications', type: 1, sectionIdx: 3, value: 0, placeholder: '' },
    \\  { label: 'Frequency', type: 2, sectionIdx: 3, value: 1, placeholder: '' },
    \\  { label: 'Quiet Hours', type: 1, sectionIdx: 3, value: 0, placeholder: '' }
    \\];
    \\setFields(fields);
    \\
    \\
    \\
;

// ── Embedded Lua logic ───────────────────────────────────────
const LUA_LOGIC =
    \\-- State variables (mirroring Zig state slots)
    \\local activeSection = 0
    \\local editCount = 0
    \\local lastEdited = 0
    \\local formDirty = 0
    \\local validationErrors = 0
    \\
    \\function setActiveSection(v) activeSection = v; __setState(0, v) end
    \\function setEditCount(v) editCount = v; __setState(1, v) end
    \\function setLastEdited(v) lastEdited = v; __setState(2, v) end
    \\function setFormDirty(v) formDirty = v; __setState(3, v) end
    \\function setValidationErrors(v) validationErrors = v; __setState(4, v) end
    \\
    \\local sections = {}
    \\function setSections(v) sections = v; __setObjArr0(v) end
    \\local fields = {}
    \\function setFields(v) fields = v; __setObjArr1(v) end
    \\// Schema-driven form data
    \\
    \\local sections = {
    \\  { label = 'Personal', icon = 'U' },
    \\  { label = 'Work', icon = 'W' },
    \\  { label = 'Preferences', icon = 'P' },
    \\  { label = 'Notifications', icon = 'N' }
    \\}
    \\setSections(sections);
    \\
    \\local fields = {
    \\  { label = 'Full Name', type = 0, sectionIdx = 0, value = 0, placeholder = 'Enter your name' },
    \\  { label = 'Email', type = 0, sectionIdx = 0, value = 0, placeholder = 'you@example.com' },
    \\  { label = 'Phone', type = 0, sectionIdx = 0, value = 0, placeholder = '+1 (555) 000-0000' },
    \\  { label = 'Public Profile', type = 1, sectionIdx = 0, value = 1, placeholder = '' },
    \\  { label = 'Company', type = 0, sectionIdx = 1, value = 0, placeholder = 'Company name' },
    \\  { label = 'Role', type = 2, sectionIdx = 1, value = 0, placeholder = '' },
    \\  { label = 'Experience (years)', type = 3, sectionIdx = 1, value = 5, placeholder = '' },
    \\  { label = 'Remote Work', type = 1, sectionIdx = 1, value = 1, placeholder = '' },
    \\  { label = 'Theme', type = 2, sectionIdx = 2, value = 0, placeholder = '' },
    \\  { label = 'Font Size', type = 3, sectionIdx = 2, value = 14, placeholder = '' },
    \\  { label = 'Compact Mode', type = 1, sectionIdx = 2, value = 0, placeholder = '' },
    \\  { label = 'Auto-save', type = 1, sectionIdx = 2, value = 1, placeholder = '' },
    \\  { label = 'Email Notifications', type = 1, sectionIdx = 3, value = 1, placeholder = '' },
    \\  { label = 'Push Notifications', type = 1, sectionIdx = 3, value = 0, placeholder = '' },
    \\  { label = 'Frequency', type = 2, sectionIdx = 3, value = 1, placeholder = '' },
    \\  { label = 'Quiet Hours', type = 1, sectionIdx = 3, value = 0, placeholder = '' }
    \\}
    \\setFields(fields);
    \\
    \\
    \\function __mapPress_0(idx)
    \\  local sec = sections[idx + 1]
    \\  local si = idx
    \\  setActiveSection(si)
    \\end
    \\
    \\function __mapPress_1(idx)
    \\  local field = fields[idx + 1]
    \\  local fi = idx
    \\  setLastEdited(fieldIdx); setEditCount(editCount + 1); setFormDirty(1)
    \\end
    \\
    \\function __mapPress_1(idx)
    \\  local field = fields[idx + 1]
    \\  local fi = idx
    \\  setLastEdited(fieldIdx); setEditCount(editCount + 1); setFormDirty(1)
    \\end
    \\
    \\function __mapPress_1(idx)
    \\  local field = fields[idx + 1]
    \\  local fi = idx
    \\  setLastEdited(fieldIdx); setEditCount(editCount + 1); setFormDirty(1)
    \\end
    \\
    \\function __mapPress_1(idx)
    \\  local field = fields[idx + 1]
    \\  local fi = idx
    \\  setLastEdited(fieldIdx); setEditCount(editCount + 1); setFormDirty(1)
    \\end
    \\
    \\function __mapPress_1(idx)
    \\  local field = fields[idx + 1]
    \\  local fi = idx
    \\  setLastEdited(fieldIdx); setEditCount(editCount + 1); setFormDirty(1)
    \\end
    \\
    \\function __mapPress_1(idx)
    \\  local field = fields[idx + 1]
    \\  local fi = idx
    \\  setLastEdited(fieldIdx); setEditCount(editCount + 1); setFormDirty(1)
    \\end
    \\
    \\function __mapPress_1(idx)
    \\  local field = fields[idx + 1]
    \\  local fi = idx
    \\  setLastEdited(fieldIdx); setEditCount(editCount + 1); setFormDirty(1)
    \\end
    \\
    \\
;

fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

fn _updateDynamicTexts() void {
    _dyn_text_0 = std.fmt.bufPrint(&_dyn_buf_0, "{d} errors", .{ state.getSlot(4) }) catch "";
    _arr_0[5].text = _dyn_text_0;
    _dyn_text_1 = std.fmt.bufPrint(&_dyn_buf_1, "edits: {d} | last: #{d}", .{ state.getSlot(1), state.getSlot(2) }) catch "";
    _arr_0[6].text = _dyn_text_1;
    _dyn_text_2 = std.fmt.bufPrint(&_dyn_buf_2, "{d} errors", .{ state.getSlot(4) }) catch "";
    _arr_2[0].text = _dyn_text_2;
    _dyn_text_3 = std.fmt.bufPrint(&_dyn_buf_3, "{s}:{s} | edits:{d}", .{ "si", "fi", state.getSlot(1) }) catch "";
    _arr_6[1].text = _dyn_text_3;
    _dyn_text_4 = std.fmt.bufPrint(&_dyn_buf_4, "numeric field in active section {s}", .{ "si" }) catch "";
    _arr_20[0].text = _dyn_text_4;
}

fn _updateConditionals() void {
    _arr_0[0].style.display = if ((state.getSlot(0) == si)) .flex else .none;
    _arr_0[1].style.display = if ((state.getSlot(0) != si)) .flex else .none;
    _arr_0[3].style.display = if ((state.getSlot(0) == si)) .flex else .none;
    _arr_0[4].style.display = if ((state.getSlot(0) != si)) .flex else .none;
    _arr_0[4].style.display = if ((state.getSlot(3) ==  1)) .flex else .none;
    _arr_0[5].style.display = if ((state.getSlot(4) !=  0)) .flex else .none;
    _arr_3[0].style.display = if ((state.getSlot(3) ==  1)) .flex else .none;
    _arr_3[1].style.display = if ((state.getSlot(4) !=  0)) .flex else .none;
    _arr_8[0].style.display = if ((state.getSlot(2) == fieldIdx)) .flex else .none;
    _arr_9[1].style.display = if ((state.getSlot(3) ==  1)) .flex else .none;
    _arr_22[1].style.display = if ((type ==  0)) .flex else .none;
    _arr_12[1].style.display = if ((value ==  1)) .flex else .none;
    _arr_12[2].style.display = if ((value ==  0)) .flex else .none;
    _arr_22[2].style.display = if ((type ==  1)) .flex else .none;
    _arr_13[0].style.display = if ((value ==  0)) .flex else .none;
    _arr_13[1].style.display = if ((value !=  0)) .flex else .none;
    _arr_14[0].style.display = if ((value ==  1)) .flex else .none;
    _arr_14[1].style.display = if ((value !=  1)) .flex else .none;
    _arr_15[0].style.display = if ((value ==  2)) .flex else .none;
    _arr_15[1].style.display = if ((value !=  2)) .flex else .none;
    _arr_22[3].style.display = if ((type ==  2)) .flex else .none;
    _arr_20[0].style.display = if ((state.getSlot(3) ==  1)) .flex else .none;
    _arr_21[1].style.display = if ((state.getSlot(0) == sectionIdx)) .flex else .none;
    _arr_22[4].style.display = if ((type ==  3)) .flex else .none;
    _arr_23[0].style.display = if ((field.sectionIdx == si)) .flex else .none;
    _arr_7[0].style.display = if ((state.getSlot(0) == si)) .flex else .none;
}


fn _appInit() void {
    _initState();
    qjs_runtime.registerHostFn("__setObjArr0", @ptrCast(&_oa0_unpack), 1);
    qjs_runtime.registerHostFn("__setObjArr1", @ptrCast(&_oa1_unpack), 1);
    _updateDynamicTexts();
    _updateConditionals();
    _initMapLuaPtrs0();
    _initMapLuaPtrs1();
    _rebuildMap0();
    _rebuildMap1();
    _rebuildMap2();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts(); _updateConditionals();
        _rebuildMap0();
        _rebuildMap1();
        _rebuildMap2();
 state.clearDirty(); }
}

export fn app_get_root() *Node { return &_root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d13_schema_form"; }

export fn app_state_count() usize { return 5; }
const _slot_types = [_]u8{ 0, 0, 0, 0, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

// Standalone mode — when compiled as an executable directly (skipped in .so builds)
pub fn main() !void {
    if (IS_LIB) return;
    try engine.run(.{
        .title = "d13_schema_form",
        .root = &_root,
        .js_logic = JS_LOGIC,
        .lua_logic = LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}
