//! Generated by tsz compiler (Zig) — do not edit
//!
//! Source: d14_multiple_instances.tsz

const std = @import("std");
const build_options = @import("build_options");
const IS_LIB = if (@hasDecl(build_options, "is_lib")) build_options.is_lib else false;

const layout = @import("framework/layout.zig");
const Node = layout.Node;
const Style = layout.Style;
const Color = layout.Color;
const state = @import("framework/state.zig");
const engine = if (IS_LIB) struct {} else @import("framework/engine.zig");

// ── State manifest ──────────────────────────────────────────────
// slot 0: globalClicks (int)
// slot 1: count (int)
// slot 2: dismissed (int)
// slot 3: count (int)
// slot 4: count (int)
// slot 5: count (int)
// slot 6: dismissed (int)
// slot 7: dismissed (int)
// slot 8: dismissed (int)
// slot 9: dismissed (int)
// slot 10: dismissed (int)
// slot 11: count (int)
// slot 12: count (int)
comptime { if (13 != 13) @compileError("state slot count mismatch"); }

// ── Generated node tree ─────────────────────────────────────────
// tsz:d14_multiple_instances.tsz:15 — <Pressable>
var _arr_0 = [_]Node{ .{ .text = "+1", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } }; // Counter
// tsz:d14_multiple_instances.tsz:18 — <Pressable>
var _arr_1 = [_]Node{ .{ .text = "Reset", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } }; // Counter
// tsz:d14_multiple_instances.tsz:12 — <Box>
var _arr_2 = [_]Node{ .{ .text = "Counter A", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .text = "", .font_size = 32, .text_color = Color.rgb(0, 0, 0) }, .{ .style = .{ .background_color = Color.rgb(51, 65, 85), .border_radius = 6, .padding = 10, .align_items = .center }, .handlers = .{ .lua_on_press = "setCount(count + 1); setGlobalClicks(globalClicks + 1)" }, .children = &_arr_0 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 6, .align_items = .center, .border_color = Color.rgb(51, 65, 85), .border_width = 1 }, .handlers = .{ .lua_on_press = "setCount(0)" }, .children = &_arr_1 } }; // Counter
// tsz:d14_multiple_instances.tsz:15 — <Pressable>
var _arr_3 = [_]Node{ .{ .text = "+1", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } }; // Counter
// tsz:d14_multiple_instances.tsz:18 — <Pressable>
var _arr_4 = [_]Node{ .{ .text = "Reset", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } }; // Counter
// tsz:d14_multiple_instances.tsz:12 — <Box>
var _arr_5 = [_]Node{ .{ .text = "Counter B", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .text = "", .font_size = 32, .text_color = Color.rgb(0, 0, 0) }, .{ .style = .{ .background_color = Color.rgb(51, 65, 85), .border_radius = 6, .padding = 10, .align_items = .center }, .handlers = .{ .lua_on_press = "setCount(count + 1); setGlobalClicks(globalClicks + 1)" }, .children = &_arr_3 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 6, .align_items = .center, .border_color = Color.rgb(51, 65, 85), .border_width = 1 }, .handlers = .{ .lua_on_press = "setCount(0)" }, .children = &_arr_4 } }; // Counter
// tsz:d14_multiple_instances.tsz:15 — <Pressable>
var _arr_6 = [_]Node{ .{ .text = "+1", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } }; // Counter
// tsz:d14_multiple_instances.tsz:18 — <Pressable>
var _arr_7 = [_]Node{ .{ .text = "Reset", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } }; // Counter
// tsz:d14_multiple_instances.tsz:12 — <Box>
var _arr_8 = [_]Node{ .{ .text = "Counter C", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .text = "", .font_size = 32, .text_color = Color.rgb(0, 0, 0) }, .{ .style = .{ .background_color = Color.rgb(51, 65, 85), .border_radius = 6, .padding = 10, .align_items = .center }, .handlers = .{ .lua_on_press = "setCount(count + 1); setGlobalClicks(globalClicks + 1)" }, .children = &_arr_6 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 6, .align_items = .center, .border_color = Color.rgb(51, 65, 85), .border_width = 1 }, .handlers = .{ .lua_on_press = "setCount(0)" }, .children = &_arr_7 } }; // Counter
// tsz:d14_multiple_instances.tsz:46 — <Box>
var _arr_9 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 16, .gap = 8, .flex_grow = 1 }, .children = &_arr_2 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 16, .gap = 8, .flex_grow = 1 }, .children = &_arr_5 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 16, .gap = 8, .flex_grow = 1 }, .children = &_arr_8 } };
// tsz:d14_multiple_instances.tsz:29 — <Pressable>
var _arr_10 = [_]Node{ .{ .text = "Info", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } }; // Badge
// tsz:d14_multiple_instances.tsz:32 — <Box>
var _arr_11 = [_]Node{ .{ .text = "dismissed", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } }; // Badge
// tsz:d14_multiple_instances.tsz:28 — <Box>
var _arr_12 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(59, 130, 246), .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .handlers = .{ .lua_on_press = "setDismissed(1)" }, .children = &_arr_10 }, .{ .style = .{ .border_color = Color.rgb(51, 65, 85), .border_width = 1, .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .children = &_arr_11 } }; // Badge
// tsz:d14_multiple_instances.tsz:29 — <Pressable>
var _arr_13 = [_]Node{ .{ .text = "Success", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } }; // Badge
// tsz:d14_multiple_instances.tsz:32 — <Box>
var _arr_14 = [_]Node{ .{ .text = "dismissed", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } }; // Badge
// tsz:d14_multiple_instances.tsz:28 — <Box>
var _arr_15 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(34, 197, 94), .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .handlers = .{ .lua_on_press = "setDismissed(1)" }, .children = &_arr_13 }, .{ .style = .{ .border_color = Color.rgb(51, 65, 85), .border_width = 1, .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .children = &_arr_14 } }; // Badge
// tsz:d14_multiple_instances.tsz:29 — <Pressable>
var _arr_16 = [_]Node{ .{ .text = "Warning", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } }; // Badge
// tsz:d14_multiple_instances.tsz:32 — <Box>
var _arr_17 = [_]Node{ .{ .text = "dismissed", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } }; // Badge
// tsz:d14_multiple_instances.tsz:28 — <Box>
var _arr_18 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(245, 158, 11), .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .handlers = .{ .lua_on_press = "setDismissed(1)" }, .children = &_arr_16 }, .{ .style = .{ .border_color = Color.rgb(51, 65, 85), .border_width = 1, .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .children = &_arr_17 } }; // Badge
// tsz:d14_multiple_instances.tsz:29 — <Pressable>
var _arr_19 = [_]Node{ .{ .text = "Error", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } }; // Badge
// tsz:d14_multiple_instances.tsz:32 — <Box>
var _arr_20 = [_]Node{ .{ .text = "dismissed", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } }; // Badge
// tsz:d14_multiple_instances.tsz:28 — <Box>
var _arr_21 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(239, 68, 68), .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .handlers = .{ .lua_on_press = "setDismissed(1)" }, .children = &_arr_19 }, .{ .style = .{ .border_color = Color.rgb(51, 65, 85), .border_width = 1, .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .children = &_arr_20 } }; // Badge
// tsz:d14_multiple_instances.tsz:29 — <Pressable>
var _arr_22 = [_]Node{ .{ .text = "Debug", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } }; // Badge
// tsz:d14_multiple_instances.tsz:32 — <Box>
var _arr_23 = [_]Node{ .{ .text = "dismissed", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } }; // Badge
// tsz:d14_multiple_instances.tsz:28 — <Box>
var _arr_24 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(139, 92, 246), .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .handlers = .{ .lua_on_press = "setDismissed(1)" }, .children = &_arr_22 }, .{ .style = .{ .border_color = Color.rgb(51, 65, 85), .border_width = 1, .border_radius = 12, .padding_left = 10, .padding_right = 10, .padding_top = 4, .padding_bottom = 4 }, .children = &_arr_23 } }; // Badge
// tsz:d14_multiple_instances.tsz:53 — <Box>
var _arr_25 = [_]Node{ .{ .children = &_arr_12 }, .{ .children = &_arr_15 }, .{ .children = &_arr_18 }, .{ .children = &_arr_21 }, .{ .children = &_arr_24 } };
// tsz:d14_multiple_instances.tsz:15 — <Pressable>
var _arr_26 = [_]Node{ .{ .text = "+1", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } }; // Counter
// tsz:d14_multiple_instances.tsz:18 — <Pressable>
var _arr_27 = [_]Node{ .{ .text = "Reset", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } }; // Counter
// tsz:d14_multiple_instances.tsz:12 — <Box>
var _arr_28 = [_]Node{ .{ .text = "Outer Left", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .text = "", .font_size = 32, .text_color = Color.rgb(0, 0, 0) }, .{ .style = .{ .background_color = Color.rgb(51, 65, 85), .border_radius = 6, .padding = 10, .align_items = .center }, .handlers = .{ .lua_on_press = "setCount(count + 1); setGlobalClicks(globalClicks + 1)" }, .children = &_arr_26 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 6, .align_items = .center, .border_color = Color.rgb(51, 65, 85), .border_width = 1 }, .handlers = .{ .lua_on_press = "setCount(0)" }, .children = &_arr_27 } }; // Counter
// tsz:d14_multiple_instances.tsz:15 — <Pressable>
var _arr_29 = [_]Node{ .{ .text = "+1", .font_size = 12, .text_color = Color.rgb(226, 232, 240) } }; // Counter
// tsz:d14_multiple_instances.tsz:18 — <Pressable>
var _arr_30 = [_]Node{ .{ .text = "Reset", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } }; // Counter
// tsz:d14_multiple_instances.tsz:12 — <Box>
var _arr_31 = [_]Node{ .{ .text = "Outer Right", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .text = "", .font_size = 32, .text_color = Color.rgb(0, 0, 0) }, .{ .style = .{ .background_color = Color.rgb(51, 65, 85), .border_radius = 6, .padding = 10, .align_items = .center }, .handlers = .{ .lua_on_press = "setCount(count + 1); setGlobalClicks(globalClicks + 1)" }, .children = &_arr_29 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 6, .padding = 6, .align_items = .center, .border_color = Color.rgb(51, 65, 85), .border_width = 1 }, .handlers = .{ .lua_on_press = "setCount(0)" }, .children = &_arr_30 } }; // Counter
// tsz:d14_multiple_instances.tsz:62 — <Box>
var _arr_32 = [_]Node{ .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 16, .gap = 8, .flex_grow = 1 }, .children = &_arr_28 }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 16, .gap = 8, .flex_grow = 1 }, .children = &_arr_31 } };
// tsz:d14_multiple_instances.tsz:41 — <Box>
var _arr_33 = [_]Node{ .{ .text = "Multiple Instances", .font_size = 18, .text_color = Color.rgb(241, 245, 249) }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(71, 85, 105) }, .{ .text = "Three counters — each must count independently", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .flex_direction = .row, .gap = 12 }, .children = &_arr_9 }, .{ .text = "Five badges — each dismisses independently", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .flex_direction = .row, .gap = 8, .flex_wrap = .wrap }, .children = &_arr_25 }, .{ .text = "Nested: component inside component, both with state", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .flex_direction = .row, .gap = 12 }, .children = &_arr_32 } };
var _root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(15, 23, 42), .padding = 20, .gap = 16 }, .children = &_arr_33 };

// ── Dynamic text buffers ─────────────────────────────────────────
var _dyn_buf_0: [64]u8 = undefined;
var _dyn_text_0: []const u8 = "";
var _dyn_buf_1: [64]u8 = undefined;
var _dyn_text_1: []const u8 = "";
var _dyn_buf_2: [64]u8 = undefined;
var _dyn_text_2: []const u8 = "";
var _dyn_buf_3: [64]u8 = undefined;
var _dyn_text_3: []const u8 = "";
var _dyn_buf_4: [64]u8 = undefined;
var _dyn_text_4: []const u8 = "";
var _dyn_buf_5: [64]u8 = undefined;
var _dyn_text_5: []const u8 = "";

// ── Embedded JS logic ────────────────────────────────────────
const JS_LOGIC =
    \\
;

// ── Embedded Lua logic ───────────────────────────────────────
const LUA_LOGIC =
    \\-- State variables (mirroring Zig state slots)
    \\local globalClicks = 0
    \\local count = 0
    \\local dismissed = 0
    \\local count = 0
    \\local count = 0
    \\local count = 0
    \\local dismissed = 0
    \\local dismissed = 0
    \\local dismissed = 0
    \\local dismissed = 0
    \\local dismissed = 0
    \\local count = 0
    \\local count = 0
    \\
    \\function setGlobalClicks(v) globalClicks = v; __setState(0, v) end
    \\function setCount(v) count = v; __setState(1, v) end
    \\function setDismissed(v) dismissed = v; __setState(2, v) end
    \\function setCount(v) count = v; __setState(3, v) end
    \\function setCount(v) count = v; __setState(4, v) end
    \\function setCount(v) count = v; __setState(5, v) end
    \\function setDismissed(v) dismissed = v; __setState(6, v) end
    \\function setDismissed(v) dismissed = v; __setState(7, v) end
    \\function setDismissed(v) dismissed = v; __setState(8, v) end
    \\function setDismissed(v) dismissed = v; __setState(9, v) end
    \\function setDismissed(v) dismissed = v; __setState(10, v) end
    \\function setCount(v) count = v; __setState(11, v) end
    \\function setCount(v) count = v; __setState(12, v) end
    \\
    \\
;

fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

fn _updateDynamicTexts() void {
    _dyn_text_0 = std.fmt.bufPrint(&_dyn_buf_0, "global clicks: {d}", .{ state.getSlot(0) }) catch "";
    _arr_33[1].text = _dyn_text_0;
    _dyn_text_1 = std.fmt.bufPrint(&_dyn_buf_1, "{d}", .{ state.getSlot(3) }) catch "";
    _arr_2[1].text = _dyn_text_1;
    _dyn_text_2 = std.fmt.bufPrint(&_dyn_buf_2, "{d}", .{ state.getSlot(4) }) catch "";
    _arr_5[1].text = _dyn_text_2;
    _dyn_text_3 = std.fmt.bufPrint(&_dyn_buf_3, "{d}", .{ state.getSlot(5) }) catch "";
    _arr_8[1].text = _dyn_text_3;
    _dyn_text_4 = std.fmt.bufPrint(&_dyn_buf_4, "{d}", .{ state.getSlot(11) }) catch "";
    _arr_28[1].text = _dyn_text_4;
    _dyn_text_5 = std.fmt.bufPrint(&_dyn_buf_5, "{d}", .{ state.getSlot(12) }) catch "";
    _arr_31[1].text = _dyn_text_5;
    _arr_2[1].text_color = Color.rgb(59, 130, 246);
    _arr_5[1].text_color = Color.rgb(34, 197, 94);
    _arr_8[1].text_color = Color.rgb(245, 158, 11);
    _arr_28[1].text_color = Color.rgb(236, 72, 153);
    _arr_31[1].text_color = Color.rgb(20, 184, 166);
}

fn _updateConditionals() void {
    _arr_12[0].style.display = if ((state.getSlot(6) ==  0)) .flex else .none;
    _arr_12[1].style.display = if ((state.getSlot(6) ==  1)) .flex else .none;
    _arr_15[0].style.display = if ((state.getSlot(7) ==  0)) .flex else .none;
    _arr_15[1].style.display = if ((state.getSlot(7) ==  1)) .flex else .none;
    _arr_18[0].style.display = if ((state.getSlot(8) ==  0)) .flex else .none;
    _arr_18[1].style.display = if ((state.getSlot(8) ==  1)) .flex else .none;
    _arr_21[0].style.display = if ((state.getSlot(9) ==  0)) .flex else .none;
    _arr_21[1].style.display = if ((state.getSlot(9) ==  1)) .flex else .none;
    _arr_24[0].style.display = if ((state.getSlot(10) ==  0)) .flex else .none;
    _arr_24[1].style.display = if ((state.getSlot(10) ==  1)) .flex else .none;
}


fn _appInit() void {
    _initState();
    _updateDynamicTexts();
    _updateConditionals();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts(); _updateConditionals(); state.clearDirty(); }
}

export fn app_get_root() *Node { return &_root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d14_multiple_instances"; }

export fn app_state_count() usize { return 13; }
const _slot_types = [_]u8{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

// Standalone mode — when compiled as an executable directly (skipped in .so builds)
pub fn main() !void {
    if (IS_LIB) return;
    try engine.run(.{
        .title = "d14_multiple_instances",
        .root = &_root,
        .js_logic = JS_LOGIC,
        .lua_logic = LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}
