//! Generated by tsz compiler — s13b_music_player [logic.zig]
//! Source: s13b_music_player.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var playing = 0;
    \\function setPlaying(v) { playing = v; if (__luaReady) __luaEval("setPlaying(" + v + ")"); else __markDirty(); }
    \\var progress = 0;
    \\function setProgress(v) { progress = v; if (__luaReady) __luaEval("setProgress(" + v + ")"); else __markDirty(); }
    \\var trackIdx = 0;
    \\function setTrackIdx(v) { trackIdx = v; if (__luaReady) __luaEval("setTrackIdx(" + v + ")"); else __markDirty(); }
    \\var shuffle = 0;
    \\function setShuffle(v) { shuffle = v; if (__luaReady) __luaEval("setShuffle(" + v + ")"); else __markDirty(); }
    \\var tracks = [];
    \\var tracks = [
    \\  { title: 'Midnight Drive', artist: 'Synthwave', duration: 243 },
    \\  { title: 'Blue Horizon', artist: 'Lo-fi Beats', duration: 198 },
    \\  { title: 'Digital Rain', artist: 'Ambient', duration: 312 },
    \\  { title: 'Neon City', artist: 'Retrowave', duration: 267 }
    \\];
    \\
    \\function togglePlay() {
    \\  setPlaying(playing === 1 ? 0 : 1);
    \\}
    \\
    \\function nextTrack() {
    \\  if (shuffle === 1) {
    \\    var next = Math.floor(Math.random() * tracks.length);
    \\    setTrackIdx(next);
    \\  } else {
    \\    setTrackIdx((trackIdx + 1) % tracks.length);
    \\  }
    \\  setProgress(0);
    \\}
    \\
    \\function prevTrack() {
    \\  setTrackIdx(trackIdx === 0 ? tracks.length - 1 : trackIdx - 1);
    \\  setProgress(0);
    \\}
    \\
    \\function seek(pct) {
    \\  setProgress(pct);
    \\}
    \\
    \\function step() {
    \\  if (playing === 0) return;
    \\  var next = progress + 1;
    \\  if (next >= 100) { nextTrack(); return; }
    \\  setProgress(next);
    \\}
    \\
    \\function formatTime(secs, pct) {
    \\  var t = Math.floor(secs * pct / 100);
    \\  var m = Math.floor(t / 60);
    \\  var s = t % 60;
    \\  return m + ':' + (s < 10 ? '0' : '') + s;
    \\}
    \\
    \\var albumColors = ['#1e3a5f', '#3b1a5f', '#1a3b1f', '#3b2a0a'];
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["playing"] = 0
    \\playing = _state["playing"]
    \\function setPlaying(v) _state["playing"] = v; playing = v; __syncToJS("playing", v); __markDirty() end
    \\_state["progress"] = 0
    \\progress = _state["progress"]
    \\function setProgress(v) _state["progress"] = v; progress = v; __syncToJS("progress", v); __markDirty() end
    \\_state["trackIdx"] = 0
    \\trackIdx = _state["trackIdx"]
    \\function setTrackIdx(v) _state["trackIdx"] = v; trackIdx = v; __syncToJS("trackIdx", v); __markDirty() end
    \\_state["shuffle"] = 0
    \\shuffle = _state["shuffle"]
    \\function setShuffle(v) _state["shuffle"] = v; shuffle = v; __syncToJS("shuffle", v); __markDirty() end
    \\_state["__jsExpr_4"] = ""
    \\__jsExpr_4 = _state["__jsExpr_4"]
    \\function __setJsExpr_4(v) _state["__jsExpr_4"] = v; __jsExpr_4 = v; __syncToJS("__jsExpr_4", v); __markDirty() end
    \\_state["__jsExpr_5"] = ""
    \\__jsExpr_5 = _state["__jsExpr_5"]
    \\function __setJsExpr_5(v) _state["__jsExpr_5"] = v; __jsExpr_5 = v; __syncToJS("__jsExpr_5", v); __markDirty() end
    \\_state["__jsExpr_6"] = ""
    \\__jsExpr_6 = _state["__jsExpr_6"]
    \\function __setJsExpr_6(v) _state["__jsExpr_6"] = v; __jsExpr_6 = v; __syncToJS("__jsExpr_6", v); __markDirty() end
    \\_state["__jsExpr_7"] = ""
    \\__jsExpr_7 = _state["__jsExpr_7"]
    \\function __setJsExpr_7(v) _state["__jsExpr_7"] = v; __jsExpr_7 = v; __syncToJS("__jsExpr_7", v); __markDirty() end
    \\_state["__jsExpr_8"] = ""
    \\__jsExpr_8 = _state["__jsExpr_8"]
    \\function __setJsExpr_8(v) _state["__jsExpr_8"] = v; __jsExpr_8 = v; __syncToJS("__jsExpr_8", v); __markDirty() end
    \\
    \\tracks = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, width = -1, height = -1, align_items = "center", justify_content = "center", padding = 24, gap = 20, overflow = "hidden" }, children = {
    \\    { style = { background_color = "0x000000", width = 200, height = 200, border_radius = 16, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\      { text = (playing == 1) and "♪" or "♫", font_size = 48, text_color = 0xffffff }
    \\    } },
    \\    { style = { align_items = "center", gap = 4 }, children = {
    \\      { text = tostring(__jsExpr_4), font_size = 18, text_color = 0xf8fafc },
    \\      { text = tostring(__jsExpr_5), font_size = 13, text_color = 0x94a3b8 }
    \\    } },
    \\    { style = { width = -1, gap = 4 }, children = {
    \\      { style = { width = -1, height = 4, background_color = 0x1e293b, border_radius = 2, overflow = "auto" }, children = {
    \\        { style = { height = 4, background_color = 0x3b82f6, border_radius = 2 } }
    \\      } },
    \\      { style = { flex_direction = "row", justify_content = "space_between" }, children = {
    \\        { text = tostring(__jsExpr_6), font_size = 10, text_color = 0x64748b },
    \\        { text = tostring(__jsExpr_7), font_size = 10, text_color = 0x64748b }
    \\      } },
    \\      { style = { flex_direction = "row", gap = 8, justify_content = "center" } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 12, align_items = "center" }, children = {
    \\      { style = { padding = 8, background_color = (shuffle == 1) and 0x1e3a5f or 0x1e293b, border_radius = 8 }, lua_on_press = "setShuffle(shuffle == 1 and 0 or 1)", children = {
    \\        { text = "⇌", font_size = 13, text_color = (shuffle == 1) and 0x3b82f6 or 0x64748b }
    \\      } },
    \\      { style = { padding = 10, background_color = 0x1e293b, border_radius = 10 }, lua_on_press = "prevTrack()", children = {
    \\        { text = "⏮", font_size = 16, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 14, background_color = 0x3b82f6, border_radius = 30, align_items = "center" }, lua_on_press = "togglePlay()", children = {
    \\        { text = (playing == 1) and "⏸" or "▶", font_size = 20, text_color = 0xffffff }
    \\      } },
    \\      { style = { padding = 10, background_color = 0x1e293b, border_radius = 10 }, lua_on_press = "nextTrack()", children = {
    \\        { text = "⏭", font_size = 16, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x1e293b, border_radius = 8 }, lua_on_press = "step()", children = {
    \\        { text = "+1s", font_size = 11, text_color = 0x64748b }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      __mapLoop(tracks, function(_item, _i)
    \\        return { style = { padding = 4 }, lua_on_press = "setTrackIdx(" .. ((_i - 1)) .. "); setProgress(0); ", children = {
    \\          { style = { width = 8, height = 8, border_radius = 4, background_color = (trackIdx == (_i - 1)) and 0x3b82f6 or 0x334155 } }
    \\        } }
    \\      end)
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

