//! Generated by tsz compiler — s13b_music_player [nodes.zig]
//! Source: s13b_music_player.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:s13b_music_player:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

