//! Generated by tsz compiler — s13b_music_player [state.zig]
//! Source: s13b_music_player.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

