//! Generated by tsz compiler — d26a_timer_script [nodes.zig]
//! Source: d26a_timer_script.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d26a_timer_script:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

