//! Generated by tsz compiler — d26a_timer_script [state.zig]
//! Source: d26a_timer_script.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

