//! Generated by tsz compiler — d28a_string_ops_script [logic.zig]
//! Source: d28a_string_ops_script.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var query = "";
    \\function setQuery(v) { query = v; if (__luaReady) __luaEval("setQuery(\'" + v + "\')"); else __markDirty(); }
    \\var resultCount = 0;
    \\function setResultCount(v) { resultCount = v; if (__luaReady) __luaEval("setResultCount(" + v + ")"); else __markDirty(); }
    \\var lastParsed = "";
    \\function setLastParsed(v) { lastParsed = v; if (__luaReady) __luaEval("setLastParsed(\'" + v + "\')"); else __markDirty(); }
    \\var entries = [ { raw : "" , parsed : "" , domain : "" , valid : 0 } ];
    \\function setEntries(v) { entries = v; __markDirty(); }
    \\var results = [ { raw : "" , parsed : "" , domain : "" , valid : 0 } ];
    \\function setResults(v) { results = v; __markDirty(); }
    \\var emails = [
    \\  'alice@example.com',
    \\  'BOB@GMAIL.COM',
    \\  '  carol@test.org  ',
    \\  'dave@company.co.uk',
    \\  'invalid-no-at-sign',
    \\  'eve@dev.io',
    \\  '  FRANK@Yahoo.COM  ',
    \\  'grace@startup.ai',
    \\  'not.an" email',
    \\  'heidi@university.edu'
    \\];
    \\
    \\var parsed = [];
    \\for (var i = 0; i < emails.length; i++) {
    \\  var raw = emails[i];
    \\  var trimmed = raw.trim !== undefined ? raw.trim() : raw;
    \\  var lower = trimmed.toLowerCase !== undefined ? trimmed.toLowerCase() : trimmed;
    \\  var atIdx = lower.indexOf('@');
    \\  var valid = atIdx > 0 && atIdx < lower.length - 1 ? 1 : 0;
    \\  var domain = valid === 1 ? lower.slice(atIdx + 1) : 'n/a';
    \\  parsed.push({ raw: raw, parsed: lower, domain: domain, valid: valid });
    \\}
    \\setEntries(parsed);
    \\setResults(parsed);
    \\setResultCount(parsed.length);
    \\
    \\function search(q) {
    \\  setQuery(q);
    \\  var lower = q.toLowerCase !== undefined ? q.toLowerCase() : q;
    \\  if (lower === '' || lower.length === 0) {
    \\    setResults(entries);
    \\    setResultCount(entries.length);
    \\    setLastParsed('showing all');
    \\    return;
    \\  }
    \\  var matched = [];
    \\  for (var i = 0; i < entries.length; i++) {
    \\    if (entries[i].parsed.indexOf(lower) >= 0) {
    \\      matched.push(entries[i]);
    \\    }
    \\  }
    \\  setResults(matched);
    \\  setResultCount(matched.length);
    \\  setLastParsed('searched: ' + lower);
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["query"] = ""
    \\query = _state["query"]
    \\function setQuery(v) _state["query"] = v; query = v; __syncToJS("query", v); __markDirty() end
    \\_state["resultCount"] = 0
    \\resultCount = _state["resultCount"]
    \\function setResultCount(v) _state["resultCount"] = v; resultCount = v; __syncToJS("resultCount", v); __markDirty() end
    \\_state["lastParsed"] = ""
    \\lastParsed = _state["lastParsed"]
    \\function setLastParsed(v) _state["lastParsed"] = v; lastParsed = v; __syncToJS("lastParsed", v); __markDirty() end
    \\
    \\entries = {}
    \\function setEntries(v) entries = v; __markDirty() end
    \\results = {}
    \\function setResults(v) results = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x1a1a2e, padding = 20, width = -1, height = -1, gap = 10, overflow = "hidden" }, children = {
    \\    { text = "Email Parser", font_size = 16, text_color = 0xe2e8f0 },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "search ( \"com\" )", children = {
    \\        { text = ".com", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "search ( \"org\" )", children = {
    \\        { text = ".org", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "search ( \"alice\" )", children = {
    \\        { text = "alice", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "search ( \"\" )", children = {
    \\        { text = "Clear", font_size = 10, text_color = 0xe2e8f0 }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(results, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", padding = 8, background_color = 0x16213e, border_radius = 4, gap = 8 }, children = {
    \\          { text = tostring(_item.parsed), font_size = 10, text_color = 0xe2e8f0 },
    \\          { text = tostring(_item.domain), font_size = 10, text_color = 0x94a3b8 },
    \\          (_item . valid == 1) and { text = "OK", font_size = 9, text_color = 0x3fb950 } or nil,
    \\          (_item . valid == 0) and { text = "BAD", font_size = 9, text_color = 0xda3633 } or nil
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(resultCount) .. " results · " .. tostring(lastParsed), font_size = 10, text_color = 0x64748b }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then entries = __luaMapData0 end
    \\  if __luaMapData1 then results = __luaMapData1 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

