//! Generated by tsz compiler — d28a_string_ops_script [state.zig]
//! Source: d28a_string_ops_script.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

