//! Generated by tsz compiler — d103_ternary_array_sizing [nodes.zig]
//! Source: d103_ternary_array_sizing.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d103_ternary_array_sizing:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

