//! Generated by tsz compiler — d24_chained_state [logic.zig]
//! Source: d24_chained_state.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var step = 0;
    \\function setStep(v) { step = v; if (__luaReady) __luaEval("setStep(" + v + ")"); else __markDirty(); }
    \\var name = "";
    \\function setName(v) { name = v; if (__luaReady) __luaEval("setName(\'" + v + "\')"); else __markDirty(); }
    \\var email = "";
    \\function setEmail(v) { email = v; if (__luaReady) __luaEval("setEmail(\'" + v + "\')"); else __markDirty(); }
    \\var plan = 0;
    \\function setPlan(v) { plan = v; if (__luaReady) __luaEval("setPlan(" + v + ")"); else __markDirty(); }
    \\var confirmed = 0;
    \\function setConfirmed(v) { confirmed = v; if (__luaReady) __luaEval("setConfirmed(" + v + ")"); else __markDirty(); }
    \\var error = "";
    \\function setError(v) { error = v; if (__luaReady) __luaEval("setError(\'" + v + "\')"); else __markDirty(); }
    \\
    \\setStep(0);
    \\setName('');
    \\setEmail('');
    \\setPlan(0);
    \\setConfirmed(0);
    \\setError('');
    \\
    \\function goNext() {
    \\  if (step === 0 && name === '') { setError('Pick a name first'); return; }
    \\  if (step === 1 && email === '') { setError('Pick an email first'); return; }
    \\  if (step === 2 && plan === 0) { setError('Pick a plan first'); return; }
    \\  setError('');
    \\  setStep(step + 1);
    \\}
    \\
    \\function goBack() {
    \\  setError('');
    \\  setStep(step - 1);
    \\}
    \\
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["step"] = 0
    \\step = _state["step"]
    \\function setStep(v) _state["step"] = v; step = v; __syncToJS("step", v); __markDirty() end
    \\_state["name"] = ""
    \\name = _state["name"]
    \\function setName(v) _state["name"] = v; name = v; __syncToJS("name", v); __markDirty() end
    \\_state["email"] = ""
    \\email = _state["email"]
    \\function setEmail(v) _state["email"] = v; email = v; __syncToJS("email", v); __markDirty() end
    \\_state["plan"] = 0
    \\plan = _state["plan"]
    \\function setPlan(v) _state["plan"] = v; plan = v; __syncToJS("plan", v); __markDirty() end
    \\_state["confirmed"] = 0
    \\confirmed = _state["confirmed"]
    \\function setConfirmed(v) _state["confirmed"] = v; confirmed = v; __syncToJS("confirmed", v); __markDirty() end
    \\_state["error"] = ""
    \\error = _state["error"]
    \\function setError(v) _state["error"] = v; error = v; __syncToJS("error", v); __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Signup Wizard", font_size = 16, text_color = 0xe2e8f0 },
    \\    { text = "Step " .. tostring(step + 1) .. " of 4", font_size = 10, text_color = 0x64748b },
    \\    (step == 0) and { style = { gap = 8, padding = 16, background_color = 0x1e293b, border_radius = 8 }, children = {
    \\      { text = "Choose your name", font_size = 13, text_color = 0xcbd5e1 },
    \\      { style = { flex_direction = "row", gap = 6 }, children = {
    \\        { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, lua_on_press = "setName(\"Alice\"); setError(\"\")", children = {
    \\          { text = "Alice", font_size = 12, text_color = 0xe2e8f0 }
    \\        } },
    \\        { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, lua_on_press = "setName(\"Bob\"); setError(\"\")", children = {
    \\          { text = "Bob", font_size = 12, text_color = 0xe2e8f0 }
    \\        } }
    \\      } },
    \\      { text = "selected: " .. tostring(name), font_size = 10, text_color = 0x94a3b8 }
    \\    } } or nil,
    \\    (step == 1) and { style = { gap = 8, padding = 16, background_color = 0x1e293b, border_radius = 8 }, children = {
    \\      { text = "Choose your email", font_size = 13, text_color = 0xcbd5e1 },
    \\      { style = { flex_direction = "row", gap = 6 }, children = {
    \\        { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, lua_on_press = "setEmail(\"a@test.com\"); setError(\"\")", children = {
    \\          { text = "a@test.com", font_size = 12, text_color = 0xe2e8f0 }
    \\        } },
    \\        { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, lua_on_press = "setEmail(\"b@test.com\"); setError(\"\")", children = {
    \\          { text = "b@test.com", font_size = 12, text_color = 0xe2e8f0 }
    \\        } }
    \\      } },
    \\      { text = "selected: " .. tostring(email), font_size = 10, text_color = 0x94a3b8 }
    \\    } } or nil,
    \\    (step == 2) and { style = { gap = 8, padding = 16, background_color = 0x1e293b, border_radius = 8 }, children = {
    \\      { text = "Choose plan", font_size = 13, text_color = 0xcbd5e1 },
    \\      { style = { padding = 10, background_color = (plan == 1) and 0x1d4ed8 or 0x334155, border_radius = 6 }, lua_on_press = "setPlan(1); setError(\"\")", children = {
    \\        { text = "Free", font_size = 12, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 10, background_color = (plan == 2) and 0x1d4ed8 or 0x334155, border_radius = 6 }, lua_on_press = "setPlan(2); setError(\"\")", children = {
    \\        { text = "Pro $10/mo", font_size = 12, text_color = 0xe2e8f0 }
    \\      } }
    \\    } } or nil,
    \\    (step == 3) and { style = { gap = 8, padding = 16, background_color = 0x1e293b, border_radius = 8 }, children = {
    \\      { text = "Confirm", font_size = 13, text_color = 0xcbd5e1 },
    \\      { text = "Name: " .. tostring(name), font_size = 11, text_color = 0x94a3b8 },
    \\      { text = "Email: " .. tostring(email), font_size = 11, text_color = 0x94a3b8 },
    \\      { text = "Plan: " .. tostring(plan), font_size = 11, text_color = 0x94a3b8 },
    \\      (confirmed == 1) and { text = "Account created!", font_size = 13, text_color = 0x22c55e } or nil
    \\    } } or nil,
    \\    (error ~= "") and { text = tostring(error), font_size = 11, text_color = 0xef4444 } or nil,
    \\    { style = { flex_direction = "row", gap = 8 }, children = {
    \\      (step > 0) and { style = { padding = 8, background_color = 0x475569, border_radius = 6 }, js_on_press = "goBack ( )", children = {
    \\        { text = "Back", font_size = 12, text_color = 0xe2e8f0 }
    \\      } } or nil,
    \\      (step < 3) and { style = { padding = 8, background_color = 0x2563eb, border_radius = 6 }, js_on_press = "goNext ( )", children = {
    \\        { text = "Next", font_size = 12, text_color = 0xffffff }
    \\      } } or nil,
    \\      (step == 3) and { style = { padding = 8, background_color = 0x16a34a, border_radius = 6 }, lua_on_press = "setConfirmed(1)", children = {
    \\        { text = "Submit", font_size = 12, text_color = 0xffffff }
    \\      } } or nil
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

