//! Generated by tsz compiler — d24_chained_state [nodes.zig]
//! Source: d24_chained_state.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d24_chained_state:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

