//! Generated by tsz compiler — d24_chained_state [state.zig]
//! Source: d24_chained_state.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

