//! Generated by tsz compiler — d39_declare_function [state.zig]
//! Source: d39_declare_function.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

