//! Generated by tsz compiler — d17_map_conditional_card [state.zig]
//! Source: d17_map_conditional_card.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

