//! Generated by tsz compiler — map [logic.zig]
//! Source: map.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var items = [];
    \\function setItems(v) { items = v; }
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x1a1a2e, padding = 16, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "Items", font_size = 24, text_color = 0xffffff },
    \\    __mapLoop(items, function(_item, _i)
    \\      return { style = { padding = 12, background_color = 0x0f3460, border_radius = 8, flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\        { text = tostring(_item.label), text_color = 0xffffff },
    \\        { text = "#" .. tostring((_i - 1)), font_size = 10, text_color = 0x888888 }
    \\      } }
    \\    end)
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

