//! Generated by tsz compiler — d101_filter_sort_map_render [logic.zig]
//! Source: d101_filter_sort_map_render.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var activeGroup = 3;
    \\function setActiveGroup(v) { activeGroup = v; if (__luaReady) __luaEval("setActiveGroup(" + v + ")"); else __markDirty(); }
    \\var showOffline = 0;
    \\function setShowOffline(v) { showOffline = v; if (__luaReady) __luaEval("setShowOffline(" + v + ")"); else __markDirty(); }
    \\var limit = 4;
    \\function setLimit(v) { limit = v; if (__luaReady) __luaEval("setLimit(" + v + ")"); else __markDirty(); }
    \\var selected = "";
    \\function setSelected(v) { selected = v; if (__luaReady) __luaEval("setSelected(\'" + v + "\')"); else __markDirty(); }
    \\var tapCount = 0;
    \\function setTapCount(v) { tapCount = v; if (__luaReady) __luaEval("setTapCount(" + v + ")"); else __markDirty(); }
    \\var commands = [ { label : "" , group : 0 , online : 0 , score : 0 } ];
    \\function setCommands(v) { commands = v; __markDirty(); }
    \\var items = [];
    \\var items = [
    \\  { label: 'Open incident room', group: 0, online: 1, score: 88 },
    \\  { label: 'Rebuild search index', group: 2, online: 1, score: 54 },
    \\  { label: 'Deploy billing-worker', group: 2, online: 0, score: 91 },
    \\  { label: 'Invite design reviewers', group: 1, online: 1, score: 63 },
    \\  { label: 'Rotate stale API keys', group: 2, online: 1, score: 97 },
    \\  { label: 'Open changelog draft', group: 1, online: 1, score: 72 },
    \\  { label: 'Tail auth-service logs', group: 0, online: 0, score: 79 },
    \\  { label: 'Sync support macros', group: 1, online: 1, score: 58 }
    \\];
    \\setCommands(items);
    \\setSelected(items[0].label);
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["activeGroup"] = 3
    \\activeGroup = _state["activeGroup"]
    \\function setActiveGroup(v) _state["activeGroup"] = v; activeGroup = v; __syncToJS("activeGroup", v); __markDirty() end
    \\_state["showOffline"] = 0
    \\showOffline = _state["showOffline"]
    \\function setShowOffline(v) _state["showOffline"] = v; showOffline = v; __syncToJS("showOffline", v); __markDirty() end
    \\_state["limit"] = 4
    \\limit = _state["limit"]
    \\function setLimit(v) _state["limit"] = v; limit = v; __syncToJS("limit", v); __markDirty() end
    \\_state["selected"] = ""
    \\selected = _state["selected"]
    \\function setSelected(v) _state["selected"] = v; selected = v; __syncToJS("selected", v); __markDirty() end
    \\_state["tapCount"] = 0
    \\tapCount = _state["tapCount"]
    \\function setTapCount(v) _state["tapCount"] = v; tapCount = v; __syncToJS("tapCount", v); __markDirty() end
    \\
    \\commands = {}
    \\function setCommands(v) commands = v; __markDirty() end
    \\items = {}
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x020617, padding = 20, gap = 12, overflow = "hidden" }, children = {
    \\    { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\      { text = "Render Pipeline", font_size = 16, text_color = 0xf8fafc },
    \\      { text = tostring(tapCount) .. " picks", font_size = 10, text_color = 0x64748b }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 6, flex_wrap = "wrap" }, children = {
    \\      { style = { padding = 8, border_radius = 999, background_color = (activeGroup == 3) and 0x1d4ed8 or 0x111827 }, lua_on_press = "setActiveGroup(3)", children = {
    \\        { text = "All", font_size = 9, text_color = 0xf8fafc }
    \\      } },
    \\      { style = { padding = 8, border_radius = 999, background_color = (activeGroup == 0) and 0x1d4ed8 or 0x111827 }, lua_on_press = "setActiveGroup(0)", children = {
    \\        { text = "Ops", font_size = 9, text_color = 0xf8fafc }
    \\      } },
    \\      { style = { padding = 8, border_radius = 999, background_color = (activeGroup == 1) and 0x1d4ed8 or 0x111827 }, lua_on_press = "setActiveGroup(1)", children = {
    \\        { text = "Design", font_size = 9, text_color = 0xf8fafc }
    \\      } },
    \\      { style = { padding = 8, border_radius = 999, background_color = (activeGroup == 2) and 0x1d4ed8 or 0x111827 }, lua_on_press = "setActiveGroup(2)", children = {
    \\        { text = "Infra", font_size = 9, text_color = 0xf8fafc }
    \\      } },
    \\      { style = { padding = 8, border_radius = 999, background_color = (showOffline == 1) and 0x7c3aed or 0x111827 }, lua_on_press = "setShowOffline(showOffline == 0 and 1 or 0)", children = {
    \\        { text = (showOffline == 1) and "Offline On" or "Offline Off", font_size = 9, text_color = 0xf8fafc }
    \\      } },
    \\      { style = { padding = 8, border_radius = 999, background_color = 0x111827 }, lua_on_press = "setLimit(limit == 4 and 6 or 4)", children = {
    \\        { text = "Top " .. tostring(limit), font_size = 9, text_color = 0xf8fafc }
    \\      } }
    \\    } },
    \\    { text = "List is rendered by chaining filter, sort, slice, and map inline in JSX.", font_size = 11, text_color = 0x94a3b8 },
    \\    { style = { gap = 8 }, children = {
    \\      __mapLoop(commands, function(_item, _i)
    \\        return { style = { padding = 10, border_radius = 10, border_width = 1, border_color = ((selected == "_item.label")) and 0x60a5fa or 0x1f2937, background_color = ((selected == "_item.label")) and 0x172554 or 0x111827 }, lua_on_press = "setSelected('" .. (_item.label) .. "'); setTapCount(tapCount + 1)", children = {
    \\          { style = { flex_direction = "row", justify_content = "space_between", align_items = "center" }, children = {
    \\            { style = { gap = 2 }, children = {
    \\              { text = tostring(_item.label), font_size = 11, text_color = 0xf8fafc },
    \\              { text = tostring(_item.group), font_size = 9, text_color = 0x64748b }
    \\            } },
    \\            { style = { align_items = "end", gap = 2 }, children = {
    \\              { text = tostring((_item.online == 1) and "online" or "offline"), font_size = 9, text_color = (_item.online == 1) and 0x34d399 or 0xf87171 },
    \\              { text = "score " .. tostring(_item.score), font_size = 9, text_color = 0x94a3b8 }
    \\            } }
    \\          } }
    \\        } }
    \\      end)
    \\    } },
    \\    { style = { padding = 12, border_radius = 10, background_color = 0x111827, gap = 4 }, children = {
    \\      { text = "Selected command", font_size = 11, text_color = 0x94a3b8 },
    \\      { text = tostring(selected), font_size = 13, text_color = 0xf8fafc }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then commands = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

