//! Generated by tsz compiler — d86_settings_page [app.zig]
//! Source: d86_settings_page.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const engine = api.engine;
const qjs_runtime = api.qjs_runtime;
const luajit_runtime = api.luajit_runtime;
const nodes = @import("nodes.zig");
const st = @import("state.zig");
const logic = @import("logic.zig");

fn _appInit() void {
    luajit_runtime.setMapWrapper(0, @ptrCast(&nodes._root));
    // OA data synced on first tick (after logic.JS_LOGIC loads)
    state.markDirty();
}

var _first_render: bool = true;
fn _appTick(now: u32) void {
    _ = now;
    if (_first_render or state.isDirty()) {
        if (_first_render) {
            qjs_runtime.syncScalarToLua("activeTab");
            qjs_runtime.syncScalarToLua("darkMode");
            qjs_runtime.syncScalarToLua("fontSize");
            qjs_runtime.syncScalarToLua("notifications");
            qjs_runtime.syncScalarToLua("autoSave");
            qjs_runtime.syncScalarToLua("language");
            qjs_runtime.syncScalarToLua("dirty");
            qjs_runtime.syncScalarToLua("saved");
        }
        luajit_runtime.callGlobal("__render");
        state.clearDirty();
        _first_render = false;
    }
}

export fn app_get_root() *Node { return &nodes._root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return logic.JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return logic.JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return logic.LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return logic.LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d86_settings_page"; }

export fn app_state_count() usize { return 8; }

pub fn main() !void {
    try engine.run(.{
        .title = "d86_settings_page",
        .root = &nodes._root,
        .init = _appInit,
        .tick = _appTick,
        .js_logic = logic.JS_LOGIC,
        .lua_logic = logic.LUA_LOGIC,
    });
}

// ── Smith debug log ──
// DBG: [INLINE PROBE] Inlining component: NavItem bodyPos: 368 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: NavItem bodyPos: 368 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: NavItem bodyPos: 368 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: Toggle bodyPos: 172 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: Toggle bodyPos: 172 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: Toggle bodyPos: 172 token: < kind: 41
