//! Generated by tsz compiler — radar_chart [logic.zig]
//! Source: radar_chart.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC = "";

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { gap = 12, padding = 24, background_color = 0x0d1117, height = -1, width = -1, flex_direction = "column", overflow = "hidden" }, children = {
    \\    { text = "Radar Chart", font_size = 20, text_color = 0xe6edf3 },
    \\    { text = "5-axis spider chart — Graph.Path pentagon grid + data polygon", font_size = 12, text_color = 0x8b949e },
    \\    { style = { gap = 8, padding = 16, border_color = 0x30363d, border_width = 1, border_radius = 8, background_color = 0x161b22, flex_direction = "column", flex_grow = 1, overflow = "auto" }, children = {
    \\      { style = { flex_grow = 1 }, graph_container = true, canvas_view_x = 0, canvas_view_y = 0, canvas_view_zoom = 1, canvas_view_set = true, children = {
    \\        { text_color = 0x30363d, canvas_path = true, canvas_path_d = "M 0,-100 L 95,-31 L 59,81 L -59,81 L -95,-31 Z", canvas_stroke_width = 1 },
    \\        { text_color = 0x21262d, canvas_path = true, canvas_path_d = "M 0,-75 L 71,-23 L 44,61 L -44,61 L -71,-23 Z", canvas_stroke_width = 1 },
    \\        { text_color = 0x21262d, canvas_path = true, canvas_path_d = "M 0,-50 L 48,-16 L 30,40 L -30,40 L -48,-16 Z", canvas_stroke_width = 1 },
    \\        { text_color = 0x21262d, canvas_path = true, canvas_path_d = "M 0,-25 L 24,-8 L 15,20 L -15,20 L -24,-8 Z", canvas_stroke_width = 1 },
    \\        { text_color = 0x30363d, canvas_path = true, canvas_path_d = "M 0,0 L 0,-100", canvas_stroke_width = 1 },
    \\        { text_color = 0x30363d, canvas_path = true, canvas_path_d = "M 0,0 L 95,-31", canvas_stroke_width = 1 },
    \\        { text_color = 0x30363d, canvas_path = true, canvas_path_d = "M 0,0 L 59,81", canvas_stroke_width = 1 },
    \\        { text_color = 0x30363d, canvas_path = true, canvas_path_d = "M 0,0 L -59,81", canvas_stroke_width = 1 },
    \\        { text_color = 0x30363d, canvas_path = true, canvas_path_d = "M 0,0 L -95,-31", canvas_stroke_width = 1 },
    \\        { text_color = 0x3b82f6, canvas_path = true, canvas_path_d = "M 0,-85 L 67,-22 L 35,49 L -53,73 L -48,-16 Z", canvas_stroke_width = 2 },
    \\        { canvas_node = true, canvas_gx = 0, canvas_gy = -115, canvas_gw = 60, canvas_gh = 18, children = {
    \\          { text = "Speed", font_size = 11, text_color = 0xe6edf3 }
    \\        } },
    \\        { canvas_node = true, canvas_gx = 112, canvas_gy = -31, canvas_gw = 55, canvas_gh = 18, children = {
    \\          { text = "Power", font_size = 11, text_color = 0xe6edf3 }
    \\        } },
    \\        { canvas_node = true, canvas_gx = 72, canvas_gy = 96, canvas_gw = 70, canvas_gh = 18, children = {
    \\          { text = "Defense", font_size = 11, text_color = 0xe6edf3 }
    \\        } },
    \\        { canvas_node = true, canvas_gx = -72, canvas_gy = 96, canvas_gw = 55, canvas_gh = 18, children = {
    \\          { text = "Magic", font_size = 11, text_color = 0xe6edf3 }
    \\        } },
    \\        { canvas_node = true, canvas_gx = -112, canvas_gy = -31, canvas_gw = 45, canvas_gh = 18, children = {
    \\          { text = "Luck", font_size = 11, text_color = 0xe6edf3 }
    \\        } }
    \\      } },
    \\      { style = { flex_wrap = "wrap", gap = 16, flex_direction = "row" }, children = {
    \\        { style = { gap = 6, align_items = "center", flex_direction = "row" }, children = {
    \\          { style = { border_radius = 4, height = 8, width = 8, background_color = 0x3b82f6 } },
    \\          { text = "Speed 85  Power 70  Defense 60  Magic 90  Luck 50", font_size = 11, text_color = 0x8b949e }
    \\        } }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

