//! Generated by tsz compiler — radar_chart [state.zig]
//! Source: radar_chart.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

