//! Generated by tsz compiler — d66_chained_calls [logic.zig]
//! Source: d66_chained_calls.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var logLen = 0;
    \\function setLogLen(v) { logLen = v; if (__luaReady) __luaEval("setLogLen(" + v + ")"); else __markDirty(); }
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var items = [ { name : "" , processed : "" } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var log = [ { step : "" , result : "" } ];
    \\function setLog(v) { log = v; __markDirty(); }
    \\var entries = [];
    \\var logEntries = [];
    \\
    \\function upper(s) {
    \\  return s.toUpperCase !== undefined ? s.toUpperCase() : s;
    \\}
    \\
    \\function prefix(s, p) {
    \\  return p + s;
    \\}
    \\
    \\function truncate(s, len) {
    \\  if (s.length <= len) return s;
    \\  return s.slice(0, len) + '...';
    \\}
    \\
    \\function process(name) {
    \\  var step1 = upper(name);
    \\  var step2 = prefix(step1, '[');
    \\  var step3 = step2 + ']';
    \\  var step4 = truncate(step3, 12);
    \\
    \\  logEntries.push({ step: 'upper', result: step1 });
    \\  logEntries.push({ step: 'prefix', result: step2 });
    \\  logEntries.push({ step: 'concat', result: step3 });
    \\  logEntries.push({ step: 'truncate', result: step4 });
    \\  setLog(logEntries);
    \\  setLogLen(logEntries.length);
    \\
    \\  entries.push({ name: name, processed: step4 });
    \\  setItems(entries);
    \\  setOutput('processed: ' + name + ' → ' + step4);
    \\}
    \\
    \\function processAll() {
    \\  var names = ['Alpha', 'Bravo', 'Charlie', 'DeltaForce', 'Echo'];
    \\  for (var i = 0; i < names.length; i++) {
    \\    process(names[i]);
    \\  }
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["logLen"] = 0
    \\logLen = _state["logLen"]
    \\function setLogLen(v) _state["logLen"] = v; logLen = v; __syncToJS("logLen", v); __markDirty() end
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\log = {}
    \\function setLog(v) log = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Chained Calls", font_size = 16, text_color = 0xe2e8f0 },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "process ( \"Hello\" )", children = {
    \\        { text = "Process \"Hello\"", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "process ( \"World\" )", children = {
    \\        { text = "Process \"World\"", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x1e40af, border_radius = 6 }, js_on_press = "processAll ( )", children = {
    \\        { text = "Process All", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 12 }, children = {
    \\      { style = { flex_grow = 1, gap = 4, overflow = "auto" }, children = {
    \\        { text = "Results", font_size = 10, text_color = 0x94a3b8 },
    \\        __mapLoop(items, function(_item, _i)
    \\          return { style = { flex_direction = "row", justify_content = "space_between", padding = 6, background_color = 0x1e293b, border_radius = 4 }, children = {
    \\            { text = tostring(_item.name), font_size = 10, text_color = 0xe2e8f0 },
    \\            { text = tostring(_item.processed), font_size = 10, text_color = 0x6ee7b7 }
    \\          } }
    \\        end)
    \\      } },
    \\      { style = { flex_grow = 1, gap = 4, overflow = "auto" }, children = {
    \\        { text = "Log (" .. tostring(logLen) .. ")", font_size = 10, text_color = 0x94a3b8 },
    \\        __mapLoop(log, function(_item, _i)
    \\          return { style = { flex_direction = "row", gap = 6, padding = 4 }, children = {
    \\            { text = tostring(_item.step), font_size = 8, text_color = 0x475569 },
    \\            { text = tostring(_item.result), font_size = 8, text_color = 0x94a3b8 }
    \\          } }
    \\        end)
    \\      } }
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x64748b }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  if __luaMapData1 then log = __luaMapData1 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

