//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: /tmp/test-hex.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime /tmp/test-hex.tsz
//! To modify: edit test-hex.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Module state ───────────────────────────────────
const A: usize = 0xFFFD;
const B: usize = 0x80;
const C: usize = 0xFF;
var x: u32 = 0;

// ── Functions ──────────────────────────────────────

pub fn test() u32 {
    return 0xDEAD;
}
