//! Generated by tsz compiler — d110_component_ternary_map_handler [state.zig]
//! Source: d110_component_ternary_map_handler.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

