//! Generated by tsz compiler — 14_percentage_sizing [nodes.zig]
//! Source: 14_percentage_sizing.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:14_percentage_sizing:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

