//! Generated by tsz compiler — d68_todo_app [logic.zig]
//! Source: d68_todo_app.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var filter = 0;
    \\function setFilter(v) { filter = v; if (__luaReady) __luaEval("setFilter(" + v + ")"); else __markDirty(); }
    \\var nextId = 0;
    \\function setNextId(v) { nextId = v; if (__luaReady) __luaEval("setNextId(" + v + ")"); else __markDirty(); }
    \\var totalCount = 0;
    \\function setTotalCount(v) { totalCount = v; if (__luaReady) __luaEval("setTotalCount(" + v + ")"); else __markDirty(); }
    \\var doneCount = 0;
    \\function setDoneCount(v) { doneCount = v; if (__luaReady) __luaEval("setDoneCount(" + v + ")"); else __markDirty(); }
    \\var activeCount = 0;
    \\function setActiveCount(v) { activeCount = v; if (__luaReady) __luaEval("setActiveCount(" + v + ")"); else __markDirty(); }
    \\var todos = [ { text : "" , done : 0 } ];
    \\function setTodos(v) { todos = v; __markDirty(); }
    \\var items = [];
    \\var items = [
    \\  { text: 'Learn TSZ', done: 1 },
    \\  { text: 'Write conformance tests', done: 1 },
    \\  { text: 'Pass all tests', done: 0 },
    \\  { text: 'Ship v1', done: 0 }
    \\];
    \\setTodos(items);
    \\setNextId(items.length);
    \\recalc();
    \\
    \\function recalc() {
    \\  var d = 0;
    \\  for (var i = 0; i < items.length; i++) {
    \\    if (items[i].done === 1) d++;
    \\  }
    \\  setDoneCount(d);
    \\  setActiveCount(items.length - d);
    \\  setTotalCount(items.length);
    \\}
    \\
    \\function addTodo(text) {
    \\  items.push({ text: text, done: 0 });
    \\  setTodos(items);
    \\  setNextId(nextId + 1);
    \\  recalc();
    \\}
    \\
    \\function toggleTodo(idx) {
    \\  items[idx].done = items[idx].done === 1 ? 0 : 1;
    \\  setTodos(items);
    \\  recalc();
    \\}
    \\
    \\function removeTodo(idx) {
    \\  var result = [];
    \\  for (var i = 0; i < items.length; i++) {
    \\    if (i !== idx) result.push(items[i]);
    \\  }
    \\  items = result;
    \\  setTodos(items);
    \\  recalc();
    \\}
    \\
    \\function clearDone() {
    \\  var result = [];
    \\  for (var i = 0; i < items.length; i++) {
    \\    if (items[i].done === 0) result.push(items[i]);
    \\  }
    \\  items = result;
    \\  setTodos(items);
    \\  recalc();
    \\}
    \\
    \\function toggleAll() {
    \\  var allDone = doneCount === totalCount ? 1 : 0;
    \\  var target = allDone === 1 ? 0 : 1;
    \\  for (var i = 0; i < items.length; i++) {
    \\    items[i].done = target;
    \\  }
    \\  setTodos(items);
    \\  recalc();
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["filter"] = 0
    \\filter = _state["filter"]
    \\function setFilter(v) _state["filter"] = v; filter = v; __syncToJS("filter", v); __markDirty() end
    \\_state["nextId"] = 0
    \\nextId = _state["nextId"]
    \\function setNextId(v) _state["nextId"] = v; nextId = v; __syncToJS("nextId", v); __markDirty() end
    \\_state["totalCount"] = 0
    \\totalCount = _state["totalCount"]
    \\function setTotalCount(v) _state["totalCount"] = v; totalCount = v; __syncToJS("totalCount", v); __markDirty() end
    \\_state["doneCount"] = 0
    \\doneCount = _state["doneCount"]
    \\function setDoneCount(v) _state["doneCount"] = v; doneCount = v; __syncToJS("doneCount", v); __markDirty() end
    \\_state["activeCount"] = 0
    \\activeCount = _state["activeCount"]
    \\function setActiveCount(v) _state["activeCount"] = v; activeCount = v; __syncToJS("activeCount", v); __markDirty() end
    \\
    \\todos = {}
    \\function setTodos(v) todos = v; __markDirty() end
    \\items = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x1a1a2e, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "todos", font_size = 20, text_color = 0xe2e8f0 },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 8, background_color = 0x3b82f6, border_radius = 6 }, js_on_press = "addTodo ( \"New task \" + nextId )", children = {
    \\        { text = "Add", font_size = 11, text_color = 0xffffff }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x334155, border_radius = 6 }, js_on_press = "toggleAll ( )", children = {
    \\        { text = "Toggle All", font_size = 11, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 8, background_color = 0xdc2626, border_radius = 6 }, js_on_press = "clearDone ( )", children = {
    \\        { text = "Clear Done", font_size = 11, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 6, background_color = (filter == 0) and 0x1e40af or 0x334155, border_radius = 4 }, lua_on_press = "setFilter(0)", children = {
    \\        { text = "All (" .. tostring(totalCount) .. ")", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = (filter == 1) and 0x1e40af or 0x334155, border_radius = 4 }, lua_on_press = "setFilter(1)", children = {
    \\        { text = "Active (" .. tostring(activeCount) .. ")", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = (filter == 2) and 0x1e40af or 0x334155, border_radius = 4 }, lua_on_press = "setFilter(2)", children = {
    \\        { text = "Done (" .. tostring(doneCount) .. ")", font_size = 10, text_color = 0xe2e8f0 }
    \\      } }
    \\    } },
    \\    (totalCount == 0) and { style = { padding = 20, align_items = "center" }, children = {
    \\      { text = "No todos. Add one!", font_size = 13, text_color = 0x475569 }
    \\    } } or nil,
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(todos, function(_item, _i)
    \\        return { children = {
    \\          (filter == 0) and { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 10, background_color = 0x16213e, border_radius = 6 }, children = {
    \\            { style = { flex_direction = "row", gap = 8, align_items = "center", flex_grow = 1 }, js_on_press = "toggleTodo(" .. ((_i - 1)) .. ")", children = {
    \\              (_item . done == 1) and { text = "[x]", font_size = 14, text_color = 0x22c55e } or nil,
    \\              (_item . done == 0) and { text = "[ ]", font_size = 14, text_color = 0x475569 } or nil,
    \\              { text = tostring(_item.text), font_size = 12, text_color = (_item.done == 1) and 0x64748b or 0xe2e8f0 }
    \\            } },
    \\            { style = { padding = 4 }, js_on_press = "removeTodo(" .. ((_i - 1)) .. ")", children = {
    \\              { text = "X", font_size = 10, text_color = 0xef4444 }
    \\            } }
    \\          } } or nil,
    \\          (filter == 1) and { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 10, background_color = 0x16213e, border_radius = 6 }, children = {
    \\            { style = { flex_direction = "row", gap = 8, align_items = "center", flex_grow = 1 }, js_on_press = "toggleTodo(" .. ((_i - 1)) .. ")", children = {
    \\              { text = "[ ]", font_size = 14, text_color = 0x475569 },
    \\              { text = tostring(_item.text), font_size = 12, text_color = 0xe2e8f0 }
    \\            } },
    \\            { style = { padding = 4 }, js_on_press = "removeTodo(" .. ((_i - 1)) .. ")", children = {
    \\              { text = "X", font_size = 10, text_color = 0xef4444 }
    \\            } }
    \\          } } or nil,
    \\          (filter == 2) and { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 10, background_color = 0x16213e, border_radius = 6 }, children = {
    \\            { style = { flex_direction = "row", gap = 8, align_items = "center", flex_grow = 1 }, js_on_press = "toggleTodo(" .. ((_i - 1)) .. ")", children = {
    \\              { text = "[x]", font_size = 14, text_color = 0x22c55e },
    \\              { text = tostring(_item.text), font_size = 12, text_color = 0x64748b }
    \\            } },
    \\            { style = { padding = 4 }, js_on_press = "removeTodo(" .. ((_i - 1)) .. ")", children = {
    \\              { text = "X", font_size = 10, text_color = 0xef4444 }
    \\            } }
    \\          } } or nil
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(activeCount) .. " items left", font_size = 10, text_color = 0x64748b }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then todos = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

