//! Generated by tsz compiler — d135_flex_scroll_with_maps [logic.zig]
//! Source: d135_flex_scroll_with_maps.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var catCount = 0;
    \\function setCatCount(v) { catCount = v; if (__luaReady) __luaEval("setCatCount(" + v + ")"); else __markDirty(); }
    \\var laneCount = 0;
    \\function setLaneCount(v) { laneCount = v; if (__luaReady) __luaEval("setLaneCount(" + v + ")"); else __markDirty(); }
    \\var fileCount = 0;
    \\function setFileCount(v) { fileCount = v; if (__luaReady) __luaEval("setFileCount(" + v + ")"); else __markDirty(); }
    \\var failCount = 0;
    \\function setFailCount(v) { failCount = v; if (__luaReady) __luaEval("setFailCount(" + v + ")"); else __markDirty(); }
    \\var cats = [ { name : "" , count : 0 , color : 0x484f58 } ];
    \\function setCats(v) { cats = v; __markDirty(); }
    \\var lanes = [ { name : "" , pass : 0 , fail : 0 , total : 0 } ];
    \\function setLanes(v) { lanes = v; __markDirty(); }
    \\var files = [ { name : "" , count : 0 , color : 0x484f58 } ];
    \\function setFiles(v) { files = v; __markDirty(); }
    \\var failures = [ { name : "" , status : "" } ];
    \\function setFailures(v) { failures = v; __markDirty(); }
    \\setCats([
    \\  { name: 'flight_fail', count: 114, color: 0xf85149 },
    \\  { name: 'preflight_blocked', count: 18, color: 0xd29922 },
    \\  { name: 'zig_fail', count: 24, color: 0xf0883e }
    \\]);
    \\setCatCount(3);
    \\
    \\setLanes([
    \\  { name: 'mixed', pass: 154, fail: 96, total: 250 },
    \\  { name: 'wpt-flex', pass: 75, fail: 0, total: 75 },
    \\  { name: 'chad', pass: 16, fail: 24, total: 40 },
    \\  { name: 'lscript', pass: 9, fail: 28, total: 37 },
    \\  { name: 'soup', pass: 13, fail: 8, total: 21 },
    \\  { name: 'root', pass: 1, fail: 0, total: 1 }
    \\]);
    \\setLaneCount(6);
    \\
    \\var f = [];
    \\var fi = 0;
    \\while (fi < 15) {
    \\  f.push({ name: 'tsz/compiler', count: 40 + fi, color: 0xd2a8ff });
    \\  fi = fi + 1;
    \\}
    \\setFiles(f);
    \\setFileCount(f.length);
    \\
    \\var fl = [];
    \\var fli = 0;
    \\while (fli < 25) {
    \\  fl.push({ name: 'test_' + fli, status: 'flight_fail' });
    \\  fli = fli + 1;
    \\}
    \\setFailures(fl);
    \\setFailCount(fl.length);
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["catCount"] = 0
    \\catCount = _state["catCount"]
    \\function setCatCount(v) _state["catCount"] = v; catCount = v; __syncToJS("catCount", v); __markDirty() end
    \\_state["laneCount"] = 0
    \\laneCount = _state["laneCount"]
    \\function setLaneCount(v) _state["laneCount"] = v; laneCount = v; __syncToJS("laneCount", v); __markDirty() end
    \\_state["fileCount"] = 0
    \\fileCount = _state["fileCount"]
    \\function setFileCount(v) _state["fileCount"] = v; fileCount = v; __syncToJS("fileCount", v); __markDirty() end
    \\_state["failCount"] = 0
    \\failCount = _state["failCount"]
    \\function setFailCount(v) _state["failCount"] = v; failCount = v; __syncToJS("failCount", v); __markDirty() end
    \\
    \\cats = {}
    \\function setCats(v) cats = v; __markDirty() end
    \\lanes = {}
    \\function setLanes(v) lanes = v; __markDirty() end
    \\files = {}
    \\function setFiles(v) files = v; __markDirty() end
    \\failures = {}
    \\function setFailures(v) failures = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x0d1117, flex_direction = "column", overflow = "hidden" }, children = {
    \\    { style = { padding = 10, background_color = 0x161b22, border_color = 0x30363d, border_width = 1 }, children = {
    \\      { text = "d135: Flex scroll with maps", font_size = 14, text_color = 0xe6edf3 }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 8, padding = 10 }, children = {
    \\      { style = { padding = 8, background_color = 0x161b22, border_radius = 6, border_width = 1, border_color = 0x30363d, flex_grow = 1, flex_basis = 0, align_items = "center", overflow = "auto" }, children = {
    \\        { text = "268", font_size = 16, text_color = 0xe6edf3 },
    \\        { text = "COMPILED", font_size = 9, text_color = 0x8b949e }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x161b22, border_radius = 6, border_width = 1, border_color = 0x30363d, flex_grow = 1, flex_basis = 0, align_items = "center", overflow = "auto" }, children = {
    \\        { text = "156", font_size = 16, text_color = 0xf85149 },
    \\        { text = "FAILED", font_size = 9, text_color = 0x8b949e }
    \\      } },
    \\      { style = { padding = 8, background_color = 0x161b22, border_radius = 6, border_width = 1, border_color = 0x30363d, flex_grow = 1, flex_basis = 0, align_items = "center", overflow = "auto" }, children = {
    \\        { text = "62%", font_size = 16, text_color = 0x3fb950 },
    \\        { text = "PASS RATE", font_size = 9, text_color = 0x8b949e }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", gap = 10, flex_grow = 1, padding_left = 10, padding_right = 10, padding_bottom = 10, overflow = "auto" }, children = {
    \\      { style = { flex_direction = "column", gap = 10, flex_grow = 1, flex_basis = 0, overflow = "auto" }, children = {
    \\        { style = { border_color = 0x30363d, border_width = 1, border_radius = 6, background_color = 0x161b22, padding = 12, gap = 6, flex_direction = "column" }, children = {
    \\          { text = "Commit Density", font_size = 13, text_color = 0xe6edf3 },
    \\          { style = { flex_direction = "row", gap = 4 }, children = {
    \\            { style = { width = 12, height = 12, border_radius = 2, background_color = 0x3fb950 } },
    \\            { style = { width = 12, height = 12, border_radius = 2, background_color = 0x26a641 } },
    \\            { style = { width = 12, height = 12, border_radius = 2, background_color = 0x006d32 } },
    \\            { style = { width = 12, height = 12, border_radius = 2, background_color = 0x0e4429 } }
    \\          } }
    \\        } },
    \\        { style = { border_color = 0x30363d, border_width = 1, border_radius = 6, background_color = 0x161b22, padding = 12, gap = 6, flex_direction = "column" }, children = {
    \\          { text = "Build Performance", font_size = 13, text_color = 0xe6edf3 },
    \\          { style = { padding_bottom = 2, padding_top = 2, align_items = "center", gap = 8, flex_direction = "row" }, children = {
    \\            { text = "Avg total", font_size = 11, text_color = 0xe6edf3 },
    \\            { text = "309ms", font_size = 11, text_color = 0x8b949e }
    \\          } },
    \\          { style = { padding_bottom = 2, padding_top = 2, align_items = "center", gap = 8, flex_direction = "row" }, children = {
    \\            { text = "Throughput", font_size = 11, text_color = 0xe6edf3 },
    \\            { text = "376 lines/sec", font_size = 11, text_color = 0x8b949e }
    \\          } }
    \\        } },
    \\        { style = { border_color = 0x30363d, border_width = 1, border_radius = 6, background_color = 0x161b22, padding = 12, gap = 6, flex_direction = "column" }, children = {
    \\          { text = "Failure Categories", font_size = 13, text_color = 0xe6edf3 },
    \\          __mapLoop(cats, function(_item, _i)
    \\            return { style = { padding_bottom = 2, padding_top = 2, align_items = "center", gap = 8, flex_direction = "row" }, children = {
    \\              { style = { border_radius = 5, height = 10, width = 10, background_color = _item.color } },
    \\              { text = tostring(_item.name), font_size = 11, text_color = 0xe6edf3 },
    \\              { style = { flex_grow = 1 } },
    \\              { text = tostring(_item.count), font_size = 11, text_color = 0x8b949e }
    \\            } }
    \\          end)
    \\        } },
    \\        { style = { border_color = 0x30363d, border_width = 1, border_radius = 6, background_color = 0x161b22, padding = 12, gap = 6, flex_direction = "column", flex_grow = 1, flex_basis = 0, overflow = "auto" }, children = {
    \\          { text = "Files by Area", font_size = 13, text_color = 0xe6edf3 },
    \\          { style = { overflow = "scroll", flex_grow = 1, flex_basis = 0 }, children = {
    \\            __mapLoop(files, function(_item, _i)
    \\              return { style = { padding_bottom = 2, padding_top = 2, align_items = "center", gap = 8, flex_direction = "row" }, children = {
    \\                { style = { border_radius = 5, height = 10, width = 10, background_color = _item.color } },
    \\                { text = tostring(_item.name), font_size = 11, text_color = 0xe6edf3 },
    \\                { style = { flex_grow = 1 } },
    \\                { text = tostring(_item.count), font_size = 11, text_color = 0x8b949e }
    \\              } }
    \\            end)
    \\          }, scroll_y = ((_scrollY and _scrollY[1]) or 0), scroll_persist_slot = 1 }
    \\        } }
    \\      } },
    \\      { style = { flex_direction = "column", gap = 10, flex_grow = 1, flex_basis = 0, overflow = "auto" }, children = {
    \\        { style = { border_color = 0x30363d, border_width = 1, border_radius = 6, background_color = 0x161b22, padding = 12, gap = 6, flex_direction = "column" }, children = {
    \\          { text = "By Lane", font_size = 13, text_color = 0xe6edf3 },
    \\          { style = { flex_direction = "row", gap = 4, padding_left = 8, padding_right = 8, padding_bottom = 4 }, children = {
    \\            { style = { width = 70 }, children = {
    \\              { text = "LANE", font_size = 9, text_color = 0x484f58 }
    \\            } },
    \\            { style = { width = 35 }, children = {
    \\              { text = "PASS", font_size = 9, text_color = 0x3fb950 }
    \\            } },
    \\            { style = { width = 35 }, children = {
    \\              { text = "FAIL", font_size = 9, text_color = 0xf85149 }
    \\            } },
    \\            { style = { flex_grow = 1 } },
    \\            { text = "TOTAL", font_size = 9, text_color = 0x484f58 }
    \\          } },
    \\          __mapLoop(lanes, function(_item, _i)
    \\            return { style = { padding_bottom = 2, padding_top = 2, align_items = "center", gap = 8, flex_direction = "row" }, children = {
    \\              { style = { width = 70 }, children = {
    \\                { text = tostring(_item.name), font_size = 11, text_color = 0xe6edf3 }
    \\              } },
    \\              { style = { width = 35 }, children = {
    \\                { text = tostring(_item.pass), font_size = 10, text_color = 0x3fb950 }
    \\              } },
    \\              { style = { width = 35 }, children = {
    \\                { text = tostring(_item.fail), font_size = 10, text_color = 0xf85149 }
    \\              } },
    \\              { style = { flex_grow = 1 } },
    \\              { text = tostring(_item.total), font_size = 11, text_color = 0x8b949e }
    \\            } }
    \\          end)
    \\        } },
    \\        { style = { border_color = 0x30363d, border_width = 1, border_radius = 6, background_color = 0x161b22, padding = 12, gap = 6, flex_direction = "column", flex_grow = 1, flex_basis = 0, overflow = "auto" }, children = {
    \\          { text = "Recent Failures", font_size = 13, text_color = 0xe6edf3 },
    \\          { style = { overflow = "scroll", flex_grow = 1, flex_basis = 0 }, children = {
    \\            __mapLoop(failures, function(_item, _i)
    \\              return { style = { padding_bottom = 2, padding_top = 2, align_items = "center", gap = 8, flex_direction = "row" }, children = {
    \\                { text = tostring(_item.name), font_size = 10, text_color = 0xf85149 },
    \\                { style = { flex_grow = 1 } },
    \\                { text = tostring(_item.status), font_size = 9, text_color = 0xf85149 }
    \\              } }
    \\            end)
    \\          }, scroll_y = ((_scrollY and _scrollY[2]) or 0), scroll_persist_slot = 2 }
    \\        } }
    \\      } }
    \\    } },
    \\    { style = { padding = 6, background_color = 0x161b22, border_color = 0x30363d, border_width = 1 }, children = {
    \\      { text = "status bar", font_size = 9, text_color = 0x8b949e }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then cats = __luaMapData0 end
    \\  if __luaMapData1 then lanes = __luaMapData1 end
    \\  if __luaMapData2 then files = __luaMapData2 end
    \\  if __luaMapData3 then failures = __luaMapData3 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

