//! Generated by tsz compiler — d25_map_conditional_classifier [nodes.zig]
//! Source: d25_map_conditional_classifier.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d25_map_conditional_classifier:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

