//! Generated by tsz compiler — d115_conditional_component_in_nested_map [logic.zig]
//! Source: d115_conditional_component_in_nested_map.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var expandedRow = 0;
    \\function setExpandedRow(v) { expandedRow = v; if (__luaReady) __luaEval("setExpandedRow(" + v + ")"); else __markDirty(); }
    \\var selectedDetail = 0;
    \\function setSelectedDetail(v) { selectedDetail = v; if (__luaReady) __luaEval("setSelectedDetail(" + v + ")"); else __markDirty(); }
    \\var clickCount = 0;
    \\function setClickCount(v) { clickCount = v; if (__luaReady) __luaEval("setClickCount(" + v + ")"); else __markDirty(); }
    \\var rows = [ { title : "" , status : 0 } ];
    \\function setRows(v) { rows = v; __markDirty(); }
    \\var details = [ { label : "" , value : 0 , rowIdx : 0 } ];
    \\function setDetails(v) { details = v; __markDirty(); }
    \\
    \\
    \\  setRows([
    \\    { title: "Authentication", status: 1 },
    \\    { title: "Payment Gateway", status: 2 },
    \\    { title: "User Service", status: 1 },
    \\    { title: "Notification", status: 0 },
    \\    { title: "Analytics", status: 1 }
    \\  ]);
    \\  setDetails([
    \\    { label: "Login endpoint", value: 200, rowIdx: 0 },
    \\    { label: "OAuth flow", value: 180, rowIdx: 0 },
    \\    { label: "Token refresh", value: 95, rowIdx: 0 },
    \\    { label: "Charge API", value: 450, rowIdx: 1 },
    \\    { label: "Refund API", value: 120, rowIdx: 1 },
    \\    { label: "Profile read", value: 50, rowIdx: 2 },
    \\    { label: "Profile write", value: 340, rowIdx: 2 },
    \\    { label: "Search users", value: 220, rowIdx: 2 },
    \\    { label: "Batch export", value: 890, rowIdx: 2 },
    \\    { label: "Push service", value: 30, rowIdx: 3 },
    \\    { label: "Email queue", value: 150, rowIdx: 3 },
    \\    { label: "Event ingest", value: 75, rowIdx: 4 },
    \\    { label: "Dashboard", value: 110, rowIdx: 4 }
    \\  ]);
    \\
    \\
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["expandedRow"] = 0
    \\expandedRow = _state["expandedRow"]
    \\function setExpandedRow(v) _state["expandedRow"] = v; expandedRow = v; __syncToJS("expandedRow", v); __markDirty() end
    \\_state["selectedDetail"] = 0
    \\selectedDetail = _state["selectedDetail"]
    \\function setSelectedDetail(v) _state["selectedDetail"] = v; selectedDetail = v; __syncToJS("selectedDetail", v); __markDirty() end
    \\_state["clickCount"] = 0
    \\clickCount = _state["clickCount"]
    \\function setClickCount(v) _state["clickCount"] = v; clickCount = v; __syncToJS("clickCount", v); __markDirty() end
    \\
    \\rows = {}
    \\function setRows(v) rows = v; __markDirty() end
    \\details = {}
    \\function setDetails(v) details = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x0f172a, padding = 12, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "Expandable Table", font_size = 16, text_color = 0xf1f5f9 },
    \\    { text = "expanded: " .. tostring(expandedRow) .. " | detail: " .. tostring(selectedDetail) .. " | clicks: " .. tostring(clickCount), font_size = 9, text_color = 0x475569 },
    \\    { style = { overflow = "scroll", flex_grow = 1, gap = 4 }, children = {
    \\      __mapLoop(rows, function(_item, _i)
    \\        return { style = { gap = 4 }, children = {
    \\          { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 12, background_color = 0x1a1a2e, border_radius = 6 }, lua_on_press = "setExpandedRow(" .. ((_i - 1)) .. ")", children = {
    \\            { style = { flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\              (expandedRow == (_i - 1)) and { text = "v", font_size = 11, text_color = 0x22d3ee } or nil,
    \\              (expandedRow ~= (_i - 1)) and { text = ">", font_size = 11, text_color = 0x475569 } or nil,
    \\              { text = tostring(_item.title), font_size = 13, text_color = 0xe2e8f0 }
    \\            } },
    \\            { style = { flex_direction = "row", gap = 4, align_items = "center" }, children = {
    \\              (_item . status == 0) and { style = { width = 8, height = 8, border_radius = 4, background_color = 0x6b7280 } } or nil,
    \\              (_item . status == 1) and { style = { width = 8, height = 8, border_radius = 4, background_color = 0x22c55e } } or nil,
    \\              (_item . status == 2) and { style = { width = 8, height = 8, border_radius = 4, background_color = 0xef4444 } } or nil,
    \\              { text = "#" .. tostring((_i - 1)), font_size = 10, text_color = 0x475569 }
    \\            } }
    \\          } },
    \\          (expandedRow == (_i - 1)) and { style = { background_color = 0x1e293b, border_radius = 6, padding = 8, gap = 4, margin_left = 16 }, children = {
    \\            { text = "Details for: " .. tostring(_item.title), font_size = 10, text_color = 0x64748b },
    \\            __mapLoop(details, function(_nitem, _ni)
    \\              return (_nitem . rowIdx == (_i - 1)) and { style = { flex_direction = "row", justify_content = "space_between", padding = 6, border_radius = 3 }, lua_on_press = "setSelectedDetail(" .. ((_ni - 1)) .. "); setClickCount(clickCount + 1)", children = {
    \\                  (selectedDetail == (_ni - 1)) and { style = { flex_direction = "row", justify_content = "space_between", background_color = 0x0e7490, border_radius = 3, padding = 6, flex_grow = 1, overflow = "auto" }, children = {
    \\                    { text = tostring(_nitem.label), font_size = 10, text_color = 0xecfeff },
    \\                    { text = tostring(_nitem.value), font_size = 10, text_color = 0xa5f3fc }
    \\                  } } or nil,
    \\                  (selectedDetail ~= (_ni - 1)) and { style = { flex_direction = "row", justify_content = "space_between", padding = 6, flex_grow = 1, overflow = "auto" }, children = {
    \\                    { text = tostring(_nitem.label), font_size = 10, text_color = 0x94a3b8 },
    \\                    { text = tostring(_nitem.value), font_size = 10, text_color = 0x64748b }
    \\                  } } or nil
    \\                } } or nil
    \\            end)
    \\          } } or nil
    \\        } }
    \\      end)
    \\    }, scroll_y = ((_scrollY and _scrollY[1]) or 0), scroll_persist_slot = 1 }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then rows = __luaMapData0 end
    \\  if __luaMapData1 then details = __luaMapData1 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

