//! Generated by tsz compiler — spotify [logic.zig]
//! Source: spotify.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var trackCount = 0;
    \\function setTrackCount(v) { trackCount = v; }
    \\var tracks = [];
    \\function setTracks(v) { tracks = v; }
    \\
    \\// Spotify clone — 20 hardcoded tracks with per-field data.
    \\
    \\
    \\
    \\
    \\function loadData() {
    \\  var songs = [
    \\    { title: 'Bohemian Rhapsody', artist: 'Queen', duration: '5:55' },
    \\    { title: 'Blinding Lights', artist: 'The Weeknd', duration: '3:20' },
    \\    { title: 'Shape of You', artist: 'Ed Sheeran', duration: '3:53' },
    \\    { title: 'Someone Like You', artist: 'Adele', duration: '4:45' },
    \\    { title: 'Billie Jean', artist: 'Michael Jackson', duration: '4:54' },
    \\    { title: 'Smells Like Teen Spirit', artist: 'Nirvana', duration: '5:01' },
    \\    { title: 'Hotel California', artist: 'Eagles', duration: '6:30' },
    \\    { title: 'Sweet Child O Mine', artist: 'Guns N Roses', duration: '5:56' },
    \\    { title: 'Lose Yourself', artist: 'Eminem', duration: '5:26' },
    \\    { title: 'Rolling in the Deep', artist: 'Adele', duration: '3:48' },
    \\    { title: 'Stairway to Heaven', artist: 'Led Zeppelin', duration: '8:02' },
    \\    { title: 'Imagine', artist: 'John Lennon', duration: '3:04' },
    \\    { title: 'Wonderwall', artist: 'Oasis', duration: '4:18' },
    \\    { title: 'Superstition', artist: 'Stevie Wonder', duration: '4:26' },
    \\    { title: 'Hey Jude', artist: 'The Beatles', duration: '7:11' },
    \\    { title: 'Redbone', artist: 'Childish Gambino', duration: '5:27' },
    \\    { title: 'Take On Me', artist: 'a-ha', duration: '3:48' },
    \\    { title: 'Dreams', artist: 'Fleetwood Mac', duration: '4:14' },
    \\    { title: 'Dont Stop Believin', artist: 'Journey', duration: '4:11' },
    \\    { title: 'Purple Rain', artist: 'Prince', duration: '8:41' }
    \\  ];
    \\
    \\  var tl = [];
    \\  for (var i = 0; songs.length > i; i = i + 1) {
    \\    var s = songs[i];
    \\    var num = i + 1;
    \\    tl.push({
    \\      num: '' + num,
    \\      title: s.title,
    \\      artist: s.artist,
    \\      duration: s.duration,
    \\      isPlaying: i === 0 ? 1 : 0,
    \\      titleColor: i === 0 ? 0x1DB954 : 0xffffff,
    \\      numColor: i === 0 ? 0x1DB954 : 0xb3b3b3
    \\    });
    \\  }
    \\  setTracks(tl);
    \\  setTrackCount(tl.length);
    \\}
    \\
    \\loadData();
    \\
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["trackCount"] = 0
    \\trackCount = _state["trackCount"]
    \\function setTrackCount(v) _state["setTrackCount"] = v; trackCount = v; __markDirty() end
    \\
    \\tracks = {}
    \\function setTracks(v) tracks = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { flex_direction = "column", width = -1, height = -1, background_color = 0x121212, overflow = "hidden" }, children = {
    \\    { style = { flex_direction = "row", flex_grow = 1, overflow = "auto" }, children = {
    \\      { style = { flex_direction = "column", width = 200, background_color = 0x000000, padding_top = 16 }, children = {
    \\        { style = { padding_left = 16, padding_bottom = 20 }, children = {
    \\          { text = "Spotify", font_size = 16, text_color = 0x1db954 }
    \\        } },
    \\        { style = { padding_left = 16, padding_right = 16, padding_bottom = 4 }, children = {
    \\          { text = "Home", font_size = 11, text_color = 0xffffff }
    \\        } },
    \\        { style = { padding_left = 16, padding_right = 16, padding_bottom = 4 }, children = {
    \\          { text = "Search", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_right = 16, padding_bottom = 16 }, children = {
    \\          { text = "Your Library", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_bottom = 6 }, children = {
    \\          { text = "PLAYLISTS", font_size = 9, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "Discover Weekly", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "Release Radar", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "Chill Vibes", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "Workout Mix", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "Road Trip", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "Late Night Jazz", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "90s Throwback", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "Focus Flow", font_size = 11, text_color = 0xffffff }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 16, padding_bottom = 6 }, children = {
    \\          { text = "LIKED SONGS", font_size = 9, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { padding_left = 16, padding_top = 3, padding_bottom = 3 }, children = {
    \\          { text = "342 songs", font_size = 11, text_color = 0xb3b3b3 }
    \\        } }
    \\      } },
    \\      { style = { flex_direction = "column", flex_grow = 1, background_color = 0x121212, overflow = "auto" }, children = {
    \\        { style = { flex_direction = "row", align_items = "center", gap = 16, padding_left = 24, padding_right = 24, padding_top = 20, padding_bottom = 16 }, children = {
    \\          { style = { width = 80, height = 80, background_color = 0x282828, border_radius = 4 } },
    \\          { style = { flex_direction = "column", gap = 4 }, children = {
    \\            { text = "PLAYLIST", font_size = 9, text_color = 0xb3b3b3 },
    \\            { text = "Greatest Hits", font_size = 24, text_color = 0xffffff },
    \\            { text = "Various Artists - " .. tostring(trackCount) .. " songs, about 1 hr 40 min", font_size = 10, text_color = 0xb3b3b3 }
    \\          } }
    \\        } },
    \\        { style = { flex_direction = "row", align_items = "center", gap = 12, padding_left = 24, padding_bottom = 16 }, children = {
    \\          { style = { width = 40, height = 40, border_radius = 20, background_color = 0x1db954, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\            { text = "▶", font_size = 16, text_color = 0x000000 }
    \\          } },
    \\          { text = "Shuffle", font_size = 11, text_color = 0xb3b3b3 },
    \\          { text = "...", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { flex_direction = "row", padding_left = 24, padding_right = 24, padding_bottom = 8 }, children = {
    \\          { style = { width = 32 }, children = {
    \\            { text = "#", font_size = 9, text_color = 0xb3b3b3 }
    \\          } },
    \\          { style = { flex_grow = 1, overflow = "auto" }, children = {
    \\            { text = "TITLE", font_size = 9, text_color = 0xb3b3b3 }
    \\          } },
    \\          { text = "DURATION", font_size = 9, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { height = 1, background_color = 0x282828, margin_left = 24, margin_right = 24 } },
    \\        { style = { overflow = "scroll", flex_grow = 1, padding_left = 24, padding_right = 24 }, children = {
    \\          __mapLoop(tracks, function(_item, _i)
    \\            return { style = { flex_direction = "row", align_items = "center", padding_top = 6, padding_bottom = 6 }, children = {
    \\              { style = { width = 32 }, children = {
    \\                { text = tostring(_item.num), font_size = 11, text_color = 0x000000 }
    \\              } },
    \\              { style = { flex_direction = "column", flex_grow = 1, gap = 2, overflow = "auto" }, children = {
    \\                { text = tostring(_item.title), font_size = 11, text_color = 0x000000 },
    \\                { text = tostring(_item.artist), font_size = 9, text_color = 0xb3b3b3 }
    \\              } },
    \\              { text = tostring(_item.duration), font_size = 11, text_color = 0xb3b3b3 }
    \\            } }
    \\          end)
    \\        } }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", align_items = "center", height = 60, background_color = 0x181818, border_color = 0x282828, border_width = 1, padding_left = 12, padding_right = 12, overflow = "auto" }, children = {
    \\      { style = { flex_direction = "row", align_items = "center", gap = 10, width = 200 }, children = {
    \\        { style = { width = 40, height = 40, background_color = 0x282828, border_radius = 4 } },
    \\        { style = { flex_direction = "column", gap = 2 }, children = {
    \\          { text = "Bohemian Rhapsody", font_size = 11, text_color = 0xffffff },
    \\          { text = "Queen", font_size = 9, text_color = 0xb3b3b3 }
    \\        } }
    \\      } },
    \\      { style = { flex_direction = "column", align_items = "center", flex_grow = 1, gap = 4, overflow = "auto" }, children = {
    \\        { style = { flex_direction = "row", align_items = "center", gap = 16 }, children = {
    \\          { text = "|&lt;&lt;", font_size = 11, text_color = 0xb3b3b3 },
    \\          { style = { width = 28, height = 28, border_radius = 14, background_color = 0xffffff, align_items = "center", justify_content = "center", overflow = "auto" }, children = {
    \\            { text = "▶", font_size = 12, text_color = 0x000000 }
    \\          } },
    \\          { text = "&gt;&gt;|", font_size = 11, text_color = 0xb3b3b3 }
    \\        } },
    \\        { style = { flex_direction = "row", align_items = "center", gap = 8 }, children = {
    \\          { text = "1:42", font_size = 9, text_color = 0xb3b3b3 },
    \\          { style = { width = 300, height = 4, background_color = 0x535353, border_radius = 2, overflow = "auto" }, children = {
    \\            { style = { width = 90, height = 4, background_color = 0x1db954, border_radius = 2 } }
    \\          } },
    \\          { text = "5:55", font_size = 9, text_color = 0xb3b3b3 }
    \\        } }
    \\      } },
    \\      { style = { flex_direction = "row", align_items = "center", gap = 6, width = 120, justify_content = "end" }, children = {
    \\        { text = "Vol", font_size = 9, text_color = 0xb3b3b3 },
    \\        { style = { width = 80, height = 4, background_color = 0x535353, border_radius = 2, overflow = "auto" }, children = {
    \\          { style = { width = 56, height = 4, background_color = 0x1db954, border_radius = 2 } }
    \\        } }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then tracks = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

