//! Generated by tsz compiler — d03_conditional_wrapping_map [state.zig]
//! Source: d03_conditional_wrapping_map.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

