//! Generated by tsz compiler — ifttt_lab [state.zig]
//! Source: ifttt_lab.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

