//! Generated by tsz compiler — d23_empty_array [nodes.zig]
//! Source: d23_empty_array.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d23_empty_array:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

