//! Generated by tsz compiler — d23_empty_array [state.zig]
//! Source: d23_empty_array.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

