//! Generated by tsz compiler — 18_shrink_basis_interaction [logic.zig]
//! Source: 18_shrink_basis_interaction.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, flex_direction = "column", padding = 10, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "WPT: shrink + basis interaction", font_size = 18 },
    \\    { text = "VERIFY: Shrink proportional to basis, shrink:0 absorbs nothing, all shrink:0 overflows", font_size = 10, text_color = 0x888888 },
    \\    { text = "Shrink proportional to basis (WPT spec behavior)", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 200, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 200, flex_shrink = 1, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "b200 s1", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 100, flex_shrink = 1, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "b100 s1", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "Shrink:0 + shrink:1 — one item absorbs all shrinkage", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 150, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 100, flex_shrink = 0, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "no shrink", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 100, flex_shrink = 1, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "shrinks", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "All shrink:0 — items overflow (no shrinking)", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 150, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 100, flex_shrink = 0, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "100", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 100, flex_shrink = 0, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "100", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "Grow and shrink on same item — basis determines direction", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 300, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 50, flex_grow = 1, flex_shrink = 1, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "grows", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 200, flex_grow = 0, flex_shrink = 1, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "fixed-ish", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

