//! Generated by tsz compiler — 06_flex_shrink [logic.zig]
//! Source: 06_flex_shrink.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, flex_direction = "column", padding = 10, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "WPT: flex-shrink", font_size = 18 },
    \\    { text = "VERIFY: Items shrink to fit container, proportional shrink, shrink:0 refuses to shrink", font_size = 10, text_color = 0x888888 },
    \\    { style = { background_color = 0x0d1117, border_radius = 4, padding = 6, padding_left = 10, padding_right = 10, flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\      { text = "WPT", font_size = 9, text_color = 0x8b949e },
    \\      { text = "flex-shrink", font_size = 10, text_color = 0x58a6ff }
    \\    } },
    \\    { text = "Default shrink — items shrink equally when overflow", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 200, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { width = 100, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "100", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "100", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 40, background_color = 0xff9800, overflow = "auto" }, children = {
    \\        { text = "100", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "Shrink 1:2:1 — middle shrinks twice as much", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 200, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { width = 100, flex_shrink = 1, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "s:1", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, flex_shrink = 2, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "s:2", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, flex_shrink = 1, height = 40, background_color = 0xff9800, overflow = "auto" }, children = {
    \\        { text = "s:1", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "Shrink 0 — item refuses to shrink", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 200, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { width = 100, flex_shrink = 0, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "no shrink", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "shrink", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { width = 100, height = 40, background_color = 0xff9800, overflow = "auto" }, children = {
    \\        { text = "shrink", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

