//! Generated by tsz compiler — d67_conditional_in_map_component [state.zig]
//! Source: d67_conditional_in_map_component.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

