//! Generated by tsz compiler — d73_undefined_checks [state.zig]
//! Source: d73_undefined_checks.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

