//! Generated by tsz compiler — 11_padding_margin [nodes.zig]
//! Source: 11_padding_margin.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:11_padding_margin:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

