//! Generated by tsz compiler — 10_flex_basis [logic.zig]
//! Source: 10_flex_basis.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, flex_direction = "column", padding = 10, gap = 8, overflow = "hidden" }, children = {
    \\    { text = "WPT: flex-basis", font_size = 18 },
    \\    { text = "VERIFY: basis sets initial size, basis+grow distributes remainder, basis:0 is pure ratio", font_size = 10, text_color = 0x888888 },
    \\    { style = { background_color = 0x0d1117, border_radius = 4, padding = 6, padding_left = 10, padding_right = 10, flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\      { text = "WPT", font_size = 9, text_color = 0x8b949e },
    \\      { text = "flex-basis", font_size = 10, text_color = 0x58a6ff }
    \\    } },
    \\    { text = "flex-basis sets initial main size before grow/shrink", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 300, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 100, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "basis:100", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 50, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "basis:50", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 150, height = 40, background_color = 0xff9800, overflow = "auto" }, children = {
    \\        { text = "basis:150", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "flex-basis with flex-grow — grow distributes remaining space", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 400, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 50, flex_grow = 1, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "b50+g1", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 100, flex_grow = 1, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "b100+g1", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 50, flex_grow = 2, height = 40, background_color = 0xff9800, overflow = "auto" }, children = {
    \\        { text = "b50+g2", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "flex-basis 0 with grow — pure proportional sizing", font_size = 11 },
    \\    { style = { flex_direction = "row", width = 300, height = 40, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 0, flex_grow = 1, height = 40, background_color = 0x4caf50, overflow = "auto" }, children = {
    \\        { text = "1/6", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 0, flex_grow = 2, height = 40, background_color = 0x2196f3, overflow = "auto" }, children = {
    \\        { text = "2/6", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 0, flex_grow = 3, height = 40, background_color = 0xff9800, overflow = "auto" }, children = {
    \\        { text = "3/6", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { text = "flex-basis in column direction", font_size = 11 },
    \\    { style = { flex_direction = "column", width = 100, height = 200, background_color = 0x333333, overflow = "auto" }, children = {
    \\      { style = { flex_basis = 40, background_color = 0x4caf50 }, children = {
    \\        { text = "b:40", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 80, background_color = 0x2196f3 }, children = {
    \\        { text = "b:80", font_size = 10, text_color = 0xffffff }
    \\      } },
    \\      { style = { flex_basis = 40, background_color = 0xff9800 }, children = {
    \\        { text = "b:40", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

