//! Generated by tsz compiler — d123_theme_hydra [state.zig]
//! Source: d123_theme_hydra.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

