//! Generated by tsz compiler — d117_same_component_multi_map [nodes.zig]
//! Source: d117_same_component_multi_map.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:d117_same_component_multi_map:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

