//! Generated by tsz compiler — d117_same_component_multi_map [state.zig]
//! Source: d117_same_component_multi_map.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

