//! Generated by tsz compiler — github-issues [logic.zig]
//! Source: github-issues.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var selected = 0;
    \\function setSelected(v) { selected = v; }
    \\var currentFilter = 0;
    \\function setCurrentFilter(v) { currentFilter = v; }
    \\var currentLabel = "";
    \\function setCurrentLabel(v) { currentLabel = v; }
    \\var openCount = 0;
    \\function setOpenCount(v) { openCount = v; }
    \\var closedCount = 0;
    \\function setClosedCount(v) { closedCount = v; }
    \\var visibleCount = 0;
    \\function setVisibleCount(v) { visibleCount = v; }
    \\var issues = [];
    \\function setIssues(v) { issues = v; }
    \\
    \\// GitHub Issues script — hardcoded issue data, filter by open/closed + label
    \\// filter: 0=open, 1=closed
    \\
    \\let _issues = [
    \\  { title: 'Bug: useEffect cleanup runs twice in StrictMode', status: 0, label: 'bug', labelColor: 1, author: 'devguy42', time: '2h ago', comments: 12 },
    \\  { title: 'Feature: Add server actions support', status: 0, label: 'enhancement', labelColor: 2, author: 'sarahdev', time: '5h ago', comments: 34 },
    \\  { title: 'Hydration mismatch with Suspense boundaries', status: 0, label: 'bug', labelColor: 1, author: 'waterbender', time: '8h ago', comments: 7 },
    \\  { title: 'RFC: React Forget compiler', status: 0, label: 'rfc', labelColor: 3, author: 'danabramov', time: '1d ago', comments: 89 },
    \\  { title: 'Concurrent rendering causes flicker on slow devices', status: 0, label: 'bug', labelColor: 1, author: 'mobiledev99', time: '1d ago', comments: 5 },
    \\  { title: 'Add TypeScript 5.4 support to types', status: 0, label: 'types', labelColor: 4, author: 'tsWizard', time: '2d ago', comments: 18 },
    \\  { title: 'useSyncExternalStore missing in react-native', status: 0, label: 'react-native', labelColor: 5, author: 'rnhacker', time: '2d ago', comments: 3 },
    \\  { title: 'Improve error overlay with source maps', status: 0, label: 'dx', labelColor: 6, author: 'errorhunter', time: '3d ago', comments: 21 },
    \\  { title: 'Memory leak in useCallback with closures', status: 0, label: 'bug', labelColor: 1, author: 'gc_master', time: '3d ago', comments: 9 },
    \\  { title: 'Support CSS-in-JS with zero runtime', status: 0, label: 'enhancement', labelColor: 2, author: 'stylelord', time: '4d ago', comments: 45 },
    \\  { title: 'Fix: key prop warning false positive in fragments', status: 1, label: 'bug', labelColor: 1, author: 'keymaster', time: '5d ago', comments: 6 },
    \\  { title: 'Update React DevTools protocol', status: 1, label: 'devtools', labelColor: 7, author: 'debugqueen', time: '5d ago', comments: 11 },
    \\  { title: 'Docs: Migrate to RSC examples', status: 1, label: 'documentation', labelColor: 8, author: 'docwriter', time: '6d ago', comments: 2 },
    \\  { title: 'Remove legacy context API', status: 1, label: 'breaking', labelColor: 9, author: 'cleanupbot', time: '1w ago', comments: 67 },
    \\  { title: 'Add useFormStatus hook', status: 0, label: 'enhancement', labelColor: 2, author: 'formfan', time: '1w ago', comments: 28 },
    \\  { title: 'Fix SSR streaming with error boundaries', status: 1, label: 'bug', labelColor: 1, author: 'streamfix', time: '1w ago', comments: 14 },
    \\  { title: 'Scheduler priority inversion on iOS Safari', status: 0, label: 'bug', labelColor: 1, author: 'safaridev', time: '2w ago', comments: 8 },
    \\  { title: 'Support async server components in testing', status: 0, label: 'testing', labelColor: 10, author: 'testpro', time: '2w ago', comments: 16 },
    \\  { title: 'Tree-shaking improvements for production builds', status: 1, label: 'perf', labelColor: 11, author: 'bundleopt', time: '2w ago', comments: 22 },
    \\  { title: 'Add React.lazy preload API', status: 0, label: 'enhancement', labelColor: 2, author: 'lazyloader', time: '3w ago', comments: 31 }
    \\];
    \\
    \\function rebuild() {
    \\  let filterStatus = currentFilter;
    \\  let filterLabel = currentLabel;
    \\  let visible = [];
    \\  let openCount = 0;
    \\  let closedCount = 0;
    \\  for (let i = 0; i < _issues.length; i++) {
    \\    if (_issues[i].status === 0) openCount++;
    \\    else closedCount++;
    \\    let matchStatus = (filterStatus === 0 && _issues[i].status === 0) || (filterStatus === 1 && _issues[i].status === 1);
    \\    if (!matchStatus) continue;
    \\    if (filterLabel !== '' && _issues[i].label !== filterLabel) continue;
    \\    visible.push(_issues[i]);
    \\  }
    \\  setIssues(visible);
    \\  setOpenCount(openCount);
    \\  setClosedCount(closedCount);
    \\  setVisibleCount(visible.length);
    \\}
    \\
    \\function filterOpen() { setCurrentFilter(0); rebuild(); }
    \\function filterClosed() { setCurrentFilter(1); rebuild(); }
    \\function filterByLabel(lbl) { setCurrentLabel(lbl); rebuild(); }
    \\function clearLabelFilter() { setCurrentLabel(''); rebuild(); }
    \\function selectIssue(idx) { setSelected(idx); }
    \\
    \\// init
    \\rebuild();
    \\
    \\
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["selected"] = 0
    \\selected = _state["selected"]
    \\function setSelected(v) _state["setSelected"] = v; selected = v; __markDirty() end
    \\_state["currentFilter"] = 0
    \\currentFilter = _state["currentFilter"]
    \\function setCurrentFilter(v) _state["setCurrentFilter"] = v; currentFilter = v; __markDirty() end
    \\_state["currentLabel"] = ""
    \\currentLabel = _state["currentLabel"]
    \\function setCurrentLabel(v) _state["setCurrentLabel"] = v; currentLabel = v; __markDirty() end
    \\_state["openCount"] = 0
    \\openCount = _state["openCount"]
    \\function setOpenCount(v) _state["setOpenCount"] = v; openCount = v; __markDirty() end
    \\_state["closedCount"] = 0
    \\closedCount = _state["closedCount"]
    \\function setClosedCount(v) _state["setClosedCount"] = v; closedCount = v; __markDirty() end
    \\_state["visibleCount"] = 0
    \\visibleCount = _state["visibleCount"]
    \\function setVisibleCount(v) _state["setVisibleCount"] = v; visibleCount = v; __markDirty() end
    \\
    \\issues = {}
    \\function setIssues(v) issues = v; __markDirty() end
    \\
    \\function App()
    \\  return { style = { width = -1, height = -1, background_color = 0x0d1117, flex_direction = "column", overflow = "hidden" }, children = {
    \\    { style = { padding = 16, border_color = 0x30363d, border_width = 1, gap = 4 }, children = {
    \\      { style = { flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\        { text = "facebook", font_size = 14, text_color = 0x58a6ff },
    \\        { text = "/", font_size = 14, text_color = 0x8b949e },
    \\        { text = "react", font_size = 14, text_color = 0x58a6ff }
    \\      } },
    \\      { style = { flex_direction = "row", gap = 16, padding_top = 12 }, children = {
    \\        { style = { padding_bottom = 8, border_color = 0xf78166, border_width = 0 }, children = {
    \\          { text = "Code", font_size = 12, text_color = 0x8b949e }
    \\        } },
    \\        { style = { padding_bottom = 8, border_color = 0xf78166, border_width = 2 }, children = {
    \\          { text = "Issues", font_size = 12, text_color = 0xf0f6fc }
    \\        } },
    \\        { style = { padding_bottom = 8, border_color = 0xf78166, border_width = 0 }, children = {
    \\          { text = "Pull requests", font_size = 12, text_color = 0x8b949e }
    \\        } }
    \\      } }
    \\    } },
    \\    { style = { flex_direction = "row", flex_grow = 1, overflow = "auto" }, children = {
    \\      { style = { width = 200, padding = 16, gap = 12, border_color = 0x30363d, border_width = 1 }, children = {
    \\        { text = "Filters", font_size = 11, text_color = 0x8b949e },
    \\        { style = { gap = 4 }, children = {
    \\          { style = { flex_direction = "row", gap = 6, padding = 6, border_radius = 4, background_color = 0x161b22 }, js_on_press = "filterOpen ( )", children = {
    \\            { text = "O", font_size = 11, text_color = 0x3fb950 },
    \\            { text = "Open " .. tostring(openCount), font_size = 11, text_color = 0xc9d1d9 }
    \\          } },
    \\          { style = { flex_direction = "row", gap = 6, padding = 6, border_radius = 4, background_color = 0x161b22 }, js_on_press = "filterClosed ( )", children = {
    \\            { text = "C", font_size = 11, text_color = 0xa371f7 },
    \\            { text = "Closed " .. tostring(closedCount), font_size = 11, text_color = 0xc9d1d9 }
    \\          } }
    \\        } },
    \\        { text = "Labels", font_size = 11, text_color = 0x8b949e },
    \\        { style = { gap = 2 }, children = {
    \\          { style = { padding = 4, border_radius = 3 }, js_on_press = "filterByLabel ( \"bug\" )", children = {
    \\            { text = "bug", font_size = 10, text_color = 0xe5534b }
    \\          } },
    \\          { style = { padding = 4, border_radius = 3 }, js_on_press = "filterByLabel ( \"enhancement\" )", children = {
    \\            { text = "enhancement", font_size = 10, text_color = 0xa371f7 }
    \\          } },
    \\          { style = { padding = 4, border_radius = 3 }, js_on_press = "filterByLabel ( \"rfc\" )", children = {
    \\            { text = "rfc", font_size = 10, text_color = 0xd29922 }
    \\          } },
    \\          { style = { padding = 4, border_radius = 3 }, js_on_press = "filterByLabel ( \"documentation\" )", children = {
    \\            { text = "documentation", font_size = 10, text_color = 0x4493f8 }
    \\          } },
    \\          { style = { padding = 4, border_radius = 3 }, js_on_press = "clearLabelFilter ( )", children = {
    \\            { text = "Clear filter", font_size = 10, text_color = 0x8b949e }
    \\          } }
    \\        } },
    \\        { style = { height = 1, background_color = 0x30363d } },
    \\        { text = tostring(visibleCount) .. " shown", font_size = 10, text_color = 0x484f58 }
    \\      } },
    \\      { style = { flex_grow = 1, flex_direction = "column", overflow = "auto" }, children = {
    \\        { style = { flex_direction = "row", padding = 12, gap = 8, border_color = 0x30363d, border_width = 1, background_color = 0x161b22 }, children = {
    \\          (currentFilter == 0) and { text = tostring(openCount) .. " Open", font_size = 11, text_color = 0xf0f6fc } or nil,
    \\          (currentFilter == 1) and { text = tostring(closedCount) .. " Closed", font_size = 11, text_color = 0xf0f6fc } or nil
    \\        } },
    \\        { style = { overflow = "scroll", flex_grow = 1 }, children = {
    \\          __mapLoop(issues, function(_item, _i)
    \\            return { style = { flex_direction = "row", padding = 12, gap = 10, border_color = 0x30363d, border_width = 1, align_items = "center" }, js_on_press = "selectIssue ( idx )", children = {
    \\              (_item . status == 0) and { text = "O", font_size = 14, text_color = 0x3fb950 } or nil,
    \\              (_item . status == 1) and { text = "C", font_size = 14, text_color = 0xa371f7 } or nil,
    \\              { style = { flex_grow = 1, gap = 4, overflow = "auto" }, children = {
    \\                { text = tostring(_item.title), font_size = 13, text_color = 0xc9d1d9 },
    \\                { style = { flex_direction = "row", gap = 6, align_items = "center" }, children = {
    \\                  { style = { background_color = 0x30363d, border_radius = 10, padding_left = 6, padding_right = 6, padding_top = 1, padding_bottom = 1 }, children = {
    \\                    { text = tostring(_item.label), font_size = 9, text_color = 0xc9d1d9 }
    \\                  } },
    \\                  { text = tostring(_item.author), font_size = 10, text_color = 0x484f58 },
    \\                  { text = tostring(_item.time), font_size = 10, text_color = 0x484f58 }
    \\                } }
    \\              } },
    \\              { style = { flex_direction = "row", gap = 4, align_items = "center" }, children = {
    \\                { text = tostring(_item.comments), font_size = 10, text_color = 0x484f58 }
    \\              } }
    \\            } }
    \\          end)
    \\        } }
    \\      } }
    \\    } }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then issues = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

