//! Generated by tsz compiler — github-issues [nodes.zig]
//! Source: github-issues.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// ── Generated node tree ──
// [origin:github-issues:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1 } };

