//! Generated by tsz compiler — d19_polymorphic_map [state.zig]
//! Source: d19_polymorphic_map.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

