//! Generated by tsz compiler — d40_type_annotations [logic.zig]
//! Source: d40_type_annotations.tsz


// ── Embedded JS logic ──
pub const JS_LOGIC =
    \\var __luaReady = false;
    \\var name = "";
    \\function setName(v) { name = v; if (__luaReady) __luaEval("setName(\'" + v + "\')"); else __markDirty(); }
    \\var score = 0;
    \\function setScore(v) { score = v; if (__luaReady) __luaEval("setScore(" + v + ")"); else __markDirty(); }
    \\var ratio = 0;
    \\function setRatio(v) { ratio = v; if (__luaReady) __luaEval("setRatio(" + v + ")"); else __markDirty(); }
    \\var active = 0;
    \\function setActive(v) { active = v; if (__luaReady) __luaEval("setActive(" + v + ")"); else __markDirty(); }
    \\var output = "";
    \\function setOutput(v) { output = v; if (__luaReady) __luaEval("setOutput(\'" + v + "\')"); else __markDirty(); }
    \\var items = [ { title : "" , done : 0 , priority : 0 , tag : "" } ];
    \\function setItems(v) { items = v; __markDirty(); }
    \\var tasks = [];
    \\setName('Alice');
    \\setScore(100);
    \\setActive(1);
    \\
    \\var tasks = [
    \\  { title: 'Write tests', done: 0, priority: 2, tag: 'dev' },
    \\  { title: 'Fix bug #42', done: 1, priority: 1, tag: 'bugfix' },
    \\  { title: 'Code review', done: 0, priority: 0, tag: 'dev' },
    \\  { title: 'Deploy v2', done: 0, priority: 2, tag: 'ops' },
    \\  { title: 'Update docs', done: 1, priority: 0, tag: 'docs' }
    \\];
    \\setItems(tasks);
    \\
    \\function toggleDone(idx) {
    \\  tasks[idx].done = tasks[idx].done === 1 ? 0 : 1;
    \\  setItems(tasks);
    \\  var doneCount = 0;
    \\  for (var i = 0; i < tasks.length; i++) {
    \\    if (tasks[i].done === 1) doneCount++;
    \\  }
    \\  setOutput(doneCount + '/' + tasks.length + ' done');
    \\  setScore(doneCount * 20);
    \\}
    \\
    \\function filterByTag(tag) {
    \\  var result = [];
    \\  for (var i = 0; i < tasks.length; i++) {
    \\    if (tasks[i].tag === tag) result.push(tasks[i]);
    \\  }
    \\  setItems(result);
    \\  setOutput('filtered: ' + tag + ' (' + result.length + ')');
    \\}
    \\
    \\function showAll() {
    \\  setItems(tasks);
    \\  setOutput('showing all');
    \\}
;

// ── Embedded Lua logic ──
pub const LUA_LOGIC =
    \\local _state = {}
    \\function _getState(k) return _state[k] end
    \\function _setState(k, v) _state[k] = v; __markDirty() end
    \\
    \\function __mapLoop(arr, fn)
    \\  if not arr then return nil end
    \\  local r = {}
    \\  for i, item in ipairs(arr) do
    \\    r[#r + 1] = fn(item, i)
    \\  end
    \\  r.__isMapResult = true
    \\  return r
    \\end
    \\
    \\function __flattenChildren(children)
    \\  if not children then return {} end
    \\  local flat = {}
    \\  for _, child in ipairs(children) do
    \\    if type(child) == "table" and child.__isMapResult then
    \\      for _, mc in ipairs(child) do flat[#flat + 1] = mc end
    \\    elseif child ~= nil then
    \\      flat[#flat + 1] = child
    \\    end
    \\  end
    \\  return flat
    \\end
    \\
    \\_state["name"] = ""
    \\name = _state["name"]
    \\function setName(v) _state["name"] = v; name = v; __syncToJS("name", v); __markDirty() end
    \\_state["score"] = 0
    \\score = _state["score"]
    \\function setScore(v) _state["score"] = v; score = v; __syncToJS("score", v); __markDirty() end
    \\_state["ratio"] = 0
    \\ratio = _state["ratio"]
    \\function setRatio(v) _state["ratio"] = v; ratio = v; __syncToJS("ratio", v); __markDirty() end
    \\_state["active"] = 0
    \\active = _state["active"]
    \\function setActive(v) _state["active"] = v; active = v; __syncToJS("active", v); __markDirty() end
    \\_state["output"] = ""
    \\output = _state["output"]
    \\function setOutput(v) _state["output"] = v; output = v; __syncToJS("output", v); __markDirty() end
    \\
    \\items = {}
    \\function setItems(v) items = v; __markDirty() end
    \\tasks = {}
    \\
    \\function App()
    \\  return { style = { background_color = 0x0f172a, padding = 20, width = -1, height = -1, gap = 12, overflow = "hidden" }, children = {
    \\    { text = "Type Annotations", font_size = 16, text_color = 0xe2e8f0 },
    \\    { style = { flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\      { text = "name: " .. tostring(name), font_size = 12, text_color = 0x94a3b8 },
    \\      { text = "score: " .. tostring(score), font_size = 12, text_color = 0x6ee7b7 },
    \\      (active == 1) and { text = "ACTIVE", font_size = 10, text_color = 0x22c55e } or nil
    \\    } },
    \\    { style = { flex_direction = "row", gap = 6 }, children = {
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "filterByTag ( \"dev\" )", children = {
    \\        { text = "dev", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "filterByTag ( \"bugfix\" )", children = {
    \\        { text = "bugfix", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x334155, border_radius = 4 }, js_on_press = "filterByTag ( \"ops\" )", children = {
    \\        { text = "ops", font_size = 10, text_color = 0xe2e8f0 }
    \\      } },
    \\      { style = { padding = 6, background_color = 0x1e40af, border_radius = 4 }, js_on_press = "showAll ( )", children = {
    \\        { text = "All", font_size = 10, text_color = 0xffffff }
    \\      } }
    \\    } },
    \\    { style = { gap = 4 }, children = {
    \\      __mapLoop(items, function(_item, _i)
    \\        return { style = { flex_direction = "row", justify_content = "space_between", align_items = "center", padding = 8, background_color = 0x1e293b, border_radius = 4 }, js_on_press = "toggleDone(" .. ((_i - 1)) .. ")", children = {
    \\          { style = { flex_direction = "row", gap = 8, align_items = "center" }, children = {
    \\            (_item . done == 1) and { text = "[x]", font_size = 12, text_color = 0x22c55e } or nil,
    \\            (_item . done == 0) and { text = "[ ]", font_size = 12, text_color = 0x475569 } or nil,
    \\            { text = tostring(_item.title), font_size = 11, text_color = 0xe2e8f0 }
    \\          } },
    \\          { style = { flex_direction = "row", gap = 6, align_items = "center" }, children = {
    \\            { text = tostring(_item.tag), font_size = 9, text_color = 0x7c3aed },
    \\            (_item . priority == 2) and { text = "HIGH", font_size = 9, text_color = 0xef4444 } or nil,
    \\            (_item . priority == 1) and { text = "MED", font_size = 9, text_color = 0xf59e0b } or nil,
    \\            (_item . priority == 0) and { text = "LOW", font_size = 9, text_color = 0x475569 } or nil
    \\          } }
    \\        } }
    \\      end)
    \\    } },
    \\    { text = tostring(output), font_size = 10, text_color = 0x64748b }
    \\  } }
    \\end
    \\
    \\function __render()
    \\  __clearLuaNodes()
    \\  if __luaMapData0 then items = __luaMapData0 end
    \\  local tree = App()
    \\  if __mw0 then __declareChildren(__mw0, { tree }) end
    \\end
    \\
;

